### ISSUE TITLE
[Self-Managed]: Unable to install lower version Fleet Server on 8.0 snapshot.

### ISSUE THREAD

**Issue by amolnater-qasource** [elastic/fleet-server#1038]
**Kibana version:**  8.0.0 Snapshot Kibana self-managed environment

**Host OS and Browser version:** Windows, All

**Build details:**
```
Build: 48868
Commit: a29e0164a4af4d3135910cac9e6caa4478af5f3b
Artifact Link 7.16.2 agent: https://artifacts.elastic.co/downloads/beats/elastic-agent/elastic-agent-7.16.2-windows-x86_64.zip
```

**Preconditions:**
1. 8.0.0 Snapshot Kibana self-managed environment should be available.
2. 8.0 Self-managed should be setup using auto-configure feature[using fingerprints].

**Steps to reproduce:**
1. Login to Kibana environment.
2. Copy install command for Fleet-Server.
3. Manually removed the fingerprint flag, still user is not able to install lower version fleet-server.

**Screenshots:**
![3](https://user-images.githubusercontent.com/77374876/147545664-cd04731b-8fb4-4180-bb7c-4d5fdd9d3032.JPG)

**Note:**
- Before 8.0 Snapshot we are able to install lower version agents and fleet-servers from actual kibana version.
- We are also able to install lower version agents on 8.0 cloud environment.

**Expected Result:**
User should be able to install lower version fleet server on self-managed 8.0 Snapshot.

**Comment by amolnater-qasource** [comment]
@manishgupta-qasource Please review.

**Comment by manishgupta-qasource** [comment]
Reviewed & mention to @elastic/elastic-agent-control-plane

**Comment by EricDavisX** [comment]
I think this will be an expected issue, @amolnater-qasource due to the new fingerprint functionality as you note.  We can confirm with the team, of course.

**Comment by blakerouse** [comment]
@EricDavisX is correct. This should be expected as 8.0 now has security on by default. You either need to start the 8.0 elasticsearch with security off (is that still possible?), or provide the certificates and CA to the command so that Fleet Server can communicate correctly.

**Comment by amolnater-qasource** [comment]
Hi @blakerouse & @EricDavisX 
Thanks for looking into this.
>provide the certificates and CA to the command so that Fleet Server can communicate correctly.

Did you mean to create certs and try installing lower version agent with `Production mode`?
![5](https://user-images.githubusercontent.com/77374876/147632150-1f1f9c4f-9ce5-494a-8ba2-2336e3ac5c5b.JPG)

We attempted this, however we got no success.

**Screenshot:**
![6](https://user-images.githubusercontent.com/77374876/147632250-aaa682a3-15fa-46b4-99db-afde5110c2a7.JPG)

Please let us know if we are missing anything.
Thanks

**Comment by blakerouse** [comment]
@amolnater-qasource I think you are missing the `--fleet-server-es-ca` flag. That should point to the CA for the Elasticsearch.

**Comment by amolnater-qasource** [comment]
Hi @blakerouse 
We added the `--fleet-server-es-ca` flag, however we didn't get any success in installing lower version agent.
- When we run command with fingerprint flag, it shows Unknown flag error.
- When we removed fingerprint flag, it keeps showing x509- certificate signed by unknown authority.
- We even attempted with --insecure flag but got no success.

**Screenshot:**
![3](https://user-images.githubusercontent.com/77374876/147814589-10fabd97-7576-41f9-ad83-f7fd014156fe.JPG)

Thanks

**Comment by jlind23** [comment]
@michel-laterman @blakerouse could you chime in please?

**Comment by blakerouse** [comment]
@amolnater-qasource Are you generating the certificate that is being used by Elasticsearch or are you using the default certificates that Elasticsearch generates?

**Comment by amolnater-qasource** [comment]
Hi @blakerouse 
Thanks for looking into this.
We are generating certificates using elasticsearch-util tool available in elasticsearch\bin folder with below commands: 
- `elasticsearch-certutil ca --pem` to generate ca certs.
- `elasticsearch-certutil cert --name fleet-server --ca-cert C:\elk\elasticsearch-8.0.0-SNAPSHOT\ca\ca.crt --ca-key C:\elk\elasticsearch-8.0.0-SNAPSHOT\ca\ca.key --dns AmolWin-11-x64 --ip 10.0.x.xx --pem` to generate fleet-server certs.

cc: @jlind23 
Please let us know if we are missing anything.
Thanks!

**Comment by blakerouse** [comment]
@amolnater-qasource Thats to generate the certificates for Fleet Server, did you also use that command to generate the certificates for the running Elasticsearch?

**Comment by amolnater-qasource** [comment]
Hi @blakerouse 
We don't use any certs to run elasticsearch or kibana, we only use these certs to install Fleet-Server.
Is that required if we need to run elasticsearch using certs?
Thanks

**Comment by blakerouse** [comment]
@amolnater-qasource So that is your issue then, because with 8.0 elasticsearch always generates self-signed certificates, so the Fleet Server cannot communicate with the elasticsearch because of it.

To get a lower version of Fleet Server to connect to the newer version of elasticsearch, you will need to either provide the same CA that elasticsearch generated on its own, or generate your own for elasticsearch and provide it to Fleet Server.

**Comment by amolnater-qasource** [comment]
Hi @blakerouse 
We currently run elasticsearch and kibana with auto-configure method on 8.0 Snapshot.

**Details shared below:**
1. Download and extract elasticsearch and kibana 8.0 Snapshot artifacts.
2. Open cmd instance and navigate to elasticsearch\bin and run elasticsearch.
3. Copy the available Kibana enrollment token and password.
4. Now, open another cmd instance and navigate to kibana\bin and run kibana.bat
5. Observe a url with unique code http://localhost:5601:xxxxxx
6. Open this url and enter kibana enrollment token, click `Configure Elastic`.
7. Observe kibana setup is completed and fingerprint flags are available.
8. Create certificates for fleet server installation shared at https://github.com/elastic/fleet-server/issues/1038#issuecomment-1006326649

Could you please share some more details what we are missing? and how this can be resolved? it will be helpful.
We need some details to setup elasticsearch and kibana using self created certs.

**What we have tried:**
- We have tried to create the certs from elasticsearch-util manually and attempted to install lower version agent.
- As per our understanding 7.17 or lower version won't support fingerprint value, so we manually removed and attempted to install the lower version agent.

Thanks for looking into this.

**Comment by jlind23** [comment]
Hey @amolnater-qasource having an "old" fleet server with a fresh 8.0 install of Elasticsearch seems to be a strange testing scenario. 
Maybe you wanted to upgrade Elasticsearch first?
Then disabling the security by default should be the best things to do.

Indeed 7.17 or lower won't support fingerprint value, that's why when upgrading from 7.17 to 8.0 security will not be unable by default.

**Comment by amolnater-qasource** [comment]
Hi @jlind23 
>"old" fleet server with a fresh 8.0 install of Elasticsearch seems to be a strange testing scenario.

This scenario is covered to test the Agent & Fleet-Server upgrades.
**Scenario 1:**
As till 7.17, we are able to install lower version fleet-server and agents on both self-managed and cloud build.
However on 8.0 due to fingerprint change we are unable to install lower version agent.
As confirmed by you this is the current expected behaviour.

**Scenario 2:**
Further we are successfully able to test this scenario on upgrading the 7.16.3 self-managed kibana >8.0 self-managed kibana and also after this upgrade user didn't get an environment with `fingerprints`. That was working fine.

Hence we are **closing** this.
Thanks!
