### ISSUE TITLE
[Enhancement] Give administrators a greater degree of granularity for deploying output settings

### ISSUE THREAD

**Issue by nathandh22** [elastic/fleet-server#1049]
**Describe the enhancement:**
Managing Elastic Agents over Fleet is much easier for most use-cases. However, administrators managing Agents enrolled in Fleet only have the ability to deploy Elasticsearch Output settings globally. It would be very useful if we gave administrators the ability to deploy these settings to individual Agents or at least by Policy or Integration.

**Describe a specific use case for the enhancement or feature:**
Not all ingestion use-cases are going to fit the same configuration for their output queue settings. In some cases, it may make sense to increase the # of `workers` or `bulk_max_size`, while in others this can have a negative effect for their pipelines. If administrators are managing their Agents via Fleet, then they're stuck with deploying a one size fits all solution. In these specific use-cases, this limitation may force administrators into deploying Agents outside of Fleet just so they can manage their output settings independently via the `elastic-agent.yml` config file.

**Comment by m-hoskin-unisa** [comment]
The ability to configure logstash as an output rather than forcing elastic would also be useful. We're currently using standalone agents that have their config managed outside Elastic in order to use logstash as the ingestion point for all our agents.

**Comment by Chadwiki** [comment]
https://github.com/elastic/observability-dev/issues/1592
