### ISSUE TITLE
Http Done log messages

### ISSUE THREAD

**Issue by ruflin** [elastic/fleet-server#1083]
The http handler in fleet-server logs a "HTTP Done" log message every time a http request was handled: https://github.com/elastic/fleet-server/blob/8a4855bc5687cbc859dc5e82278366509ecf677e/internal/pkg/logger/http.go#L221 It logs additional meta information around response code, duration which is convenient for debugging purpose in case issues happen with fleet-server. At the same time it creates quite a bit of "ground noise" of logging events.

The question I would like to answer in this thread is if we should always log these events by default on the info level or potential reduce it through:

* Only log on the debug level
* Only log on info level if the response code is not 200
* Log a summary / counter of the check ins every x seconds
* Other ideas

![Screenshot 2022-01-12 at 10 13 45](https://user-images.githubusercontent.com/244900/149098637-1b64ef9b-3583-462c-a42a-9d607548fe28.png)

**Comment by ruflin** [comment]
@scunningham Would appreciate your thoughts on the above as you added this initially.

**Comment by scunningham** [comment]
Well, we get complaints that we don't have enough logging.  
And we get complaints that there's too much logging.

:shrug:

- It was originally debug, fine to default it back to debug.
- I'd be ok, with automatically changing level to info on non 2xx.  
- The summaries at this level are harder as this is just middleware, and probably not useful.  Should use metrics for that.

**Comment by ruflin** [comment]
Thanks for the input Sean. @ph Any thoughts on your end?

**Comment by ph** [comment]
Well summarized @scunningham :)

Agree with all the above, I would just hide it for 200 for now to reduce the noise, and we can check how we would like to track metrics on the different error code.
