### ISSUE TITLE
8.1.0-60713df1-SNAPSHOT fails to bootstrap

### ISSUE THREAD

**Issue by axw** [elastic/fleet-server#1090]
## Version

8.1.0-60713df1-SNAPSHOT

## Steps to reproduce

1. Clone https://github.com/elastic/apm-server/pull/7084 (`gh pr checkout https://github.com/elastic/apm-server/pull/7084` in apm-server clone, using https://github.com/cli/cli)
2. `docker-compose up -d`

This should cleanly start up Elasticsearch, Kibana, and Fleet Server. Fleet Server is failing to bootstrap, per the logs below:

## Logs

> `$ docker-compose logs -f fleet-server
Attaching to apm-server_fleet-server_1
fleet-server_1      | Requesting service_token from Kibana.
fleet-server_1      | Created service_token named: token-1642400976285
fleet-server_1      | Performing setup of Fleet in Kibana
fleet-server_1      | 
fleet-server_1      | {"log.level":"info","@timestamp":"2022-01-17T06:29:36.908Z","log.origin":{"file.name":"cmd/enroll_cmd.go","file.line":573},"message":"Spawning Elastic Agent daemon as a subprocess to complete bootstrap process.","ecs.version":"1.6.0"}
fleet-server_1      | {"log.level":"info","@timestamp":"2022-01-17T06:29:37.090Z","log.origin":{"file.name":"application/application.go","file.line":68},"message":"Detecting execution mode","ecs.version":"1.6.0"}
fleet-server_1      | {"log.level":"info","@timestamp":"2022-01-17T06:29:37.091Z","log.origin":{"file.name":"application/application.go","file.line":88},"message":"Agent is in Fleet Server bootstrap mode","ecs.version":"1.6.0"}
fleet-server_1      | {"log.level":"info","@timestamp":"2022-01-17T06:29:37.404Z","log.logger":"api","log.origin":{"file.name":"api/server.go","file.line":62},"message":"Starting stats endpoint","ecs.version":"1.6.0"}
fleet-server_1      | {"log.level":"info","@timestamp":"2022-01-17T06:29:37.404Z","log.origin":{"file.name":"application/fleet_server_bootstrap.go","file.line":130},"message":"Agent is starting","ecs.version":"1.6.0"}
fleet-server_1      | {"log.level":"info","@timestamp":"2022-01-17T06:29:37.404Z","log.logger":"api","log.origin":{"file.name":"api/server.go","file.line":64},"message":"Metrics endpoint listening on: /usr/share/elastic-agent/state/data/tmp/elastic-agent.sock (configured: unix:///usr/share/elastic-agent/state/data/tmp/elastic-agent.sock)","ecs.version":"1.6.0"}
fleet-server_1      | {"log.level":"info","@timestamp":"2022-01-17T06:29:37.404Z","log.origin":{"file.name":"application/fleet_server_bootstrap.go","file.line":140},"message":"Agent is stopped","ecs.version":"1.6.0"}
fleet-server_1      | {"log.level":"info","@timestamp":"2022-01-17T06:29:37.938Z","log.origin":{"file.name":"cmd/enroll_cmd.go","file.line":745},"message":"Waiting for Elastic Agent to start Fleet Server","ecs.version":"1.6.0"}
fleet-server_1      | {"log.level":"info","@timestamp":"2022-01-17T06:29:39.346Z","log.origin":{"file.name":"stateresolver/stateresolver.go","file.line":48},"message":"New State ID is cqtqUFog","ecs.version":"1.6.0"}
fleet-server_1      | {"log.level":"info","@timestamp":"2022-01-17T06:29:39.346Z","log.origin":{"file.name":"stateresolver/stateresolver.go","file.line":49},"message":"Converging state requires execution of 1 step(s)","ecs.version":"1.6.0"}
fleet-server_1      | {"log.level":"info","@timestamp":"2022-01-17T06:29:40.066Z","log.origin":{"file.name":"log/reporter.go","file.line":40},"message":"2022-01-17T06:29:40Z - message: Application: fleet-server--8.1.0-SNAPSHOT[]: State changed to STARTING: Starting - type: 'STATE' - sub_type: 'STARTING'","ecs.version":"1.6.0"}
fleet-server_1      | {"log.level":"info","@timestamp":"2022-01-17T06:29:40.067Z","log.origin":{"file.name":"stateresolver/stateresolver.go","file.line":66},"message":"Updating internal state","ecs.version":"1.6.0"}
fleet-server_1      | {"log.level":"warn","@timestamp":"2022-01-17T06:29:41.587Z","log.origin":{"file.name":"status/reporter.go","file.line":236},"message":"Elastic Agent status changed to: 'degraded'","ecs.version":"1.6.0"}
fleet-server_1      | {"log.level":"info","@timestamp":"2022-01-17T06:29:41.587Z","log.origin":{"file.name":"log/reporter.go","file.line":40},"message":"2022-01-17T06:29:41Z - message: Application: fleet-server--8.1.0-SNAPSHOT[]: State changed to DEGRADED: Running on default policy with Fleet Server integration; missing config fleet.agent.id (expected during bootstrap process) - type: 'STATE' - sub_type: 'RUNNING'","ecs.version":"1.6.0"}
fleet-server_1      | {"log.level":"info","@timestamp":"2022-01-17T06:29:43.941Z","log.origin":{"file.name":"cmd/enroll_cmd.go","file.line":759},"message":"Fleet Server - Running on default policy with Fleet Server integration; missing config fleet.agent.id (expected during bootstrap process)","ecs.version":"1.6.0"}
fleet-server_1      | {"log.level":"info","@timestamp":"2022-01-17T06:29:44.078Z","log.origin":{"file.name":"cmd/enroll_cmd.go","file.line":456},"message":"Starting enrollment to URL: https://fleet-server:8220/","ecs.version":"1.6.0"}
fleet-server_1      | {"log.level":"info","@timestamp":"2022-01-17T06:29:44.455Z","log.origin":{"file.name":"cmd/run.go","file.line":185},"message":"Shutting down Elastic Agent and sending last events...","ecs.version":"1.6.0"}
fleet-server_1      | {"log.level":"info","@timestamp":"2022-01-17T06:29:44.455Z","log.origin":{"file.name":"operation/operator.go","file.line":216},"message":"waiting for installer of pipeline 'default' to finish","ecs.version":"1.6.0"}
fleet-server_1      | {"log.level":"info","@timestamp":"2022-01-17T06:29:44.455Z","log.origin":{"file.name":"process/app.go","file.line":176},"message":"Signaling application to stop because of shutdown: fleet-server--8.1.0-SNAPSHOT","ecs.version":"1.6.0"}
fleet-server_1      | {"log.level":"info","@timestamp":"2022-01-17T06:29:45.957Z","log.origin":{"file.name":"status/reporter.go","file.line":236},"message":"Elastic Agent status changed to: 'online'","ecs.version":"1.6.0"}
fleet-server_1      | {"log.level":"info","@timestamp":"2022-01-17T06:29:45.957Z","log.origin":{"file.name":"cmd/run.go","file.line":193},"message":"Shutting down completed.","ecs.version":"1.6.0"}
fleet-server_1      | {"log.level":"info","@timestamp":"2022-01-17T06:29:45.957Z","log.origin":{"file.name":"log/reporter.go","file.line":40},"message":"2022-01-17T06:29:45Z - message: Application: fleet-server--8.1.0-SNAPSHOT[]: State changed to STOPPED: Stopped - type: 'STATE' - sub_type: 'STOPPED'","ecs.version":"1.6.0"}
fleet-server_1      | {"log.level":"info","@timestamp":"2022-01-17T06:29:45.957Z","log.logger":"api","log.origin":{"file.name":"api/server.go","file.line":66},"message":"Stats endpoint (/usr/share/elastic-agent/state/data/tmp/elastic-agent.sock) finished: accept unix /usr/share/elastic-agent/state/data/tmp/elastic-agent.sock: use of closed network connection","ecs.version":"1.6.0"}
fleet-server_1      | Error: fail to enroll: fail to execute request to fleet-server: status code: 400, fleet-server returned an error: BadRequest
fleet-server_1      | For help, please see our troubleshooting guide at https://www.elastic.co/guide/en/fleet/8.1/fleet-troubleshooting.html
fleet-server_1      | Error: enrollment failed: exit status 1
fleet-server_1      | For help, please see our troubleshooting guide at https://www.elastic.co/guide/en/fleet/8.1/fleet-troubleshooting.html
apm-server_fleet-server_1 exited with code 1`

**Comment by axw** [comment]
I don't see any commits here or in beats that obviously explain why, but the latest snapshot seems to be happier: https://github.com/elastic/fleet-server/pull/1097

**Comment by ph** [comment]
@axw We can close this one?

**Comment by axw** [comment]
I left it open for you all to look into, but a more recent image is working so I guess it's related to the default policy removal.
