### ISSUE TITLE
Add FleetServer version to Status API

### ISSUE THREAD

**Issue by thbkrkr** [elastic/fleet-server#1108]
#### Proposal

Add the current version of FleetServer in the status API as it is for other Elastic products.

Examples:
```
# Elasticsearch
> curl -sku $AUTH https://localhost:9200/ | jq .version
{
  "number": "7.16.1",
  "build_flavor": "default",
  "build_type": "docker",
  "build_hash": "5b38441b16b1ebb16a27c107a4c3865776e20c53",
  "build_date": "2021-12-11T00:29:38.865893768Z",
  "build_snapshot": false,
  "lucene_version": "8.10.1",
  "minimum_wire_compatibility_version": "6.8.0",
  "minimum_index_compatibility_version": "6.0.0-beta1"
}

# Kibana
> curl -sku $AUTH https://localhost:5601/api/status | jq .version
{
  "number": "7.16.1",
  "build_hash": "8751518b4a507d6659d93735b6f90d164514327a",
  "build_number": 46258,
  "build_snapshot": false
}

# EnterpriseSearch
> curl -sku $AUTH https://localhost:3002/api/ent/v1/internal/version | jq .
{
  "number": "7.16.2",
  "build_hash": "0b1d8ae4de8888ad38c18eff255acbacf5eae306",
  "build_date": "2021-12-18T19:56:48Z"
}
```

#### Use-case

Provide a way for ECK to verify the compatibiilty between the version of an Agent managed by ECK and the version of an associated FleetServer (see [ECK documentation to connect an Agent to a FleetServer]( https://www.elastic.co/guide/en/cloud-on-k8s/master/k8s-elastic-agent-fleet-configuration.html#k8s-elastic-agent-fleet-configuration-setting-referenced-resources)) when the FleetServer is not managed by ECK. In this case, ECK only knows the URL, the username, the password and maybe the CA of the FleetServer and could get its version by requesting `/api/status`.

**Comment by scunningham** [comment]
We should not expose this data unauthenticated.  It servers as a fingerprint for an attacker.  If the requests supplies a valid api key, we can append the additional versioning data.

**Comment by thbkrkr** [comment]
Yes, makes sense and not a problem for my use-case.

**Comment by aleksmaus** [comment]
will update the PR with suggested change

**Comment by ph** [comment]
@scunningham Would be good to have a uniform strategy with Elasticsearch.

**Comment by scunningham** [comment]
@ph I believe you need creds in elastic if auth is enabled.  Not sure about kibana.

In any case, it is not recommended [security practice](https://owasp.org/www-project-web-security-testing-guide/latest/4-Web_Application_Security_Testing/01-Information_Gathering/02-Fingerprint_Web_Server) to expose software fingerprinting information unauthenticated.

**Comment by ph** [comment]
@scunningham Thanks sean, totally agree on the why. Maybe I've used too much ES without credentials for testing and it did change in some releases.
