### ISSUE TITLE
Elastic-agent not monitor windows nodes in AKS

### ISSUE THREAD

**Issue by mtloaprhn** [elastic/fleet-server#1124]
Hey guys,

I deployed elastic-agent by the K8S manifest in the documentation page ([https://www.elastic.co/guide/en/fleet/master/running-on-kubernetes-managed-by-fleet.html](https://www.elastic.co/guide/en/fleet/master/running-on-kubernetes-managed-by-fleet.html)) and agents are good and I have all Kubernetes metrics for Linux nodes only in my Dashboards and I thinked this agent could be monitor Linux and Windows nodes, but, seems not.

So, to monitor my windows nodes, I created a elastic-agent windows container. I use the previous manifest to deploy a new daemonset for my windows agents, and using the same Kubernetes roles/clusteroles created previously for linux agents.

After few tries, my agents seems works and are "Healthy" on the agent list in Fleet management and are in the right policy, but, when I view for example **_"[Metrics] - Kubernetes overview"_** I have only my linux nodes monitored by linux agents.

My entrypoint is : 

```
$AGENT_PATH = (Get-ChildItem C:\ -Filter "elastic-agent*" -Directory).Fullname

Start-Process "$($AGENT_PATH)\elastic-agent.exe" -ArgumentList "container '$@' --path.install $($AGENT_PATH) --c $($AGENT_PATH)\elastic-agent.yml" -NoNewWindow -Wait
```

Agent logs are good without any warning or error.

Anyone had a similar behavior with Windows container ?

Thanks in advance for your advices .

**Comment by mtloaprhn** [comment]
I added this lines : 
```
tolerations:
        - key: node-role.kubernetes.io/master
          effect: NoSchedule
          key: cattle.io/os
          operator: Equal
          value: linux
```
And it's working.

**Comment by mtloaprhn** [comment]
I check the data and the elastic-agent have any data. My windows nodes not fully supported.

**Comment by jlind23** [comment]
Closing this one as outdated/not prioritised, we will reopen it later if required.
cc @ycombinator
