### ISSUE TITLE
"elastic fail 503::" - Improve log message for better debug

### ISSUE THREAD

**Issue by AndersonQ** [elastic/fleet-server#1128]
**Describe the enhancement:**

At least some error logs from fleet server provide little, sometimes almost no information about the root cause of the error.
[`ErrElastic`](https://github.com/elastic/fleet-server/blob/master/internal/pkg/es/error.go#L15).`Error()` method can be improved to account for `ErrElastic.Cause` not being empty, and produce a more clear message than _elastic fail..._. _elastic_ is too broad term, it seems to refer to elasticsearch errors, that can be made explicit in the error message as we all documenting the type.

The current `Error` method often produces `elastic fail 503::`, which is cryptic for anyone not quite familiar with the code.
**Describe a specific use case for the enhancement or feature:**

Investigate production issues

**Comment by michel-laterman** [comment]
This was implemented in https://github.com/elastic/fleet-server/pull/1684/files#diff-fefef321d478decf3f5ced5c3b9e41ad4ebc99b4a8f72cb1a230cd5570161858
