### ISSUE TITLE
Hosted Fleet Server not available on Healthy deployment of 8.1 BC-1

### ISSUE THREAD

**Issue by amolnater-qasource** [elastic/fleet-server#1132]
**Description:**
Hosted Fleet Server not available on Healthy deployment of 8.1 BC-1 when deployed from:
- https://cloud.elastic.co/
- https://staging.found.no/

**Screenshots:**
![1](https://user-images.githubusercontent.com/77374876/152472690-9ee97d0d-26f4-498a-a5dc-6e14122fd6d9.JPG)

![4](https://user-images.githubusercontent.com/77374876/152472973-1a2b9e50-177a-4164-96f2-25e6c5bfd8bc.JPG)

![3](https://user-images.githubusercontent.com/77374876/152472684-f8a3f182-860f-4c99-a696-d15d01bf1376.JPG)

No-activity on page for few minutes leads to:
![2](https://user-images.githubusercontent.com/77374876/152472689-789fe1f4-28dc-416c-905c-3b8cf7ea8618.JPG)
**Note:**
No errors were observed on deployment page.

**Comment by amolnater-qasource** [comment]
@manishgupta-qasource Please review.

**Comment by manishgupta-qasource** [comment]
Reviewed & mention to @jlind23

**Comment by jlind23** [comment]
the pipeline is failing for a couple of days due to a issue. Thus it may explain why the fleet-server installer is not available.

**Comment by amolnater-qasource** [comment]
Hi @jlind23 
We have observed this issue on latest 8.1 Snapshot build too.

**Screenshot:**
![image](https://user-images.githubusercontent.com/77374876/153206727-ac3d15ce-8664-4884-917d-543206621ae1.png)

**Build details:**
BUILD: 50203
COMMIT: dd503b312534b3ade6da21625793fbbc87191a04

Thanks

**Comment by jlind23** [comment]
So you can not find any policies right?

**Comment by amolnater-qasource** [comment]
@jlind23 We are not getting the Hosted fleet server, however we are getting Elastic cloud agent policy as expected.

**Screenshots:**
![image](https://user-images.githubusercontent.com/77374876/153368206-bec655e4-5178-4352-8e0e-2ddd769e18b9.png)
![image](https://user-images.githubusercontent.com/77374876/153368253-fb068db3-e245-45cb-a6f4-c8d4caf1e781.png)

Thanks

**Comment by jlind23** [comment]
@amolnater-qasource do you have any logs to provide? 
@ph i suspect this is due to the removal of default fleet policy?

**Comment by jlind23** [comment]
Open fleet, then click on the host and you should be able to access the fleet integrations log.
@ph i'll soon be on PTO so I may need your help following up here.

**Comment by ph** [comment]
> @ph i suspect this is due to the removal of default fleet policy?

This shouldn't be the case, This is an hosted Agent,

The issue only affects on-premise environment that are completely automated.

**Comment by amolnater-qasource** [comment]
Hi @jlind23 
There are no logs available for hosted agent and managed policy doesn't allow to enable logs for this Hosted fleet server.

**Screenshot:**
![image](https://user-images.githubusercontent.com/77374876/153539172-d45899d6-7ede-498a-939d-ba72ca685837.png)
![image](https://user-images.githubusercontent.com/77374876/153539338-28998c2e-bf50-4b3c-a21d-977b1d714795.png)

Further we are also blocked to install further agents/fleet-server on this environment.
Please let us know if anything else is required from our end.
Thanks!

**Comment by nchaulet** [comment]
Not sure what the status of that issue but just tested a 8.1 deployment and my Fleet server is switching from online to offline and there is a lot of these in Fleet server logs
<img width="1408" alt="Screen Shot 2022-02-11 at 3 14 36 PM" src="https://user-images.githubusercontent.com/1336873/153663564-74e1d319-a5e8-454c-807a-8b486f59d7ab.png">
