### ISSUE TITLE
[Self-Managed]: Unable to install Fleet Server on 8.1 BC-1.

### ISSUE THREAD

**Issue by amolnater-qasource** [elastic/fleet-server#1134]
**Kibana version:**  8.1 BC-1 Kibana self-managed environment

**Host OS:** Windows 10x64

**Build details:**
```
BUILD: 50114
COMMIT: 47a2516a0cf6c227f0cb180e9a085d7d99c77d12
Artifact Link: https://staging.elastic.co/8.1.0-3c27bc9c/summary-8.1.0.html
```

**Pre-requirements:**
1. ELK setup should be completed.

**Steps to reproduce:**
1. Login to Kibana and navigate to Fleet>Agents tab.
2. Add host ip:`https://1.1.1.1:8220`.
3. Generate token and copy fleet server install command for windows.
4. Run agent install command and observe `Error: enroll command failed with exit code: 1`.

**Expected Result:**
Fleet-server should get installed on running agent install command on 8.1 BC-4.

**Screenshots:**
![6](https://user-images.githubusercontent.com/77374876/152493328-f5856bd3-54ae-440c-904c-f72c5109fe6e.JPG)

**Comment by amolnater-qasource** [comment]
@manishgupta-qasource Please review.

**Comment by amolnater-qasource** [comment]
Similar issue at: https://github.com/elastic/fleet-server/issues/1129

**Comment by manishgupta-qasource** [comment]
Reviewed & mention to @jlind23

**Comment by jlind23** [comment]
Thanks, it should be fixed in a couple of days as soon as the binary will be released.

**Comment by amolnater-qasource** [comment]
Hi @jlind23 
We have revalidated this issue on 8.1 BC2 self-managed environment and we are successfully able to install Fleet Server.

**Screenshot:**
![1](https://user-images.githubusercontent.com/77374876/153543649-8886ef59-bdac-455a-bbec-46cd7a49c98f.JPG)

**Build details:**
BUILD: 50222
COMMIT: ee89ebfddeda3baaf6cd87c0299247c5248cb952
Artifact Link: https://staging.elastic.co/8.1.0-024d23aa/summary-8.1.0.html

Hence we are **closing** this issue.
Thanks
