### ISSUE TITLE
Report degraded status from Fleet Server if there is an issue with indices monitoring

### ISSUE THREAD

**Issue by aleksmaus** [elastic/fleet-server#119]
**Describe the enhancement:**
Report degraded status from Fleet Server if there is an issue with indices monitoring and keep Fleet Server running. 
The Fleet Server will not be able to detect new actions and the new policy changes in this state.
Follow up on https://github.com/elastic/fleet-server/issues/115

**Describe a specific use case for the enhancement or feature:**
The current implementation of the new actions and policy changes detection relies on the Elasticsearch index global checkpoint. In order for it to work properly we can only have one index/one shard for the documents, possibly until we get a more robust support for this feature at Elasticsearch level.
Presently the .fleet-actions and .fleet-policies indices are replaced with aliases. 
Need to handle the situation were we have two or more indices by mistake behind the alias, log the error, indicated the degraded status back to the agent and keep Fleet Server running.

**Comment by jlind23** [comment]
@michel-laterman is this one still relevant?
cc @ycombinator

**Comment by michel-laterman** [comment]
I think that since we changed the self-monitors we report degraded if they fail to connect

**Comment by jlind23** [comment]
Thanks @michel-laterman hence closing this as done.
