### ISSUE TITLE
elastic-agent can not install in macbook

### ISSUE THREAD

**Issue by qiansheng2** [elastic/fleet-server#1209]
- Version: 
   elastic-agent-8.1.0
- Operating System: 
  macbook(apple m1 max)  macos12.2.1
- Steps to Reproduce: 
   Download elastic-agent-8.1.0-darwin-x86_64
   unzip
   sudo ./elastic-agent install ...
   
error:
-> % sudo ./elastic-agent install  \
  --fleet-server-es=http://localhost:9200 \
  --fleet-server-service-token=AAEAAWVsYXN0aWMvZmxlZXQtc2VydmVyL3Rva2VuLTE2NDY3OTUxOTE1Mjk6cFJ1UDdGbUtUMnVzcVMyZDBJU3VKdw \
  --fleet-server-policy=499b5aa7-d214-5b5d-838b-3cd76469844e \
  --fleet-server-insecure-http
Elastic Agent will be installed at /Library/Elastic/Agent and will run as a service. Do you want to continue? [Y/n]:Y
{"log.level":"info","@timestamp":"2022-03-09T11:10:22.924+0800","log.origin":{"file.name":"cmd/enroll_cmd.go","file.line":777},"message":"Fleet Server - Starting","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2022-03-09T11:10:26.926+0800","log.origin":{"file.name":"cmd/enroll_cmd.go","file.line":777},"message":"Fleet Server - Error - EOF","ecs.version":"1.6.0"}
Error: fleet-server failed: context canceled

**Comment by qiansheng2** [comment]
Version:
   Macbook Pro(Apple M1 Max)
   docker desktop  4.5.0（Engine:20.10.12）
   docker compose v2.2.3

I installed the docker image from ==>  https://www.elastic.co/guide/en/elasticsearch/reference/8.1/docker.html#docker-prod-prerequisites

**Comment by qiansheng2** [comment]
add:

{"log.level":"info","@timestamp":"2022-03-09T11:47:41.164+0800","log.origin":{"file.name":"cmd/enroll_cmd.go","file.line":777},"message":"Fleet Server - Error - could not start the HTTP server for the API: could not set mode 480 for unix socket file at location /Library/Elastic/Agent/data/tmp/default/fleet-server/fleet-server.sock: chmod /Library/Elastic/Agent/data/tmp/default/fleet-server/fleet-server.sock: no such file or directory","ecs.version":"1.6.0"}

**Comment by qiansheng2** [comment]
add by elasticsearch log out:

es-cluster-es01-1    | {"@timestamp":"2022-03-09T05:40:10.120Z", "log.level": "WARN", "message":"received plaintext http traffic on an https channel, closing connection Netty4HttpChannel{localAddress=/172.21.0.3:9200, remoteAddress=/172.21.0.1:64874}", "ecs.version": "1.2.0","service.name":"ES_ECS","event.dataset":"elasticsearch.server","process.thread.name":"elasticsearch[es01][transport_worker][T#2]","log.logger":"org.elasticsearch.xpack.security.transport.netty4.SecurityNetty4HttpServerTransport","elasticsearch.cluster.uuid":"RYv_WVG8RNeOQL05TSPOqg","elasticsearch.node.id":"Pu9F4WPLT86_hGgcQRpDbg","elasticsearch.node.name":"es01","elasticsearch.cluster.name":"docker-cluster"}
es-cluster-es01-1    | {"@timestamp":"2022-03-09T05:40:10.120Z", "log.level": "WARN", "message":"received plaintext http traffic on an https channel, closing connection Netty4HttpChannel{localAddress=/172.21.0.3:9200, remoteAddress=/172.21.0.1:64876}", "ecs.version": "1.2.0","service.name":"ES_ECS","event.dataset":"elasticsearch.server","process.thread.name":"elasticsearch[es01][transport_worker][T#3]","log.logger":"org.elasticsearch.xpack.security.transport.netty4.SecurityNetty4HttpServerTransport","elasticsearch.cluster.uuid":"RYv_WVG8RNeOQL05TSPOqg","elasticsearch.node.id":"Pu9F4WPLT86_hGgcQRpDbg","elasticsearch.node.name":"es01","elasticsearch.cluster.name":"docker-cluster"}
es-cluster-es01-1    | {"@timestamp":"2022-03-09T05:40:10.120Z", "log.level": "WARN", "message":"received plaintext http traffic on an https channel, closing connection Netty4HttpChannel{localAddress=/172.21.0.3:9200, remoteAddress=/172.21.0.1:64862}", "ecs.version": "1.2.0","service.name":"ES_ECS","event.dataset":"elasticsearch.server","process.thread.name":"elasticsearch[es01][transport_worker][T#4]","log.logger":"org.elasticsearch.xpack.security.transport.netty4.SecurityNetty4HttpServerTransport","elasticsearch.cluster.uuid":"RYv_WVG8RNeOQL05TSPOqg","elasticsearch.node.id":"Pu9F4WPLT86_hGgcQRpDbg","elasticsearch.node.name":"es01","elasticsearch.cluster.name":"docker-cluster"}
es
............

**Comment by ph** [comment]
Running Agent on M1 is not yet supported, we are working on it. (see our [current matrix)](https://www.elastic.co/support/matrix)

**Comment by qiansheng2** [comment]
thanks for your comment.

**Comment by ph** [comment]
I should add we are actively working on it, see https://github.com/elastic/beats/pull/29585

**Comment by ph** [comment]
fyi @AndersonQ related to your M1 work

**Comment by AndersonQ** [comment]
Thanks, I'm gonna ensure we cover this when testing the M1 agent

**Comment by jlind23** [comment]
@AndersonQ shouldn't we close this one and keep only the M1 build?

**Comment by AndersonQ** [comment]
I'd say so.
