### ISSUE TITLE
Elastic Fleet Server problem

### ISSUE THREAD

**Issue by jcimins** [elastic/fleet-server#1210]
https://discuss.elastic.co/t/fleet-server-problems/299204

Problem with setting up fleet server on Ubuntu 20.04 - all updates are on and Elastic+Kibana works fine. I can add beat logs as well. 
When I try to set up Fleet server I get this error:
siem@siem:~/elastic-agent-8.1.0-linux-x86_64$ sudo ./elastic-agent install   \
>   --fleet-server-es=http://172.23.27.98:9200 \
>   --fleet-server-service-token=AAEAAWVsYXN0aWMvZmxlZXQtc2VydmVyL3Rva2VuLTE2NDY4MjU0NTQ2NzU6V09RbURVak9RMy0tUG0yeVZ2b3ZtUQ \
>   --fleet-server-policy=34da2970-9f9c-11ec-83d5-65e20cafef36 \
>   --fleet-server-insecure-http
Elastic Agent will be installed at /opt/Elastic/Agent and will run as a service. Do you want to continue? [Y/n]:y
{"log.level":"info","@timestamp":"2022-03-09T11:31:10.254Z","log.origin":{"file.name":"cmd/enroll_cmd.go","file.line":744},"message":"Waiting for Elastic Agent to start Fleet Server","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2022-03-09T11:31:12.256Z","log.origin":{"file.name":"cmd/enroll_cmd.go","file.line":777},"message":"Fleet Server - Starting","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2022-03-09T11:31:16.260Z","log.origin":{"file.name":"cmd/enroll_cmd.go","file.line":777},"message":"Fleet Server - Error - failed version compatibility check with elasticsearch: unsupported version","ecs.version":"1.6.0"}
Error: fleet-server failed: context canceled
For help, please see our troubleshooting guide at https://www.elastic.co/guide/en/fleet/8.1/fleet-troubleshooting.html
Error: enroll command failed with exit code: 1
For help, please see our troubleshooting guide at https://www.elastic.co/guide/en/fleet/8.1/fleet-troubleshooting.html
siem@siem:~/elastic-agent-8.1.0-linux-x86_64$

Was downloading this elastic agent version:
https://artifacts.elastic.co/downloads/beats/elastic-agent/elastic-agent-8.1.0-linux-x86_64.tar.gz

I see that this is already 2nd error with Fleet server >> https://github.com/elastic/fleet-server/issues/1209

**Comment by qiansheng2** [comment]
As same error as my issue(#1209) in "{"file.name":"cmd/enroll_cmd.go","file.line":777}".

**Comment by jcimins** [comment]
I have the same error on Windows installation as well (just tested)

**Comment by ph** [comment]
@jcimins @qiansheng2 Kibana and Elasticsearch are running on 8.1?

**Comment by qiansheng2** [comment]
> 

Yes, they are running on ver8.1.0.

**Comment by ruflin** [comment]
Of course, 8.1.0 should work with 8.1.0. The error seems to come from here: https://github.com/elastic/fleet-server/blob/8.1/internal/pkg/ver/check.go#L40 

@jcimins @qiansheng2 When you start the Elastic Agent, in the logs directory there should be a log file from fleet-server that logs more details around what the exact versions of Elasticsearch and fleet-server it detects. Any chance you could share the content of this fleet-server log file?

**Comment by ph** [comment]
@ruflin I've already made the change in https://github.com/elastic/fleet-server/pull/1211, I've recently worked with 8.2.0 (main) and I didn't experience that issues so I am a bit surprised by it.

**Comment by ph** [comment]
Looking at the code, it look to behave as expected.

@jcimins @qiansheng2 The log would help us here, can you also do `elastic-agent version` ?

**Comment by qiansheng2** [comment]
-> % ./elastic-agent version
Binary: 8.1.0 (build: da4d9c00179e062b6d88c9dbe07d89b3d195d9d0 at 2022-03-03 17:48:46 +0000 UTC)
Daemon: <failed to communicate>
could not get version. failed to communicate with running daemon: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial unix /Users/nick/es-cluster/elastic-agent-8.1.0-darwin-x86_64/data/tmp/elastic-agent-control.sock: connect: no such file or directory"
Use --binary-only flag to skip trying to retrieve version from running daemon

**Comment by qiansheng2** [comment]
I run ./elastic-agent install .... once again.

1.  In elastic console log，there are many logs as blow:
es-cluster-es01-1    | {"@timestamp":"2022-03-10T17:52:04.038Z", "log.level": "WARN", "message":"received plaintext http traffic on an https channel, closing connection Netty4HttpChannel{localAddress=/172.21.0.3:9200, remoteAddress=/172.21.0.1:65526}", "ecs.version": "1.2.0","service.name":"ES_ECS","event.dataset":"elasticsearch.server","process.thread.name":"elasticsearch[es01][transport_worker][T#4]","log.logger":"org.elasticsearch.xpack.security.transport.netty4.SecurityNetty4HttpServerTransport","elasticsearch.cluster.uuid":"RYv_WVG8RNeOQL05TSPOqg","elasticsearch.node.id":"Pu9F4WPLT86_hGgcQRpDbg","elasticsearch.node.name":"es01","elasticsearch.cluster.name":"docker-cluster"}
es-cluster-es01-1    | {"@timestamp":"2022-03-10T17:52:04.038Z", "log.level": "WARN", "message":"received plaintext http traffic on an https channel, closing connection Netty4HttpChannel{localAddress=/172.21.0.3:9200, remoteAddress=/172.21.0.1:65530}", "ecs.version": "1.2.0","service.name":"ES_ECS","event.dataset":"elasticsearch.server","process.thread.name":"elasticsearch[es01][transport_worker][T#2]","log.logger":"org.elasticsearch.xpack.security.transport.netty4.SecurityNetty4HttpServerTransport","elasticsearch.cluster.uuid":"RYv_WVG8RNeOQL05TSPOqg","elasticsearch.node.id":"Pu9F4WPLT86_hGgcQRpDbg","elasticsearch.node.name":"es01","elasticsearch.cluster.name":"docker-cluster"}
es-cluster-es01-1    | {"@timestamp":"2022-03-10T17:52:04.368Z", "log.level": "WARN", "message":"received plaintext http traffic on an https channel, closing connection Netty4HttpChannel{localAddress=/172.21.0.3:9200, remoteAddress=/172.21.0.1:55000}", "ecs.version": "1.2.0","service.name":"ES_ECS","event.dataset":"elasticsearch.server","process.thread.name":"elasticsearch[es01][transport_worker][T#1]","log.logger":"org.elasticsearch.xpack.security.transport.netty4.SecurityNetty4HttpServerTransport","elasticsearch.cluster.uuid":"RYv_WVG8RNeOQL05TSPOqg","elasticsearch.node.id":"Pu9F4WPLT86_hGgcQRpDbg","elasticsearch.node.name":"es01","elasticsearch.cluster.name":"docker-cluster"} 

2. In the terminal :

-> % sudo ./elastic-agent install  \
  --fleet-server-es=http://localhost:9200 \
  --fleet-server-service-token=AAEAAWVsYXN0aWMvZmxlZXQtc2VydmVyL3Rva2VuLTE2NDY5MzQ2NTI5MTM6ZU10TWktdm5SSU9fVzdKd2V1MC16QQ \
  --fleet-server-policy=fleet-server-policy \
  --fleet-server-insecure-http
Password:
Elastic Agent will be installed at /Library/Elastic/Agent and will run as a service. Do you want to continue? [Y/n]:y
{"log.level":"info","@timestamp":"2022-03-11T01:51:27.152+0800","log.origin":{"file.name":"cmd/enroll_cmd.go","file.line":744},"message":"Waiting for Elastic Agent to start Fleet Server","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2022-03-11T01:51:29.208+0800","log.origin":{"file.name":"cmd/enroll_cmd.go","file.line":727},"message":"Waiting for Elastic Agent to start","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2022-03-11T01:51:33.262+0800","log.origin":{"file.name":"cmd/enroll_cmd.go","file.line":777},"message":"Fleet Server - Starting","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2022-03-11T01:51:41.265+0800","log.origin":{"file.name":"cmd/enroll_cmd.go","file.line":777},"message":"Fleet Server - Error - EOF","ecs.version":"1.6.0"}
Error: fleet-server failed: context canceled
For help, please see our troubleshooting guide at https://www.elastic.co/guide/en/fleet/8.1/fleet-troubleshooting.html
Error: enroll command failed with exit code: 1
For help, please see our troubleshooting guide at https://www.elastic.co/guide/en/fleet/8.1/fleet-troubleshooting.html

**Comment by qiansheng2** [comment]
I start my elasticsearch in docker desktop, the log is:
-> % docker compose up
[+] Running 5/0
 ⠿ Container es-cluster-setup-1   Create...                                0.0s
 ⠿ Container es-cluster-es01-1    Created                                  0.0s
 ⠿ Container es-cluster-es02-1    Created                                  0.0s
 ⠿ Container es-cluster-es03-1    Created                                  0.0s
 ⠿ Container es-cluster-kibana-1  Creat...                                 0.0s
Attaching to es-cluster-es01-1, es-cluster-es02-1, es-cluster-es03-1, es-cluster-kibana-1, es-cluster-setup-1
es-cluster-setup-1   | Creating CA
es-cluster-setup-1   | bash: line 10: bin/elasticsearch-certutil: Permission denied
es-cluster-setup-1   | Archive:  config/certs/ca.zip
es-cluster-setup-1   | replace config/certs/ca/ca.crt? [y]es, [n]o, [A]ll, [N]one, [r]ename:  NULL
es-cluster-setup-1   | (EOF or read error, treating as "[N]one" ...)
es-cluster-setup-1   | Creating certs
es-cluster-setup-1   | bash: line 36: bin/elasticsearch-certutil: Permission denied
es-cluster-setup-1   | Archive:  config/certs/certs.zip
es-cluster-setup-1   | replace config/certs/es01/es01.crt? [y]es, [n]o, [A]ll, [N]one, [r]ename:  NULL
es-cluster-setup-1   | (EOF or read error, treating as "[N]one" ...)
es-cluster-setup-1   | Setting file permissions
es-cluster-setup-1   | Waiting for Elasticsearch availability
es-cluster-es01-1    | {"@timestamp":"2022-03-10T17:41:12.048Z", "log.level": "INFO", "message":"version[8.1.0], pid[7], build[default/docker/3700f7679f7d95e36da0b43762189bab189bc53a/2022-03-03T14:20:00.690422633Z], OS[Linux/5.10.76-linuxkit/aarch64], JVM[Eclipse Adoptium/OpenJDK 64-Bit Server VM/17.0.2/17.0.2+8]", "ecs.version": "1.2.0","service.name":"ES_ECS","event.dataset":"elasticsearch.server","process.thread.name":"main","log.logger":"org.elasticsearch.node.Node","elasticsearch.node.name":"es01","elasticsearch.cluster.name":"docker-cluster"}
es-cluster-es01-1    | {"@timestamp":"2022-03-10T17:41:12.051Z", "log.level": "INFO", "message":"JVM home [/usr/share/elasticsearch/jdk], using bundled JDK [true]", "ecs.version": "1.2.0","service.name":"ES_ECS","event.dataset":"elasticsearch.server","process.thread.name":"main","log.logger":"org.elasticsearch.node.Node","elasticsearch.node.name":"es01","elasticsearch.cluster.name":"docker-cluster"}
es-cluster-es01-1    | {"@timestamp":"2022-03-10T17:41:12.052Z", "log.level": "INFO", "message":"JVM arguments [-Xshare:auto, -Des.networkaddress.cache.ttl=60, -Des.networkaddress.cache.negative.ttl=10, -Djava.security.manager=allow, -XX:+AlwaysPreTouch, -Xss1m, -Djava.awt.headless=true, -Dfile.encoding=UTF-8, -Djna.nosys=true, -XX:-OmitStackTraceInFastThrow, -XX:+ShowCodeDetailsInExceptionMessages, -Dio.netty.noUnsafe=true, -Dio.netty.noKeySetOptimization=true, -Dio.netty.recycler.maxCapacityPerThread=0, -Dio.netty.allocator.numDirectArenas=0, -Dlog4j.shutdownHookEnabled=false, -Dlog4j2.disable.jmx=true, -Dlog4j2.formatMsgNoLookups=true, -Djava.locale.providers=SPI,COMPAT, --add-opens=java.base/java.io=ALL-UNNAMED, -XX:+UseG1GC, -Djava.io.tmpdir=/tmp/elasticsearch-15245875470259601496, -XX:+HeapDumpOnOutOfMemoryError, -XX:+ExitOnOutOfMemoryError, -XX:HeapDumpPath=data, -XX:ErrorFile=logs/hs_err_pid%p.log, -Xlog:gc*,gc+age=trace,safepoint:file=logs/gc.log:utctime,pid,tags:filecount=32,filesize=64m, -Des.cgroups.hierarchy.override=/, -Xms512m, -Xmx512m, -XX:MaxDirectMemorySize=268435456, -XX:G1HeapRegionSize=4m, -XX:InitiatingHeapOccupancyPercent=30, -XX:G1ReservePercent=15, -Des.path.home=/usr/share/elasticsearch, -Des.path.conf=/usr/share/elasticsearch/config, -Des.distribution.flavor=default, -Des.distribution.type=docker, -Des.bundled_jdk=true]", "ecs.version": "1.2.0","service.name":"ES_ECS","event.dataset":"elasticsearch.server","process.thread.name":"main","log.logger":"org.elasticsearch.node.Node","elasticsearch.node.name":"es01","elasticsearch.cluster.name":"docker-cluster"}
es-cluster-es02-1    | {"@timestamp":"2022-03-10T17:41:13.002Z", "log.level": "INFO", "message":"version[8.1.0], pid[7], build[default/docker/3700f7679f7d95e36da0b43762189bab189bc53a/2022-03-03T14:20:00.690422633Z], OS[Linux/5.10.76-linuxkit/aarch64], JVM[Eclipse Adoptium/OpenJDK 64-Bit Server VM/17.0.2/17.0.2+8]", "ecs.version": "1.2.0","service.name":"ES_ECS","event.dataset":"elasticsearch.server","process.thread.name":"main","log.logger":"org.elasticsearch.node.Node","elasticsearch.node.name":"es02","elasticsearch.cluster.name":"docker-cluster"}
es-cluster-es02-1    | {"@timestamp":"2022-03-10T17:41:13.007Z", "log.level": "INFO", "message":"JVM home [/usr/share/elasticsearch/jdk], using bundled JDK [true]", "ecs.version": "1.2.0","service.name":"ES_ECS","event.dataset":"elasticsearch.server","process.thread.name":"main","log.logger":"org.elasticsearch.node.Node","elasticsearch.node.name":"es02","elasticsearch.cluster.name":"docker-cluster"}
es-cluster-es02-1    | {"@timestamp":"2022-03-10T17:41:13.007Z", "log.level": "INFO", "message":"JVM arguments [-Xshare:auto, -Des.networkaddress.cache.ttl=60, -Des.networkaddress.cache.negative.ttl=10, -Djava.security.manager=allow, -XX:+AlwaysPreTouch, -Xss1m, -Djava.awt.headless=true, -Dfile.encoding=UTF-8, -Djna.nosys=true, -XX:-OmitStackTraceInFastThrow, -XX:+ShowCodeDetailsInExceptionMessages, -Dio.netty.noUnsafe=true, -Dio.netty.noKeySetOptimization=true, -Dio.netty.recycler.maxCapacityPerThread=0, -Dio.netty.allocator.numDirectArenas=0, -Dlog4j.shutdownHookEnabled=false, -Dlog4j2.disable.jmx=true, -Dlog4j2.formatMsgNoLookups=true, -Djava.locale.providers=SPI,COMPAT, --add-opens=java.base/java.io=ALL-UNNAMED, -XX:+UseG1GC, -Djava.io.tmpdir=/tmp/elasticsearch-11308523959202993754, -XX:+HeapDumpOnOutOfMemoryError, -XX:+ExitOnOutOfMemoryError, -XX:HeapDumpPath=data, -XX:ErrorFile=logs/hs_err_pid%p.log, -Xlog:gc*,gc+age=trace,safepoint:file=logs/gc.log:utctime,pid,tags:filecount=32,filesize=64m, -Des.cgroups.hierarchy.override=/, -Xms512m, -Xmx512m, -XX:MaxDirectMemorySize=268435456, -XX:G1HeapRegionSize=4m, -XX:InitiatingHeapOccupancyPercent=30, -XX:G1ReservePercent=15, -Des.path.home=/usr/share/elasticsearch, -Des.path.conf=/usr/share/elasticsearch/config, -Des.distribution.flavor=default, -Des.distribution.type=docker, -Des.bundled_jdk=true]", "ecs.version": "1.2.0","service.name":"ES_ECS","event.dataset":"elasticsearch.server","process.thread.name":"main","log.logger":"org.elasticsearch.node.Node","elasticsearch.node.name":"es02","elasticsearch.cluster.name":"docker-cluster"}
es-cluster-es01-1    | {"@timestamp":"2022-03-10T17:41:14.578Z", "log.level": "INFO", "message":"loaded module [aggs-matrix-stats]", "ecs.version": "1.2.0","service.name":"ES_ECS","event.dataset":"elasticsearch.server","process.thread.name":"main","log.logger":"org.elasticsearch.plugins.PluginsService","elasticsearch.node.name":"es01","elasticsearch.cluster.name":"docker-cluster"}
es-cluster-es01-1    | {"@timestamp":"2022-03-10T17:41:14.578Z", "log.level": "INFO", "message":"loaded module [analysis-common]", "ecs.version": "1.2.0","service.name":"ES_ECS","event.dataset":"elasticsearch.server","process.thread.name":"main","log.logger":"org.elasticsearch.plugins.PluginsService","elasticsearch.node.name":"es01","elasticsearch.cluster.name":"docker-cluster"}
es-cluster-es01-1    | {"@timestamp":"2022-03-10T17:41:14.578Z", "log.level": "INFO", "message":"loaded module [constant-keyword]", "ecs.version": "1.2.0","service.name":"ES_ECS","event.dataset":"elasticsearch.server","process.thread.name":"main","log.logger":"org.elasticsearch.plugins.PluginsService","elasticsearch.node.name":"es01","elasticsearch.cluster.name":"docker-cluster"}
es-cluster-es01-1    | {"@timestamp":"2022-03-10T17:41:14.582Z", "log.level": "INFO", "message":"loaded module [data-streams]", "ecs.version": "1.2.0","service.name":"ES_ECS","event.dataset":"elasticsearch.server","process.thread.name":"main","log.logger":"org.elasticsearch.plugins.PluginsService","elasticsearch.node.name":"es01","elasticsearch.cluster.name":"docker-cluster"}
..........

**Comment by JohanPhom** [comment]
Same error, my config is:

Elasticsearch version: 7.17.1
Elastic-agent version: I tried  8.0.0 and 8.1.0

./elastic-agent install     --fleet-server-es=https://10.4.8.10:9200   --fleet-server-service-token=AAEAAWVsYXN0aWMvZmxlZXQtc2VydmVyL3Rva2VuLTE2NDY5ODU3NjY3ODM6c2dsSEpMR3RRanVfdVNNb2M3UXF0dw   --fleet-server-policy=499b5aa7-d214-5b5d-838b-3cd76469844e   --fleet-server-insecure-http --fleet-server-es-insecure

Elastic Agent will be installed at /opt/Elastic/Agent and will run as a service. Do you want to continue? [Y/n]:Y
{"log.level":"info","@timestamp":"2022-03-11T09:57:17.853+0100","log.origin":{"file.name":"cmd/enroll_cmd.go","file.line":778},"message":"Fleet Server - Starting","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2022-03-11T09:57:19.854+0100","log.origin":{"file.name":"cmd/enroll_cmd.go","file.line":778},"message":"Fleet Server - **Error - failed version compatibility check with elasticsearch: unsupported version","ecs.version":"1.6.0"**}
{"log.level":"info","@timestamp":"2022-03-11T09:57:31.863+0100","log.origin":{"file.name":"cmd/enroll_cmd.go","file.line":778},"message":"Fleet Server - Error - dial tcp 10.4.8.10:9200: connect: connection refused","ecs.version":"1.6.0"}
Error: fleet-server failed: context canceled

After that my service elasticsearch got killed

**Comment by kiran2sasi** [comment]
Error: fleet-server failed: context canceled
May I know the possible reasons to get this error

**Comment by gbeltramelli** [comment]
i´m facing this issue with elastic-agent 8.3.3, installing form tar and from yum in my centos 7.5 also tested using downloading rpm.

./elastic-agent install --url=https://xxxxxxt:8220 --enrollment-token=xxxxxxxxxxxxxxxx --tag=linux,test --insecure
Elastic Agent will be installed at /opt/Elastic/Agent and will run as a service. Do you want to continue? [Y/n]:y
{"log.level":"warn","@timestamp":"2022-08-10T19:32:50.679-0300","log.logger":"tls","log.origin":{"file.name":"tlscommon/tls_config.go","file.line":104},"message":"SSL/TLS verifications 
disabled.","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2022-08-10T19:32:50.930-0300","log.origin":{"file.name":"cmd/enroll_cmd.go","file.line":471},"message":"Starting enrollment to URL: https://xxxxxxxx:8220/","ecs.version":"1.6.0"}
{"log.level":"warn","@timestamp":"2022-08-10T19:32:51.228-0300","log.logger":"tls","log.origin":{"file.name":"tlscommon/tls_config.go","file.line":104},"message":"SSL/TLS verifications 
disabled.","ecs.version":"1.6.0"}
Error: fail to enroll: fail to execute request to fleet-server: status code: 400, fleet-server returned an error: UnsupportedVersion, message: version is not supported

**Comment by michel-laterman** [comment]
Looks like the discuss issue was resolved
