### ISSUE TITLE
Fleet-server error

### ISSUE THREAD

**Issue by ghost** [elastic/fleet-server#1253]
Iam trying to get apache logs using kibana!!

1. Installed fleet-server in one VM
2. Configured agent policy
3. when i try to run this command according to the document 

**sudo elastic-agent enroll --insecure --url=http://ip-address:8220 of fleet-server --enrollment-token=bac52714-fadb-415a-83ba-da05c839b834**

iam getting below error :

{"log.level":"info","@timestamp":"2022-03-23T07:52:08.099Z","log.origin":{"file.name":"cmd/enroll_cmd.go","file.line":473},"message":"Retrying enrollment to URL: http://ipaddress:8220/","ecs.version":"1.6.0"}
{"log.level":"warn","@timestamp":"2022-03-23T07:54:15.395Z","log.origin":{"file.name":"cmd/enroll_cmd.go","file.line":466},"message":"Remote server is not ready to accept connections, will retry in a moment.","ecs.version":"1.6.0"}

**Comment by ph** [comment]
@Karewisetech2021 a few question heres:

- What is the health status of the Elastic Agent that run Fleet server?
- Is there anything in between the agent you try enroll and the instance that run fleet server? A proxy?
- Is there any error logs on Fleet server?

**Comment by Karewisetech2021** [comment]
1. it shows Healthy
2. No
2. No

**Comment by Karewisetech2021** [comment]
curl --insecure https://fleep-ip:8220/api/status - when i use https iam getting error
curl: (35) SSL received a record that exceeded the maximum permissible length.

curl --insecure http://fleet-ip:8220/api/status
{"name":"fleet-server","status":"HEALTHY"}

**Comment by michel-laterman** [comment]
Is this still an issue?
It looks like an SSL issue between the agent and fleet-server

**Comment by nyukers** [comment]
Excuse me, but I can't understand where is good reason for "insecure" with "https" values in **enroll** statement.

**Comment by nyukers** [comment]
Fleet hosts is https://192.168.1.11:8220
Elasticsearch hosts is http://192.168.1.11:9200

**Try to run:**
sudo ./elastic-agent enroll  --url=https://192.168.1.11:8220 --enrollment-token=UHlWRlc0UUJyOXZ1blFVTzB1ZFM6cWRSTlpvUnpRMUNlVkxZVWI0VThGUQ== --insecure

**Output:**
2022-11-09T14:35:16.435+0200    WARN    cmd/enroll_cmd.go:453   Remote server is not ready to accept connections, will retry in a moment.
2022-11-09T14:36:16.438+0200    INFO    cmd/enroll_cmd.go:460   Retrying enrollment to URL: https://192.168.1.11:8220/
2022-11-09T14:36:16.541+0200    WARN    cmd/enroll_cmd.go:453   Remote server is not ready to accept connections, will retry in a moment.
2022-11-09T14:38:16.545+0200    INFO    cmd/enroll_cmd.go:460   Retrying enrollment to URL: https://192.168.1.11:8220/
2022-11-09T14:38:16.647+0200    WARN    cmd/enroll_cmd.go:453   Remote server is not ready to accept connections, will retry in a moment.
and so on.

**Comment by nyukers** [comment]
It's interesting - where is my Fleet server must be if I have Kibana host and Elasticsearch host **separately**?

**Comment by musabdogan** [comment]
I have the same issue how did you fixed it ?
@nyukers

**Comment by nyukers** [comment]
> I have the same issue how did you fixed it ? @nyukers

I don't remember now about solution, maybe it didn't fix for me.

**Comment by michel-laterman** [comment]
Is fleet-server running with certificates (`https`)?

Looking back at some comments it seems as though the self managed fleet-server instance was running on an `http` listener and the other agent is trying to connect with `https`.

In the example above `--url=https://192.168.1.11:8220/` designates the fleet-server instance.
If it's running as an `http` server use `--url=http://192.168.1.11:8220/`

**Comment by jlind23** [comment]
Closing this one as outdated/not prioritised, we will reopen it later if required.
cc @ycombinator
