### ISSUE TITLE
Logging is awkward during bootstrapping

### ISSUE THREAD

**Issue by lykkin** [elastic/fleet-server#1278]
Currently the way logging is handled during bootstrapping (i.e. before configuration has been resolved) is a bit haphazard.

It would be better to instantiate a bootstrapping logger with some default verbosity to pass around, then instantiate a new logger with the resolved configuration when possible.

Ideally, this code base should use the same logging library/conventions as the agent code base.

**Comment by ph** [comment]
@lykkin Do you think if we were moving from a Logger that write to disk to a logger that writes to stdout and collected by agent. This would result in only ahve the log level (and selector in the future) being a changing configuration?
