### ISSUE TITLE
[BUG] Elasticsearch API key is not included in Endpoint config updates for 8.2.0 BC1

### ISSUE THREAD

**Issue by ferullo** [elastic/fleet-server#1293]
In 8.2.0 BC1 the first config Endpoint receives on install includes an API key for Elasticsearch, so everything works. However, after a policy change for Endpoint the config no longer contains an API key. This means Endpoint cannot write to Elasticsearch.

Steps to reproduce:
1. Install Agent 8.2.0 BC1 (I used x86_64 Linux)
2. Add Endpoint Security integration
3. Wait for Endpoint to be installed
4. `/opt/Elastic/Endpoint/state/log/endpoint-000000.log` should include lines like `Sent 2 documents to Elasticsearch` being printed every 30 seconds or so (create system activity like starting a few processes to make sure Endpoint has data to write to Elasticsearch)
5. Save Endpoint's config for later comparison (`sudo cp /opt/Elastic/Endpoint/elastic-endpoint.yaml /tmp/elastic-endpoint.yaml.1`)
6. Make any change to Endpoint's policy in the Security App
7. Wait for Endpoint's config to be updated
8. Now `/opt/Elastic/Endpoint/state/log/endpoint-000000.log` will keep appending with a log containing `HTTP Status Code (401)` and a JSON response from Elasticsearch.
9. Save Endpoint's config for later comparison (`sudo cp /opt/Elastic/Endpoint/elastic-endpoint.yaml /tmp/elastic-endpoint.yaml.2`)

If you diff the two configs you'll see the Elasticsearch API keys is now missing. Example below.

```
vagrant@vagrant:/tmp$ sudo diff elastic-endpoint.yaml.1 elastic-endpoint.yaml.2 
215c215
<         enabled: false
---
>         enabled: true
251c251
<   revision: 4
---
>   revision: 5
256d255
<     api_key: HIDDEN_FOR_GITHUB:HIDDEN_FOR_GITHUB
259c258
< revision: 5
---
> revision: 6
vagrant@vagrant:/tmp$

**Comment by kevinlog** [comment]
Here's another bug this is a symptom of this: https://github.com/elastic/kibana/issues/129281

**Comment by ph** [comment]
Going to close this in favor of https://github.com/elastic/elastic-agent/issues/285
