### ISSUE TITLE
Investigate impact of LS output addition with the number of allocation

### ISSUE THREAD

**Issue by ph** [elastic/fleet-server#1301]
We had allocation optimization in place when adding the api key to the output block, We the changes we might removed all the optimization.

**Comment by lykkin** [comment]
As an addition to this: we should have benchmarks around the scenarios we optimize for to catch regressions.

**Comment by jlind23** [comment]
Closing this one as outdated/not prioritised, we will reopen it later if required.
cc @ycombinator
