### ISSUE TITLE
Automate updating our dependencies on beats

### ISSUE THREAD

**Issue by ph** [elastic/fleet-server#1338]
Updating our dependencies on beats is a manual tasks, this can lead to our code to diverge in feature from beats. 
We should automatically update our dependencies.

@v1v I belive there is something in place for other repositories, is this a big task to add this to this repository.

**Comment by v1v** [comment]
I'll ping you in one of our internal issues that discussed this deeply, IIRC

**Comment by jlind23** [comment]
Closing this one as outdated/not prioritised, we will reopen it later if required.
cc @ycombinator
