### ISSUE TITLE
Manage fleet server indices as system indices in the Elastic Stack

### ISSUE THREAD

**Issue by scunningham** [elastic/fleet-server#135]
**Describe the enhancement:**

Fleet Server relies on a set of indices to store operational data about Fleet.   These indices must be created early in the system lifecycle.  Currently the indices are instantiated in Kibana.  This enhancement will move the instantiation to the Elastic Stack where the fleet indices will be treated as managed system indices.  Moving forward, updates and migrations of these indices will be managed by the system indices plugins.

**Describe a specific use case for the enhancement or feature:**

We 7 indices we are dependent on, and one data stream with an ILM policy:

### Indices

[.fleet-actions](https://github.com/elastic/kibana/blob/master/x-pack/plugins/fleet/server/services/fleet_server/elasticsearch/fleet_actions.json)
[.fleet-agents](https://github.com/elastic/kibana/blob/master/x-pack/plugins/fleet/server/services/fleet_server/elasticsearch/fleet_agents.json)
[.fleet-enrollment-api-keys](https://github.com/elastic/kibana/blob/master/x-pack/plugins/fleet/server/services/fleet_server/elasticsearch/fleet_enrollment_api_keys.json)
[.fleet-policies](https://github.com/elastic/kibana/blob/master/x-pack/plugins/fleet/server/services/fleet_server/elasticsearch/fleet_policies.json)
[.fleet-policies-leader](https://github.com/elastic/kibana/blob/master/x-pack/plugins/fleet/server/services/fleet_server/elasticsearch/fleet_policies_leader.json)
[.fleet-servers](https://github.com/elastic/kibana/blob/master/x-pack/plugins/fleet/server/services/fleet_server/elasticsearch/fleet_servers.json)
[.fleet-artifacts](https://github.com/elastic/kibana/blob/master/x-pack/plugins/fleet/server/services/fleet_server/elasticsearch/fleet_artifacts.json)

### DataStream

[.fleet-actions-results](https://github.com/elastic/integrations/blob/master/packages/fleet_server/elasticsearch/index_template/.fleet-actions-results.json) and [ILM policy](https://github.com/elastic/integrations/blob/master/packages/fleet_server/elasticsearch/ilm_policy/.fleet-actions-results.json) for the data stream.

Note: The indices creation had moved over to Kibana, however the data stream was still being created via package management.  That was an oversight.

### Known issues
- The indices/datastreams are not instantiated in the system indices plugin until the first document is written to them.  The code in Kibana does not currently expect that.  Is there a way to "touch" each of the indices at Kibana boot so we don't have to fix the reads of indices in Kibana to handle the "does not yet exist" case?
- System Indices does not yet support the concept of a system managed ILM policy.  So the [ILM policy](https://github.com/elastic/integrations/blob/master/packages/fleet_server/elasticsearch/ilm_policy/.fleet-actions-results.json) for .fleet-action-results will likely remain in the package, or have to put into Kibana.  Question on race condition: what happens if the package is installed before the data stream is instantiated?  Does trying to add an ILM policy to a system managed data stream cause it to be created?

@jaymode will do the initial implementation in the Elastic Stack for this integration.  Moving forward, the Fleet Team will pick up maintenance.  This is expected to land for 7.13.

**Comment by jaymode** [comment]
I've opened https://github.com/elastic/elasticsearch/pull/70689 for the indices and will follow-up on the data stream.

**Comment by ruflin** [comment]
Here is the related PR for data streams: https://github.com/elastic/elasticsearch/pull/71667

**Comment by ruflin** [comment]
@scunningham @jaymode Going to close this as I think all changes landed. Can you confirm?

**Comment by scunningham** [comment]
Landed.
