### ISSUE TITLE
Add system tests

### ISSUE THREAD

**Issue by ruflin** [elastic/fleet-server#137]
As part of the fleet-server CI some of the test should be run against Elasticsearch. apm-server today already has a go based framework to do this for apm-server: https://github.com/elastic/apm-server/tree/master/systemtest We could reuse (copy) parts of it and use it for the fleet-server to test some of the parts.

**Comment by ruflin** [comment]
There are already some tests in fleet-server running against Elasticsearch and part of CI: https://github.com/elastic/fleet-server/blob/master/internal/pkg/monitor/subscription_monitor_integration_test.go

**Comment by michel-laterman** [comment]
integration tests covered a real elasticsearch instance, e2e tests for all endpoints have been added with https://github.com/elastic/fleet-server/pull/2645
