### ISSUE TITLE
Evaluate replacing internal/pkg/danger with bytes.Buffer

### ISSUE THREAD

**Issue by michel-laterman** [elastic/fleet-server#1431]
**Describe the enhancement:**

We have rolled our own buffer in the form of `pkg/danger`. It will not return errors.
A more complete buffer is provided by the standard library with `bytes.Buffer`, we may want to use that implementation instead

Note that because we know the `danger` buffer does not return errors, we don't check for them where ever the buffer is used, that may need to change if we switched buffers

**Comment by scunningham** [comment]
Replacement can work; however this was specifically added as an optimization to limit byte copies in a performance sensitive part of the code.   If removed, we should validate that the performance does not regress excessively.

**Comment by jlind23** [comment]
Closing this as outdated/not relevant, will reopen later if required.
cc @ycombinator
