### ISSUE TITLE
[Meta] Run select inputs on dedicated hosts

### ISSUE THREAD

**Issue by mostlyjason** [elastic/fleet-server#144]
Some Fleet operators would like to ensure consistent performance for integrations running on hosted Elastic Agents. This is particularly important for Synthetics because a change in the underlying host resources may create noise that could impact the accuracy of website performance measurement.  It is also important for APM server where operators want to ensure the performance for loading real time APM and Otel data. Some integrations like Fleet server and AWS will have spikey workloads so it makes sense to segregate them. 

User stories:
- As a Fleet operator, I want to specify that some types of inputs are only allowed to run on dedicated hosts
- As a Fleet operator, I want Fleet to automatically assign inputs so that I don't need to manually update agent policies when they undergo maintenance or I add/remove nodes.

Open questions:

- How important is it to specify a number of hosts > 1?
- How important is to run a set of inputs on a dedicated host vs a single input?

**Comment by michel-laterman** [comment]
coordinator is being removed see https://github.com/elastic/fleet-server/pull/3131
