### ISSUE TITLE
GitHub branch protection with CODEOWNERS and Mergify does not allow to auto-merge

### ISSUE THREAD

**Issue by v1v** [elastic/fleet-server#1472]
I've just found that Mergify cannot auto-merge PRs with the existing branch protection.

CODEOWNERS does not support GitHub apps https://github.community/t/is-it-possible-to-add-github-apps-bot-to-codeowners/3146/3

As a consequence, PRs are pilled up and need a manual approval from the owners to allow Mergify to auto-merge.

There are two actions:

1) I'd propose to ignore `dev-tools/integration/.env` from the existing CODEOWNERS so Mergify can move forward.

2) Unfortunately, the existing proposal to [automerge backported PRs](https://github.com/elastic/fleet-server/pull/168) from Mergify is not supported. Relax the policy of CODEOWNERS on release branches?

**Comment by v1v** [comment]
> I'd propose to ignore dev-tools/integration/.env from the existing CODEOWNERS so Mergify can move forward.

It's now solved, and tested with https://github.com/elastic/fleet-server/pull/1474

**Comment by v1v** [comment]
> 2. Unfortunately, the existing proposal to https://github.com/elastic/fleet-server/pull/168 from Mergify is not supported. Relax the policy of CODEOWNERS on release branches?

@ph @jlind23 , what are your thoughts? https://github.com/elastic/fleet-server/pull/168 doesn't work anymore with the existing branch policy and GitHub codeowners in the release branches.

**Comment by jlind23** [comment]
@v1v can not we just ignore this specific path?

**Comment by v1v** [comment]
> @v1v can not we just ignore this specific path?

That's done in https://github.com/elastic/fleet-server/pull/1473

But automated backports are not anymore merged since the OWNERSHIP branch protection does not allow to do so, those backports are not about the automated bumps but all the backports done from `main` to the different release branches. As long as there is a GitHub OWNERSHIP, the auto-merge with Mergify won't work. 

https://github.com/elastic/fleet-server/pull/168 was the original request to automate the merge for backports

**Comment by ph** [comment]
Would adding the bot account to the codeowner actually fixes this?

**Comment by v1v** [comment]
> Would adding the bot account to the codeowner actually fixes this?

The bot account is an APP ,  and CODEOWNERS does not support GitHub apps https://github.community/t/is-it-possible-to-add-github-apps-bot-to-codeowners/3146/3

**Comment by jlind23** [comment]
Closing this one as outdated/not prioritised, we will reopen it later if required.
cc @ycombinator
