### ISSUE TITLE
Fleet Data Streams sort by size incorrect

### ISSUE THREAD

**Issue by zez3** [elastic/fleet-server#1488]
Can someone please have a look at that numeric sort function, it looks like it needs an extra touch.

![image](https://user-images.githubusercontent.com/22619253/169618904-0e5333ab-1130-454f-a2c4-8970c8a62b70.png)

Thanks

**Comment by gemaliano** [comment]
https://github.com/elastic/kibana/issues/132825

**Comment by ph** [comment]
I will close this since there is a kibana issue linked above.
