### ISSUE TITLE
[Self-Managed]: Fleet Server failed to upgrade from 8.2>8.3 on self-managed 8.3 Kibana

### ISSUE THREAD

**Issue by amolnater-qasource** [elastic/fleet-server#1564]
**Kibana version:**  8.3 Snapshot Kibana self-managed environment

**Host OS and Browser version:** Windows, All

**Build details:**
```
VERSION: 8.3.0 Snapshot self-managed
BUILD: 53295
COMMIT: 6ef457053adce432a3b4d5b016997f92488d857d
```

**Preconditions:**
1. 8.3 Snapshot Kibana self-managed environment should be available.
2. Lower version 8.2.0 fleet server should be installed.

**Steps to reproduce:**
1. Navigate to Fleet>Agents tab.
2. Click upgrade lower version fleet server.
3. Observe after 2-3 minutes fleet server failed to upgrade to latest version.

**Expected Result:**
Fleet Server should upgrade to latest version on self-managed 8.3 Kibana

**Logs:**
[elastic-agent-diagnostics-2022-06-16T11-01-48Z-00.zip](https://github.com/elastic/fleet-server/files/8918286/elastic-agent-diagnostics-2022-06-16T11-01-48Z-00.zip)

**Screenshot:**
![19](https://user-images.githubusercontent.com/77374876/174057226-db6319d7-3eff-4ce2-85ce-de36ac39402e.JPG)

**Related Issue:**
Elastic-Agents also failed to upgrade on cloud builds.
Issue reported at: https://github.com/elastic/elastic-agent/issues/526

**Comment by manishgupta-qasource** [comment]
Secondary review for this ticket is Done

**Comment by amolnater-qasource** [comment]
Hi @jlind23 
We have revalidated this issue on 8.3 Snapshot self-managed environment and found it **fixed** now.
- 8.2.0 Fleet Server upgraded to latest version on self-managed 8.3 Snapshot Kibana.

**Screenshots:**
![3](https://user-images.githubusercontent.com/77374876/176137417-a5e27c02-e5f0-45ce-95cc-8a5c17e80acb.JPG)
![4](https://user-images.githubusercontent.com/77374876/176137425-f471cf0d-7a90-4984-b3c3-1da991d7e1f6.JPG)

**Build details:**
VERSION: 8.3.0
BUILD: 53530
COMMIT: 5c1a4d546377d12937afa10ed286adda23d60623
8.2 agent Artifact: https://artifacts.elastic.co/downloads/beats/elastic-agent/elastic-agent-8.2.0-windows-x86_64.zip

Hence we are closing this and marking as **QA:Validated**.
Thanks
