### ISSUE TITLE
[Deployment]: Hosted fleet server gets unhealthy on 8.4 Snapshot.

### ISSUE THREAD

**Issue by amolnater-qasource** [elastic/fleet-server#1574]
**Deployment Links:**
- https://staging.found.no/
- https://console.qa.cld.elstc.co/

**Description:**
Hosted fleet server gets unhealthy on 8.4 Snapshot and we have observed APM disabled under Deployment page.

**Screenshots:**
![17](https://user-images.githubusercontent.com/77374876/174783262-905683c3-996f-4558-9bd0-f966eb990efe.JPG)
![18](https://user-images.githubusercontent.com/77374876/174783484-145e757e-b676-4d98-b714-a49905dd7d39.JPG)
![19](https://user-images.githubusercontent.com/77374876/174784267-759c37fb-7a23-44d1-95fa-511246fddcdc.JPG)
![20](https://user-images.githubusercontent.com/77374876/174784259-8f14d7f7-2fe9-40eb-b1e1-71803ef78be4.JPG)

**Comment by amolnater-qasource** [comment]
FYI @jlind23 @joshdover

**Comment by manishgupta-qasource** [comment]
Secondary review for this ticket is Done

**Comment by jlind23** [comment]
@amolnater-qasource Don't we need APM integration to enable this? Do you have access to fleet-server logs?

**Comment by amolnater-qasource** [comment]
Hi @jlind23 
Thanks for looking into this.
APM integration is already added in the Hosted fleet server.

**Screenshot:**
![image](https://user-images.githubusercontent.com/77374876/174814667-890d0353-c930-42dc-a3e3-756cc1029d61.png)

As we are testing on a cloud build we are not sure how to get hosted fleet-server logs.
Further no logs are available under Logs tab for hosted agent, as logs collection is disabled for managed policy.

![image](https://user-images.githubusercontent.com/77374876/174814925-e3056f62-52d5-4781-b354-4b404eef1ee9.png)

Could you please share any steps for this?

Thanks

**Comment by jlind23** [comment]
As stated yesterday by @cmacknz no 8.4 snapshots were built for more than 15 days. Could you please try again with a fresh snapshot?

**Comment by amolnater-qasource** [comment]
Hi @jlind23 
We have attempted to re-setup latest 8.4 Snapshot Kibana cloud environment and found this issue **still reproducible.**
- Hosted fleet server gets unhealthy on 8.4 Snapshot.

**Deployment Links:**
- https://staging.found.no/
- https://console.qa.cld.elstc.co/

**Build details:**
VERSION: 8.4.0
BUILD: 53825
**COMMIT: e0446dac822f55f75c1d97b6d9c3f4647c445973
(June 21, 2022 04:04 PM GMT 5:30+**)

We have re-validated this issue on build with above commits.
Please let us know if anything else is required from our end.
Thanks

**Comment by juliaElastic** [comment]
have you tried checking the logs in https://admin.found.no ? it should work for staging instances, more info here: https://docs.google.com/presentation/d/1lIEQsQGgUR0H3MRhMqyZFP3wdofmZmiqmhYX--xT6FE/edit#slide=id.g12bd3a98d22_1_0

**Comment by jlind23** [comment]
Thanks @juliaElastic.
@amolnater-qasource I created a new deployment and did not succeed reproducing it.
As soon as you try again, could you please share your deployment ID in order to take a look at the logs?

**Comment by jlind23** [comment]
@elastic/apm-server on this particular deployment I see a lot of apm error like:
`precondition failed: dial tcp [::1]:9200: connect: cannot assign requested address`

Does it ring a bell on your end?

**Comment by axw** [comment]
@jlind23 that error message means APM Server is trying to connect to Elasticsearch on localhost, which is obviously not going to work. This implies that Elastic Agent is not sending the Elasticsearch output config to APM Server, or otherwise there's a bug in APM Server related to handling the config.

We also have an issue open to investigate 8.4 failing here: https://github.com/elastic/apm-server/issues/8426

**Comment by amolnater-qasource** [comment]
Hi @jlind23 
Thanks for the update.

We have attempted to restart the integration server and we have got a Healthy Hosted Fleet server once under Agents tab.
However, this hosted fleet server again gets Unhealthy again in sometime.
![1](https://user-images.githubusercontent.com/77374876/175224036-0124bfea-42b6-4b0d-8d86-85d80ab48a6d.JPG)
![3](https://user-images.githubusercontent.com/77374876/175224629-50f75f3b-55d1-465c-8555-9ef0624894f4.JPG)

Further the APM is still disabled under the deployment page.
![2](https://user-images.githubusercontent.com/77374876/175224133-61696e88-7c6d-478d-bcfe-bea4b52c9d6e.JPG)

Deployment id for this build is: `159a7d04412248a9a5ad9d9bd9a0e365`

Thanks

**Comment by jlind23** [comment]
Hi @amolnater-qasource , thanks for the deployment id.
Indeed I do observe the same connection problem coming from apm-server.
@amolnater-qasource can you also check the policy content to check what is the ES output value?

@pierrehilbert @ph can we quickly have someone from the control plane team looking at it?

**Comment by amolnater-qasource** [comment]
Hi @jlind23 
> you also check the policy content to check what is the ES output value?

Host value for ES is: `http://fa60f7f1004648e78c8d6b853e89569a.containerhost:9244`

Further for detailed information please find below attached `Elastic Cloud agent policy`:
[elastic-agent.zip](https://github.com/elastic/fleet-server/files/8974186/elastic-agent.zip)

Please let us know if anything else is required from our end.
Thanks

**Comment by michel-laterman** [comment]
One thing i've noted from the policy posted in https://github.com/elastic/fleet-server/issues/1574#issuecomment-1165325115 that the fleet-server input has
```yaml
    server:
      port: 8220
      host: 0.0.0.0
```

and the APM server input also has
```yaml
      host: '0.0.0.0:8200'
```
I don't think this would effect the ES output, but it may be another issue

**Comment by axw** [comment]
I'm pretty sure this is related to some recent APM Server build changes I made, which inadvertently have us building without the Fleet management code. I'll merge a fix ASAP.

**Comment by amolnater-qasource** [comment]
Hi @jlind23 
We have revalidated setting up 8.4 Snapshot kibana cloud-staging environment and found it **fixed** now.
- Hosted fleet server remains Healthy on 8.4 Snapshot.
- APM is enabled under Deployment settings

**Screenshots:**
![1](https://user-images.githubusercontent.com/77374876/176137060-5d8f5b27-5d94-4820-aeba-b4beeefe1455.JPG)
![2](https://user-images.githubusercontent.com/77374876/176137076-6ab425f8-54c0-4bf6-b774-c36fa81fdfe1.JPG)

**Build details:**
8.4 Snapshot
BUILD: 53965
COMMIT: 7c8b8f8cf32d752fd405ddf680175299fbd8cd32

Hence marking this as **QA:Validated**.
Thanks
