### ISSUE TITLE
failed on waiting for global checkpoints advance

### ISSUE THREAD

**Issue by ph** [elastic/fleet-server#1575]
Looking at a fleet server debug log on cloud I could see a lot of `failed on waiting for global checkpoints advance` errors messages, looking at the JSON payload I see the actual go error.

```json
   "message": [
      "failed on waiting for global checkpoints advance"
    ],
....
    "error.message": [
      "elastic fail 403:security_exception:current license is non-compliant for [security]"
    ],
```

This is a message returned directly from Elasticsearch and I don't think we can recover from returning a 403 in ES, so I am not sure what has changed, I know we are using some features of Elasticsearch that aren't available in basic maybe the permissions changed on theses API calls?

Looking at the license of the ES cluster on cloud, If I remember correctly this should give me the right permissions.

```json
{
  "license": {
    "status": "active",
    "uid": "78b6de3d-1f31-4062-be91-b421d3d20cf0",
    "type": "trial",
    "issue_date": "2022-06-20T14:05:50.506Z",
    "issue_date_in_millis": 1655733950506,
    "expiry_date": "2022-07-20T14:05:50.506Z",
    "expiry_date_in_millis": 1658325950506,
    "max_nodes": 1000,
    "max_resource_units": null,
    "issued_to": "e4548c81f2cd4df598e3dc1a9ab19e09",
    "issuer": "elasticsearch",
    "start_date_in_millis": -1
  }
}
```

I can give access to the cluster/logs if needed.

**Comment by joshdover** [comment]
This looks like an exception from Elasticsearch: https://github.com/elastic/elasticsearch/blob/e6c0ca3e0901cd014a0fe1941bda6cbea70bd409/x-pack/plugin/core/src/main/java/org/elasticsearch/license/LicenseUtils.java#L27-L31

**Comment by juliaElastic** [comment]
this error come up in an sdh recently where the customer had multiple shards in fleet index: https://github.com/elastic/sdh-elasticsearch/issues/6199#issuecomment-1157339976

**Comment by aleksmaus** [comment]
@ph do you still have access to that instance? How often did this happen? Did it resolve? Can I get access to that deployment?

**Comment by gwbrown** [comment]
The Elasticsearch cluster logs would be very useful in figuring out what's up here.
