### ISSUE TITLE
Optimize Key invalidation by aggregating ids.

### ISSUE THREAD

**Issue by ph** [elastic/fleet-server#1608]
The _invalidate API key endpoint_ support passing multiple API Key ids and will invalidate all of them.
Looking at the fleet-server we do leverage this feature for on a small operation, only pass an agent current api key or old api keys, if we have multiple api key to invalidate we would still do one request per agent context.

It should be possible to aggregate the IDS of the api key and do a single request, we don't need to do the request as part of an agent. This would _probably_ help for the following scenario:

- Mass unenroll
- Force unenroll
- Agent Policy change after that policy was ack.

Note, I've said probably and I do have clear data to back that up.

**Comment by ph** [comment]
@joshdover and @nimarezainia we could possibly add this to the scaling effort.

**Comment by jlind23** [comment]
Per discussed with @joshdover as we will update the api key document instead of invalidating it, this is not relevant anymore.
May still be relevant if we unenroll thousands of agents at the same time.

**Comment by jlind23** [comment]
Closing this one as outdated/not prioritised, we will reopen it later if required.
cc @ycombinator
