### ISSUE TITLE
[Feature Request] Host upgrade files directly on the fleet server

### ISSUE THREAD

**Issue by aarju** [elastic/fleet-server#1622]
**Describe the enhancement:**
The Fleet server should have the option to push the upgrade binaries directly to the Elastic Agents when performing an upgrade. This would enable upgrading of agents that cannot access the artifacts server or are on a metered network. On large deployments this would let the users download once and then deploy to thousands of hosts. 

**Describe a specific use case for the enhancement or feature:**
We plan on deploying Elastic Agent with Fleet to the hosts in Elastic Cloud. We currently have 500,000 hosts in elastic cloud. If we tried to use fleet to upgrade those 500,000 hosts each one would download the upgrade binaries from the artifacts server resulting in over 190Tb of data being transferred into Elastic Cloud as well as 190Tb of files being downloaded from the artifacts server. This would have performance impacts as well as resulting in a very large bill from our cloud providors.

The other use case for this are the large 'airgapped' networks where the agents can not communicate directly with the internet. In this case the upgrade files can be provided directly from the Fleet Server.

**Comment by ph** [comment]
cc @nimarezainia

**Comment by nimarezainia** [comment]
We will be addressing this use case by allowing the user to configure a local server to download from. If in the future (based on user demand) we see a need to pursue a download from Fleet Server  we will consider it. For now closing this request.

**Comment by defensivedepth** [comment]
@nimarezainia Where can we track the progress for: `configure a local server to download from.`

This is a key piece of functionality, especially since the binary upgrades are so large
