### ISSUE TITLE
Fleet Server should not deliver cancelled actions

### ISSUE THREAD

**Issue by joshdover** [elastic/fleet-server#1625]
If a scheduled action has been cancelled, Fleet Server should not deliver the original action or the cancel action to an agent if the cancel has been received by Fleet Server before the agent received the original action. This has the benefits of:
- Ensuring that an action that has been cancelled does not get started by an agent at all
- Reducing unnecessary ack requests for actions that aren't going to be run anyways, important at high scales (which is also the main use case for scheduled actions)

We probably should still create an action response document for these actions so they're understood to have been delivered & resolved.

See discussion here for more context: https://github.com/elastic/horde/pull/54#discussion_r910912694

**Comment by ph** [comment]
@joshdover Horde is a private project.

**Comment by joshdover** [comment]
Closing this for now. Agent correctly drops cancelled actions without acking them so this isn't a high priority problem right now.
