### ISSUE TITLE
Log all of fleet server configuration at startup

### ISSUE THREAD

**Issue by ph** [elastic/fleet-server#1626]
When debugging an issue in cloud it is useful to know with what options the fleet-server is operating at, because some options are derived from the current container size and other can be change with the fleet-server integration.

I would be good to log a single even that we can search through the log that would container the information defined in https://github.com/elastic/fleet-server/blob/3c8cd17c1370abb07f6935021d31c8204e4d16a3/internal/pkg/config/input.go

**Comment by ph** [comment]
@michalpristas @joshdover as discussed.

**Comment by joshdover** [comment]
These logs need to be sure to sanitize the configuration to avoid logging any sensitive fields like certificate private keys

**Comment by michel-laterman** [comment]
It looks like there is some existing redacting/logging of fleet-server's config (from https://github.com/elastic/fleet-server/pull/692 and https://github.com/elastic/fleet-server/pull/620). I can use the same functions in order to ensure that config is also displayed on load.

**Comment by michel-laterman** [comment]
I have a PR that needs testing, i'll push it as a draft

**Comment by jlind23** [comment]
@michel-laterman thanks, would you mind linking it to this issue to keep track?
