### ISSUE TITLE
Fleet server apm integration - namespace change not working 

### ISSUE THREAD

**Issue by SanjuTechie87** [elastic/fleet-server#1628]
Hi , 

I have deployed the elastic stack using ECK operator in a private kubernetes cluster. I am facing the below challenges while trying to change the namespace of the apm integration for which I require some help

-  I am trying to change the namespace from default to production 

![elastic1](https://user-images.githubusercontent.com/52619259/176924924-07859ab4-8eb0-4b0f-869a-43438c168774.JPG)

- But in apm-server logs and also in index management->data streams I observed it is trying to write the apm data in default index 

![image](https://user-images.githubusercontent.com/52619259/176925636-f8c2788e-8e50-4291-a3ab-946c8d2a4498.png)

-  When I again changed the namespace to default it is working properly

FYI, I am using the below version
ECK 2.2.0
Elastic stack docker image version :  8.2.3

I wanted to do this to separate the indexes based on namespaces which is kind of project requirement therefore  any quick help in this regard is much appreciated

**Comment by jlind23** [comment]
Closing this one as outdated/not prioritised, we will reopen it later if required.
Be aware that if reopening is required then we should most probably do it in the integrations repository.
cc @ycombinator
