### ISSUE TITLE
[Fleet]: Agents stuck in Updating state on triggering 10k agents `Unenroll` from Bulk actions. 

### ISSUE THREAD

**Issue by amolnater-qasource** [elastic/fleet-server#1639]
**Kibana version:**  8.4 Snapshot Kibana cloud environment

**Host OS and Browser version:** All, All

**Build details:**
```
VERSION: 8.4.0 Snapshot
BUILD: 54194
COMMIT: f94d5ff26bf1f14f9992e426d9a56ac6c5d48fb0
```

**Preconditions:**
1. 8.4 Snapshot Kibana cloud environment should be available.
2. 10k agents should be installed.

**Steps to reproduce:**
1. Navigate to Fleet>Agents tab.
2. Select 10k agents and trigger Unenroll from bulk actions.
3. Observe Agents start unenrolling.
4. Observe after approximately 2400-2500 agents stops unenrolling and all remaining agents stuck in `Updating` state.

**Expected Result:**
 Agents should not get stuck in Updating state on triggering 10k agents `Unenroll` from Bulk actions. 

**Screenshots:**
![7](https://user-images.githubusercontent.com/77374876/177529763-fd698a20-9792-44eb-a1f9-fa63de89b434.JPG)

**Horde Logs:**
[Horde Logs.txt](https://github.com/elastic/fleet-server/files/9053970/Horde.Logs.txt)

**Logs from Logs tab:**
[Logs- Logs tab.txt](https://github.com/elastic/fleet-server/files/9053976/Logs-.Logs.tab.txt)
(No Fleet Server logs are available under Logs tab even after enabling Collect Logs and metrics from edit deployment page.)

**Comment by amolnater-qasource** [comment]
FYI @joshdover

**Comment by manishgupta-qasource** [comment]
Secondary review for this ticket is Done

**Comment by joshdover** [comment]
This is likely related to https://github.com/elastic/fleet-server/issues/1548 which may only be a problem with Horde. Let's retest this once those issues are resolved.

**Comment by amolnater-qasource** [comment]
Hi @joshdover 
We have revalidated this issue on latest 8.4 BC1 Kibana cloud environment and found it **still reproducible**.

**Observations:**
- Agents stuck in Updating state on triggering 10k agents Unenroll from Bulk actions.

**Build details:**
BUILD: 54999
COMMIT: 58f7eaf0f8dc3c43cbfcd393e587f155e97b3d0d

**Screen Recording:**

https://user-images.githubusercontent.com/77374876/182362328-b3f833a2-b379-4cf1-aeb6-c23b30505cfd.mp4


![9](https://user-images.githubusercontent.com/77374876/182362259-f9f9b4c7-3c64-461f-b396-214210f38290.JPG)

Please let us know if anything else is required from our end.
Thanks

**Comment by joshdover** [comment]
@amolnater-qasource Could you test using a Integrations Server with 4gb memory and the "Max agents" setting in the Fleet Server policy set to 10000?

**Comment by amolnater-qasource** [comment]
Hi @joshdover 
Thank you for the feedback.
We have revalidated this issue with increased Integration Server memory and "Max agents" count setting set to 10000 and found it working fine.

**Observations:**
- All agents gets unenrolled on triggering 10k agents Unenroll from Bulk actions.

**Build details:**
BUILD: 55166
COMMIT: 9e9e0d6a685cbc2858a85a357f93dcb76259fdee

**Screenshot/Screen Recording:**

https://user-images.githubusercontent.com/77374876/183401717-f21b8500-1a0e-4481-add1-41d4ef8c2301.mp4

![4](https://user-images.githubusercontent.com/77374876/183401752-68865c0e-5ede-4184-bc88-6485ec936a4d.JPG)

Hence we are closing this issue and marking it as **QA:Validated**.

Thanks
