### ISSUE TITLE
[Fleet Server] 🔐 TLS 1.2+ Support

### ISSUE THREAD

**Issue by nicpenning** [elastic/fleet-server#1645]
**Describe the enhancement:**
Greetings! Currently, Fleet servers are listening on port 8220 by default and appear to be using TLS 1.1 according to vulnerability scan data. This is in a cluster version of 8.3.2. Is TLS 1.1 the only option for secure authentication/communication? I would like the ability to use TLS 1.2 and 1.3 if possible.

**Describe a specific use case for the enhancement or feature:**
TLS 1.1 is an older protocol and carries more risk than that of 1.2 and 1.3.

No where in the platform can I find a way to configure the TLS version nor is it documented what version of TLS the Fleet server will use. Please advise!

**Comment by nicpenning** [comment]
So it appears I can enumerate TLS 1.3 from a browser so that is great. So I guess this feature might better be adjusted to allow configuration settings to be set to only specific versions of TLS that can be used.

I tried this settings in the Fleet Server settings:
(But after another scan, TLS 1.1 still seems to be popping up.)
![image](https://user-images.githubusercontent.com/5582679/178052455-783791f7-c1b4-4f4b-8efb-fb611c6d9fe2.png)

**Comment by drizzthacker** [comment]
Same problem here, we cannot pass a certification while fleet server supports tlsv1.1 and old cipher suites. Is there a way to properly setup tls?

**Comment by drizzthacker** [comment]
I think I've solved it, instead your options I've tried this with "server." before "ssl":

`server.ssl.supported_protocols: [ TLSv1.2 ]
server.ssl.cipher_suites: [ "ECDHE-RSA-AES-256-GCM-SHA384", "ECDHE-RSA-AES-128-GCM-SHA256", "ECDHE-ECDSA-AES-128-GCM-SHA256", "ECDHE-ECDSA-AES-256-GCM-SHA384", "ECDHE-ECDSA-CHACHA20-POLY1305" ]`

and seems to work, at least fot TLSv1.2 could you try it?

It should be documented...

**Comment by zez3** [comment]
Indeed, I see the same on my ECE containers

hmm, not quite behind the go-http-proxy?

```
nmap -sV --script ssl-enum-ciphers -p 18661 0.0.0.0
Starting Nmap 7.80 ( https://nmap.org ) 
Nmap scan report for 0.0.0.0
Host is up (0.000069s latency).

PORT      STATE SERVICE  VERSION
18661/tcp open  ssl/http Golang net/http server (Go-IPFS json-rpc or InfluxDB API)
| ssl-enum-ciphers:
|   TLSv1.1:
|     ciphers:
|       TLS_RSA_WITH_AES_128_CBC_SHA (rsa 2048) - A
|       TLS_RSA_WITH_AES_256_CBC_SHA (rsa 2048) - A
|       TLS_RSA_WITH_3DES_EDE_CBC_SHA (rsa 2048) - C
|     compressors:
|       NULL
|     cipher preference: server
|     warnings:
|       64-bit block cipher 3DES vulnerable to SWEET32 attack
|       Forward Secrecy not supported by any cipher
|   TLSv1.2:
|     ciphers:
|       TLS_RSA_WITH_AES_128_GCM_SHA256 (rsa 2048) - A
|       TLS_RSA_WITH_AES_256_GCM_SHA384 (rsa 2048) - A
|       TLS_RSA_WITH_AES_128_CBC_SHA (rsa 2048) - A
|       TLS_RSA_WITH_AES_256_CBC_SHA (rsa 2048) - A
|       TLS_RSA_WITH_3DES_EDE_CBC_SHA (rsa 2048) - C
|     compressors:
|       NULL
|     cipher preference: server
|     warnings:
|       64-bit block cipher 3DES vulnerable to SWEET32 attack
|       Forward Secrecy not supported by any cipher
|_  least strength: C
```

3DES_EDE_CBC_SHA
Hmm, that ^ is not good

and directly in container:

```
I have no name!@2ed1d92b5c33:/usr/share/elastic-agent$ curl --tlsv1.0 --tls-max 1.0 0.0.0.0:8220 -v
*   Trying 0.0.0.0:8220...
* TCP_NODELAY set
* Connected to 0.0.0.0 (127.0.0.1) port 8220 (#0)
> GET / HTTP/1.1
> Host: 0.0.0.0:8220
> User-Agent: curl/7.68.0
> Accept: */*
>
* Mark bundle as not supporting multiuse
* HTTP 1.0, assume close after body
< HTTP/1.0 400 Bad Request
<
Client sent an HTTP request to an HTTPS server.
* Closing connection 0
```

and no @drizzthacker,  that workaround does not work for my ECE for Fleet 
but is indeed included in the APM config
under
# USER OVERRIDES

**Comment by defensivedepth** [comment]
Will this be set by default in upcoming versions of Fleet?

**Comment by zez3** [comment]
> Will this be set by default in upcoming versions of Fleet?

any ETA on the new version?

**Comment by nicpenning** [comment]
Confirmed that 
```
server.ssl:
    supported_protocols: ["TLSv1.2", "TLSv1.3"]
```
works.
