### ISSUE TITLE
Drop support for 32bit version

### ISSUE THREAD

**Issue by ruflin** [elastic/fleet-server#166]
Currently fleet-server is also built for 32bit version: https://github.com/elastic/fleet-server/blob/master/Makefile#L3 I think for simplicity fleet-server is not required in 32bit and we should drop support for it. This issue is to discuss this.

**Comment by mostlyjason** [comment]
I think 32 bit platforms are less common in the o11y space, particularly for centralized infrastructure like Fleet server. Elasticsearch and Kibana only support 64-bit platforms https://www.elastic.co/support/matrix. We expect Fleet server to run close to Kibana from an infrastructure perspective.

@bradenlpreston @caitlinbetz is there any need for 32-bit support in Fleet server on the security side?

**Comment by EricDavisX** [comment]
Is it confusing if we have an x86 version of Agent (we have many artifacts) but they are unable to run Fleet server?  As long as it fails gracefully with some error messaging, I think it is a win to reduce scope and complexity with this decision.

**Comment by bradenlpreston** [comment]
No issues from my end in not supporting a 32-bit fleet server. Do we need to check with APM as agent will eventually run Fleet Server and APM server.

**Comment by ruflin** [comment]
I'm not sure if we need to attach this to apm-server as a user could still run Elastic Agent with apm-server on the edge in 32bit but Elastic Agent with fleet-server centrally. The two do not depend on each other.

@graphaelli What is the apm-server support for 32bit?

**Comment by graphaelli** [comment]
We currently do publish 32 bit packages and support them, though I don't recall any issues specifically mentioning those artifacts.  Stats indicate ~ 20% of downloads are 32 bit, a much higher percentage than beats.

**Comment by jlind23** [comment]
Closing it as this was done already.
cc @nimarezainia @ph
