### ISSUE TITLE
Investigate the traffic use for Elastic Agent

### ISSUE THREAD

**Issue by ph** [elastic/fleet-server#1697]
It would be good to know what is the amount of traffic used by Elastic Agent during his operation.
This would help us for sizing calculation.

 I would like to say:

- Considering a normal operation, healthy state and a stable deployment X Elastic Agent would consume X number of bytes for a time period.
- When Elastic Agent is failing it consume X number of bytes per period.

**Comment by jlind23** [comment]
Closing this one as outdated/not prioritised, we will reopen it later if required.
cc @ycombinator
