### ISSUE TITLE
[Fleet]: User is unable to install Fleet Server agent on Kibana Cloud environment.

### ISSUE THREAD

**Issue by simranvaseer-qasource** [elastic/fleet-server#1701]
**Kibana version**: 8.4 BC1 Kibana cloud environment

**Host OS and Browser version**: All, All

**Build details:**

VERSION: 8.4 BC1
BUILD: 54999
COMMIT: 58f7eaf0f8dc3c43cbfcd393e587f155e97b3d0d
ARTIFACT LINK: https://staging.elastic.co/8.4.0-91109cf0/summary-8.4.0.html

**Preconditions:**
- 8.4 BC1 Kibana cloud environment should be available.

**Steps to reproduce:**

1. Login to Kibana environment.
2. Now, Navigate to Agents tab.
3. Click on 'Add Fleet Server' button.
4. Add Fleet Server host say' http://10.10.10.10:8220/
5. Click on 'Generate Fleet server policy'
6. Copy and run the command on cli.
7. Observe the fleet server agent is not installed.

**Expected Result:**
User should be able to install Fleet Server agent on Kibana Cloud environment.

**Screenshots:**

- ![1](https://user-images.githubusercontent.com/102019374/181719820-c177c8f7-9633-411d-8d8a-02b3ca157e18.PNG)
 
- ![2](https://user-images.githubusercontent.com/102019374/181720167-c61dfd22-d718-4fdd-83bf-02d7a9d0df42.PNG)

- ![image](https://user-images.githubusercontent.com/102019374/181719323-fb8531be-aa38-4814-9639-71f78e375fb0.png)

**Comment by steveytam** [comment]
havingthe same issue here using elastic agent 8.3

**Comment by simranvaseer-qasource** [comment]
Hi Team
We have revalidated this issue on latest 8.4 BC2 Kibana cloud environment and found it **fixed** now.

- We are successfully able to install Windows Fleet Server.

**Build Details:**
BUILD: 55166
COMMIT: 9e9e0d6a685cbc2858a85a357f93dcb76259fdee
ARTIFACT LINK: https://staging.elastic.co/8.4.0-f1a133aa/summary-8.4.0.html

**Screenshots:**
![Screenshot (3)](https://user-images.githubusercontent.com/102019374/182816860-e55ffd16-3b7e-4bb8-a721-d639d516ee99.png)
![image](https://user-images.githubusercontent.com/102019374/182816954-161deb2a-580a-473e-95f6-ff407ef2957e.png)

Hence, we are closing this issue and marking as QA:Validated.
Thanks

**Comment by amolnater-qasource** [comment]
### `Bug Conversion`

- Test-Case not required as this particular checkpoint is already covered in the following testcase:
   - https://elastic.testrail.io/index.php?/cases/view/77048
 
Thanks!
