### ISSUE TITLE
[Fleet] Configuring host through the agent policy is not working

### ISSUE THREAD

**Issue by nchaulet** [elastic/fleet-server#172]
## Description 

In a docker container
While configuring the host to `0.0.0.0` through the fleet server integration https://github.com/elastic/integrations/pull/806 the fleet server inside the container is still bind to `localhost`.

**Comment by ruflin** [comment]
It works when the FLEET_SERVER_HOST is set to `0.0.0.0`. I wonder if the fleet-server does not reload the server part on changes?
