### ISSUE TITLE
[Scalability] Add APM instrumentation with Span Links

### ISSUE THREAD

**Issue by juliaElastic** [elastic/fleet-server#1736]
I have a use case for this with in Fleet Server's APM instrumentation. We have a bulk process that will batch search and indexing requests from multiple incoming HTTP requests from Elastic Agents into a single `_msearch` or `_bulk` request against Elasticsearch. It'd be great to be able to connect each bulk request to their upstream incoming HTTP request from Elastic Agents.

The Go API is available now to do this:
https://github.com/elastic/apm-agent-go/issues/1243

_Originally posted by @joshdover in https://github.com/elastic/apm/issues/122#issuecomment-1181698840_

**Comment by michel-laterman** [comment]
Done as part of https://github.com/elastic/fleet-server/pull/2929
