### ISSUE TITLE
Incorrect behavior for `http.detailed_errors.enabled: false`

### ISSUE THREAD

**Issue by michalpristas** [elastic/fleet-server#1743]
`http.detailed_errors.enabled` is an ES option modifying format of error responses
while we expect complex error response such as this
```
{
  "error": {
    "root_cause": [
      {
        "type": "index_not_found_exception",
        "reason": "no such index [.fleet-actions]",
        "resource.type": "index_expression",
        "resource.id": ".fleet-actions",
        "index_uuid": "_na_",
        "index": ".fleet-actions"
      }
    ],
    "type": "index_not_found_exception",
    "reason": "no such index [.fleet-actions]",
    "resource.type": "index_expression",
    "resource.id": ".fleet-actions",
    "index_uuid": "_na_",
    "index": ".fleet-actions"
  },
  "status": 404
}
```

when `http.detailed_errors.enabled` is modified and set to `false` error returned is a simple string e.g.

```
{
   "error": "IndexNotFoundException[no such index [.fleet-actions]]",
   "status": 404
}
```

we need to have a fallback mechanism in place which is capable of handling both cases. 

**This makes starting a fleet server problematic and user cannot get through `enroll`**

**Comment by ph** [comment]
Oh I didn't know about this error detailed..

**Comment by aleksmaus** [comment]
> Oh I didn't know about this error detailed..

neither did I

probably change to json.RawMessage for the "error" and update the error parsing code slightly

**Comment by cmacknz** [comment]
I think there is a duplicate report of this in the agent repo https://github.com/elastic/beats/issues/32676 but with some clarifying comments from the ES team https://github.com/elastic/beats/issues/32676#issuecomment-1214730480

**Comment by michalpristas** [comment]
correct, thank @cmacknz i'm closing this in favor of that one. source is the same SDH
