### ISSUE TITLE
Extend local_meta information for elastic agent

### ISSUE THREAD

**Issue by shahzad31** [elastic/fleet-server#1754]
Each registered agent in the fleet contains information about it's local meta 

<img width="884" alt="image" src="https://user-images.githubusercontent.com/3505601/185102828-240d1fb7-3f60-4a2a-b449-90bde7494502.png">

For synthetics, we ask user to use elastic-agent-complete variant which also contains browser dependencies. From synthetics plugin in kibana, we would like to determine if the agent registered is complete or not and hence warn user if they are trying to run browser monitor on simple elastic agent. 

For that we need that information in the local_meta of the agent. So when user installs an agent and if its an elastic-agent-complete docker image https://hub.docker.com/r/elastic/elastic-agent-complete, we should add a flag saying. Its an es agent complete. So that we can consume that info in kibana.

**Comment by shahzad31** [comment]
so this will not a user action, we want this boolean to auto added based on the docker image being used.

**Comment by ph** [comment]
I see in this case, it could be added automatically when the elastic agent is run with the `container` subcommand.

**Comment by shahzad31** [comment]
@ph any updates on prioritising this issue?

**Comment by cmacknz** [comment]
We don't have this on our priority list, you'll want to get in touch with @pierrehilbert (currently on PTO) about getting this prioritized.

**Comment by nimarezainia** [comment]
@shahzad31 @cmacknz I am wondering whether it serves us better in the future if we have some sort of a capabilities list? instead of a boolean? a list that can be parsed, for example synthetics can parse for some value they have an interest in etc

I can't immediately think of other use cases but feel that it would serve us better in the future to allow platform users to utilize these advertised capabilities.

**Comment by shahzad31** [comment]
@nimarezainia that will work as well.

**Comment by shahzad31** [comment]
@nimarezainia any update on this?

**Comment by nimarezainia** [comment]
@shahzad31 I'm sorry we are currently completely drained for capacity and are mainly concentrating our efforts on stability of software and only some of the highest priority features. Feel free to create a PR that @pierrehilbert or @cmacknz could review for you if it's a small change.

**Comment by emilioalvap** [comment]
Hi @cmacknz,

We are looking into contributing to this ourselves, would adding the contents of `capabilities.yml` to the [agent metadata](https://github.com/elastic/elastic-agent/blob/2a3dfaa4fd1bb0e0da48801b37dda570763dc1aa/internal/pkg/agent/application/info/agent_metadata.go#L158) be an appropriate compromise here?

**Comment by cmacknz** [comment]
Capabilities.yml isn't widely used enough that it would be worth including by default in the agent metadata. We use it in our own cloud to lock down the agent that runs Fleet Server, but that is pretty much the only major use of it that I know of.

This feels like something that can just be a boolean flag under `local_metadata .elastic.agent`, possibly as simple as `local_metadata.elastic.agent.complete: true` for example.

We are considering building a lighter weight version of the non-containerized agent, the current default would effectively be the complete version with all binaries included. So this flag would work there too to allow us to distinguish the builds.

**Comment by cmacknz** [comment]
The current contents of `local_metadata.elastic.agent` for reference:

```json
  "local_metadata": {
    "elastic": {
      "agent": {
        "build.original": "8.8.2 (build: cdc5ba9b1d2c90fdfd0e998e3e744e46a225c313 at 2023-06-26 16:18:13 +0000 UTC)",
        "id": "a65dd572-d5bb-4b91-b1ac-6781e5e840f5",
        "log_level": "info",
        "snapshot": false,
        "upgradeable": true,
        "version": "8.8.2"
      }
    },
```

**Comment by awahab07** [comment]
**Post FF Testing**

Tested `8.10.0-Snapshot` and it LGTM!
|`docker.elastic.co/beats/elastic-agent:8.10.0-SNAPSHOT`|`docker.elastic.co/beats/elastic-agent-complete:8.10.0-SNAPSHOT`|
|:--:|:--:|
|<img width="463" alt="Screenshot 2023-09-04 at 14 09 49" src="https://github.com/elastic/fleet-server/assets/2748376/465a8f09-2c09-4cf3-a28f-4d793e134023">|<img width="461" alt="Screenshot 2023-09-04 at 14 10 17" src="https://github.com/elastic/fleet-server/assets/2748376/1a47f458-2733-43de-b336-da7dcc9d78b4">|
