### ISSUE TITLE
remove events from agent checkin

### ISSUE THREAD

**Issue by michel-laterman** [elastic/fleet-server#1774]
Issue https://github.com/elastic/elastic-agent/issues/993 tracks removing events from checkin requests.
we should also remove any references in the server codebase, i.e., https://github.com/elastic/fleet-server/blob/e65a42e98c3f8ff3edd676712addac61e1187e10/internal/pkg/api/schema.go#L83

**Comment by amitkanfer** [comment]
@blakerouse should we back-port to 8.4?

**Comment by blakerouse** [comment]
Backport here -  https://github.com/elastic/fleet-server/pull/1850
