### ISSUE TITLE
can not select new outputs for agent policies,why?

### ISSUE THREAD

**Issue by zzyyi66** [elastic/fleet-server#1793]
![image](https://user-images.githubusercontent.com/89442807/187634840-06bb3271-0422-43d6-8d32-d101c35fd3d3.png)

**Comment by jlind23** [comment]
Hi @zzyyi66,

Agent monitoring data will only be send to the default output for now. This is why you can not change it.
What you can change is the output for other data gathered by integrations for example.

**Comment by zzyyi66** [comment]
> Hi @zzyyi66,
> 
> Agent monitoring data will only be send to the default output for now. This is why you can not change it. What you can change is the output for other data gathered by integrations for example.
Output for integrations is also can not change,i'm on eck 2.4

**Comment by zzyyi66** [comment]
![image](https://user-images.githubusercontent.com/89442807/187644872-0adcd97f-2d31-43ca-951c-9a5feecabde6.png)

**Comment by jlind23** [comment]
@zzyyi66 Would you mind opening a discuss thread for that? Engineers will take a look over there and give you pointers as soon as possible.
