### ISSUE TITLE
[Fleet]: Unable to install fleet server when policy having id other than `fleet-server-policy` used for installation.

### ISSUE THREAD

**Issue by amolnater-qasource** [elastic/fleet-server#1829]
**Kibana version:** 8.5 Snapshot Kibana cloud environment

**Host OS and Browser version:** All, All

**Build details:**
VERSION: 8.5 Snapshot Kibana cloud environment
BUILD: 55993
COMMIT: 436b2874794a6ffc05ad3b9ef28c298ff5384ca4

**Preconditions:**
1. 8.5 Snapshot Kibana cloud environment should be available.

**Steps to reproduce:**
1. Navigate to Fleet>Add Fleet Server.
2. From Advanced option create a new policy, add host and run fleet server install command.
3. Observe install command failed: `Error: enroll command failed with exit code: 1`.

**Expected Result:**
Fleet server should be installed when policy having id other than `fleet-server-policy` used for installation.

**Screenshots:**
![2](https://user-images.githubusercontent.com/77374876/188368311-3f598fb5-c192-45ad-b0b1-15608a37b85d.JPG)

**What's working fine:**
- Fleet Server is successfully installed when policy having id `fleet-server-policy` used for installation.
![1](https://user-images.githubusercontent.com/77374876/188369238-c7f9ef81-556b-410c-8e57-9e45a10a1918.JPG)

**Comment by amolnater-qasource** [comment]
@manishgupta-qasource Please review.

**Comment by manishgupta-qasource** [comment]
Secondary review for this ticket is Done

**Comment by amolnater-qasource** [comment]
FYI @jlind23

**Comment by nchaulet** [comment]
It's normally possible to add a Fleet server with another id than `fleet-server-policy` as long the policy has the `fleet-server` integration, @amolnater-qasource can you confirm that the policy `42...` contains a Fleet server package policy?

**Comment by amolnater-qasource** [comment]
Hi Team
We have revalidated this issue on latest 8.5 BC1 kibana cloud environment and found it **fixed** now.

**Observations:**
- We are successfully able to install fleet server using policies with id having other than `fleet-server-policy`.

**Build details:**
VERSION: 8.5 BC1
BUILD: 56595
COMMIT: 0d8de4df69f8084a94cdd9638d7de510813cb5ce

**Screenshots:**
![6](https://user-images.githubusercontent.com/77374876/192270659-693c42ba-9ae7-499d-9c37-5ef57e8193bf.JPG)


Hence we are **closing** this and marking it as **QA:Validated**.

Thanks
