### ISSUE TITLE
[Fleet]: Hosted Fleet Server is not available on Healthy deployment of 8.5.0-SNAPSHOT build.

### ISSUE THREAD

**Issue by samratbhadra-qasource** [elastic/fleet-server#1836]
**Description:**
Hosted Fleet Server not available on Healthy deployment of 8.5.0-SNAPSHOT when deployed from:

https://console.qa.cld.elstc.co/
https://staging.found.no/

**Build Details:**
VERSION: 8.5.0-SNAPSHOT
COMMIT:  2c5fae2037b138f09231770ef19f0b11c0325c01
BUILD:  56060
ARTIFACT LINK: https://snapshots.elastic.co/8.5.0-4140365c/summary-8.5.0-SNAPSHOT.html

**Preconditions:**
1. Elastic 8.5.0-SNAPSHOT environment should be deployed.

**Steps to Reproduce:**

1. Navigate to the Fleet tab under Management.
2. Now, Navigate to Agents tab .
3. Observe that hosted Fleet Server not available on Healthy deployment of 8.5.0-SNAPSHOT build.

**Screenshot:**
![Screenshot (947)](https://user-images.githubusercontent.com/84007952/189038533-b41f3649-b162-4496-abce-9613214f1286.png)
![Screenshot (945)](https://user-images.githubusercontent.com/84007952/189038195-2ca70be4-270c-4458-a843-5442be7f031d.png)
![Screenshot (943)](https://user-images.githubusercontent.com/84007952/189036600-693831b4-b3e8-4fec-b69a-5fac55a28da3.png)

**Note:**
No errors were observed on deployment page.

**Comment by dikshachauhan-qasource** [comment]
Secondary review is done

**Comment by amolnater-qasource** [comment]
Hi @joshdover @jlind23 
We are unable to deploy latest 8.5 SNAPSHOT kibana from:
- https://console.qa.cld.elstc.co/
- https://staging.found.no/

**Screenshot:**
![image](https://user-images.githubusercontent.com/77374876/189580225-2606f6ab-06d2-460f-bdf9-257b50e070ff.png)

Hence we are blocked to test any features/fixed PR merges on latest 8.5 Snapshot Kibana cloud environment.
However we are running some agents and beats related tests on 8.5 Self-managed Kibana.

Please let us know if anything else is required from our end.
Thanks

**Comment by samratbhadra-qasource** [comment]
Hi Team
We are successfully able to deploy latest Healthy 8.5.0-SNAPSHOT environment from:

https://console.qa.cld.elstc.co/
https://staging.found.no/

**Screenshot:**
![Screenshot (967)](https://user-images.githubusercontent.com/84007952/190064849-68cfc570-97c5-4349-9444-e715a1cf6134.png)
![Screenshot (968)](https://user-images.githubusercontent.com/84007952/190064859-f0295d31-deb3-4caf-a391-24f81c5f7eff.png)

**Build Details:**
VERSION: 8.5.0-SNAPSHOT
BUILD: 56148
COMMIT: 1d7d0563fbdc327e9afe8d7a94495546940c1357

Hence we are closing this issue.
Thanks!

**Comment by simranvaseer-qasource** [comment]
### `Bug Conversion`

- Test-Case not required as this particular checkpoint is already covered in the following testcase:
   - https://elastic.testrail.io/index.php?/cases/view/149907&group_by=cases:section_id&group_order=asc&display_deleted_cases=0&group_id=25985

Thanks
