### ISSUE TITLE
Invalid config values in Fleet Server policy crash without warning

### ISSUE THREAD

**Issue by joshdover** [elastic/fleet-server#1848]
- Version: 8.4.1
- Steps to Reproduce: 
1. Add an invalid config to Fleet Server's "custom configuration" yaml box on the policy in the Fleet UI, like `agent.logging.level: debug`
2. Save the policy
3. Fleet Server / Integrations Server will go unhealthy, nothing works now
4. There's no log anywhere to be found
5. Since Fleet Server is unhealthy, you can't remotely update the agent's configuration from the UI
6. Only way to fix is to remove the invalid config, then restart externally (eg. via Cloud UI)

**Comment by joshdover** [comment]
@kpollich Ideally we don't allow invalid configuration in the custom yaml box at all. I don't believe we have support for validation from the package-spec side, but I wonder if we should hard code something special for Fleet Server for now.

**Comment by kpollich** [comment]
I'd be open to hardcoding some kind of validation schema for Fleet Server specifically in this instance because the result of misconfiguring Fleet Server through this YML box is essentially taking down your whole Fleet environment.

**Comment by joshdover** [comment]
> I'd be open to hardcoding some kind of validation schema for Fleet Server specifically in this instance because the result of misconfiguring Fleet Server through this YML box is essentially taking down your whole Fleet environment.

@kpollich could you track a separate issue for this for the UI validation? I think we can prioritize this one first since we should have both.

**Comment by michel-laterman** [comment]
I'm unable to recreate this on a selfhosted deployment for 8.4.1

**Comment by michel-laterman** [comment]
also unable to recreate on `8.4.1` on cloud

**Comment by joshdover** [comment]
Let's close this if we can reproduce. I've only seen this once and haven't been able to repro either. Must have been caused by something else.
