### ISSUE TITLE
Allow the user to edit the connection limit live

### ISSUE THREAD

**Issue by mostlyjason** [elastic/fleet-server#185]
We'd like to gracefully manage the capacity of the Fleet Server to prevent it from crashing. In the first phase, there will be hard limit(s) and users must manually adjust them. The [overall meta issue](https://github.com/elastic/fleet-server/issues/153) defines the subsequent phases where we hope to make this more automatic. 

We've already implemented a max connection limit here https://github.com/elastic/fleet-server/pull/122 and we've added this limit to the integration policy here https://github.com/elastic/integrations/issues/803

Requirements:
- [x] Users can update the limit(s) in the integration policy, and they are applied dynamically to the fleet server (they are "live" settings).
- [x] Add docs on the limit(s) to the Fleet Server's operator's guide https://github.com/elastic/obs-dc-team/issues/147. Describe how users can edit the limit(s), guidance on what they should set the limit(s) to https://github.com/elastic/fleet-server/issues/134, how they know when the limit(s) are hit.

**Comment by mostlyjason** [comment]
@ph I filed this one to confirm that it works as a live setting, and I left the original as a meta issue / epic

**Comment by ph** [comment]
@scunningham or @aleksmaus can confirm, you have added a limit on the number of connections that the fleet server can accept, if we expose that value in the fleet-server integration and the value changes, how fleet server will behave? Does it use the new limit and what happens to the connected clients it we are over limit?

**Comment by scunningham** [comment]
In the current implementation, the max_connections is a hard limit on the number of connections that the server will accept.  If the user reconfigures the server, the previous connections will be dropped, and subsequent connections will obey the new limit.

However, I am also adding more fine grained controls on each of the API's which limits the rate at which we can service each api, and how many parallel executions of the api are allowed.  While max connections is still a useful configuration to set to limit abuse of the system, you would probably set that to something higher than the number of supported connections.  This is to allow other api calls such as artifacts, etc to get through.  (I'm thinking 2x targeted connections).  To limit the total number of supported agents in the new implementation, you would set the max number of parallel "checkin" calls that are allowed.  If any of the api's are at capacity, they will return a 429 code.

**Comment by ph** [comment]
@scunningham I was not able to find an issue for the behavior you are describing, when you are considering landing theses options? Because this would require change in the fleet-server integration and possibly in the way we setup the integration?


@mostlyjason With the above comment from Sean and the work that @nchaulet did I think the first requirement is done. 

Looking at the second one which is documentation and recommendation, @scunningham is that something you could take on your side?

**Comment by scunningham** [comment]
Working on the PR.  This working is being done to help limit RAM bursts in the tiny amount of memory we have available in the 512mb container along side agent, beats, and apm server.

I don't think it changes the setup much.  Just more configuration options;  this one limit just happens to be in a different place in the configuration than the previous.

**Comment by mostlyjason** [comment]
> If the user reconfigures the server, the previous connections will be dropped, and subsequent connections will obey the new limit.

@scunningham Its not ideal to drop thousands of connections, but I assume there is not a straightforward to drop only the connections over the new limit?

>  While max connections is still a useful configuration to set to limit abuse of the system, you would probably set that to something higher than the number of supported connections. This is to allow other api calls such as artifacts, etc to get through. (I'm thinking 2x targeted connections)

I think i misunderstood the definition for max connections. I think we need a way to limit the max number of agents that are allowed to enroll so the agents can be load balanced to a fleet server with available capacity. This allows fleet server to provide good service to the enrolled agents, including delivering artifacts. If we only limit the max connections or parallel executions it doesn't solve the problem of load balancing enrollments.

**Comment by mostlyjason** [comment]
I had a chat with @scunningham on Slack and clarified that I meant to describe a limit on the number of persistent connections from agents checking in to an instance of Fleet server, not the number of enrollments. He also described his idea for multiple rate limits, where we could have separate limits for check ins and artifacts. I'll let him describe his proposal when he's ready.

**Comment by simitt** [comment]
Load balancing was mentioned a couple of times here; what happens if multiple fleet-server instances are running? Are they sharing the same limit and therefore would be some simple load balancing be sufficient?

**Comment by mostlyjason** [comment]
@simitt I think if multiple instances were running they could have the same or different limits, and even a simple algorithm like round robin would distribute load to available servers. Is that what you had in mind?

**Comment by scunningham** [comment]
The cloud proxy is expected to load balance in the way @simitt describes.  Just as well, a customer could stand up a load balance in front of N fleet servers to achieve a similar effect.

**Comment by mostlyjason** [comment]
@nchaulet @ph I think we still need to update the package definition to allow the user to set the new limits that Sean added?

**Comment by scunningham** [comment]
I added a sample configuration file with all the tweaks necessary to run Fleet Server in a memory constrained environment.  The change is in PR: https://github.com/elastic/fleet-server/pull/240

For larger installations we will need tweaks to make it run more efficiently.  If we change only the number of endpoints allowed to long poll for say a 10k installation, it will work but performance will be terrible.  For example, it will take a very very long time for all endpoints to checkin or roll out a new policy.

**Comment by jlind23** [comment]
Closing this as both requirements are met
