### ISSUE TITLE
Load limit presets should not overlap on max agents

### ISSUE THREAD

**Issue by joshdover** [elastic/fleet-server#1858]
Our presets currently overlap by 1 which ends up in having unexpected behavior if you configure max agents to a value like 30000. In this case you'll end up using the 12,500 - 30,000 presets rather than the >= 30000 preset:

```
Using system limits for 12500 to 30000 agents for a configured value of 30000 agents
```

You can see how the bug presents itself:
- 12.5k preset has a max of 30k: https://github.com/elastic/fleet-server/blob/0181e484a71fe98864a2c96866b3594970116612/internal/pkg/config/defaults/gt12500_limits.yml#L3
- \> 30k preset has a min of 30k: https://github.com/elastic/fleet-server/blob/0181e484a71fe98864a2c96866b3594970116612/internal/pkg/config/defaults/max_limits.yml#L2
- The code that iterates through these to choose a preset: https://github.com/elastic/fleet-server/blob/5b1c0df774371a15bfbbaf735de6cdeaa856c38c/internal/pkg/config/env_defaults.go#L181

This is sort of related to:
- https://github.com/elastic/fleet-server/issues/1841

**Comment by joshdover** [comment]
For now we could probably solve this easily by just changing the `min` on each preset to be one less than the max on the next preset

**Comment by blakerouse** [comment]
I am working on #1841, I will take this one as well.

**Comment by blakerouse** [comment]
I went with lowering the `max` by 1 in each default. That way if the number is 30000 you get the higher limits.

**Comment by jlind23** [comment]
> I went with lowering the max by 1 in each default. That way if the number is 30000 you get the higher limits.
 @blakerouse is this something you have done already?

Otherwise I created a [PR](https://github.com/elastic/fleet-server/pull/1891)
