### ISSUE TITLE
Load limit on fleet server also limits its own Elastic Agent

### ISSUE THREAD

**Issue by jlind23** [elastic/fleet-server#1859]
Apparently, the connection limit is applied to Fleet Server own Elastic Agent.
This mean that under an heavy load, the Fleet Server Elastic Agent can be prevented from checkin in and as a result FS is shown as unhealthy.

This issue will act as a placeholder for any further discoveries regarding Fleet Server config.

**Comment by scunningham** [comment]
This was noted a while ago:  https://github.com/elastic/fleet-server/issues/524

The Fleet Server should be communicating with the Elastic Agent on a dedicated loopback port.  Related code [here](https://github.com/elastic/fleet-server/blob/main/internal/pkg/config/input.go#L97).  Is this not happening?

**Comment by jlind23** [comment]
Based on recent tests done by @ablnk and following an analysis done by @joshdover. Fleet server elastic agent is logging "429" errors due to Fleet server limiting the number of connection.

**Comment by scunningham** [comment]
I would be curious to know if the Fleet Agent is using the loopback.

**Comment by jlind23** [comment]
@michel-laterman - @michalpristas is already looking at it. We'll ping you as soon as we progress on this

**Comment by michalpristas** [comment]
looks like failure is not coming from max_connection limiter but rather from checkin Limit limiter.
While max connection limiters are separated and created per listener. 
Limits (such as checkin) are enforced in handler while router is shared in between servers. 

in `main.go`

```go
        ct := api.NewCheckinT(f.verCon, &cfg.Inputs[0].Server, f.cache, bc, pm, am, ad, tr, bulker)
        router := api.NewRouter(ctx, bulker, ct, et, at, ack, st, sm, tracer, f.bi)

	g.Go(loggedRunFunc(ctx, "Http server", func(ctx context.Context) error {
		return api.Run(ctx, router, &cfg.Inputs[0].Server)
	}))
```

inside handler (`internal/pkg/api/handleCheckin.go`) we have

```go
ct := &CheckinT{
		verCon: verCon,
		...,
		limit:  limit.NewLimiter(&cfg.Limits.CheckinLimit),
		bulker: bulker,
	}
```

then this is used in `internal/pkg/api/server.go`

```go
for _, addr := range listeners {
		server := http.Server{
			Addr:              addr,
			...
			Handler:           router,  <<<
			...,
		}
```

we need to find a solution to separate these, some are nicer (separate router per listener) some are faster (apply limit only for external requests)

**Comment by scunningham** [comment]
Interesting.  Probably not hitting the max-checkin case; but can certainly hit the throttle to prevent check-ins coming to fast. 

Cleanest way would be to create a separate router for each interface.  Agreed.  Adding limit per external request is going to be messy and hard to reason about.

**Comment by michel-laterman** [comment]
Instead of creating a separate router per listener, which would require creating separate endpoint handers (`CheckinT`, `AckT`, etc) just so a different instance of a listener is associated with a route.
I think we should refactor the limiter so it can be used as a route-aware middleware layer on the http server. This way we can just make separate limiters for each listener.
It also would cleanly split checking a limit from the request handling logic.
