### ISSUE TITLE
GET /agent_policies doesn't return any package_policies

### ISSUE THREAD

**Issue by kpashko** [elastic/fleet-server#1865]
Hi, in 8.5.0 we noticed that [/agent_policies](https://petstore.swagger.io/?url=https://raw.githubusercontent.com/elastic/kibana/master/x-pack/plugins/fleet/common/openapi/bundled.json#/default/agent-policy-list) endpont of Fleet API doesn't return any package_policies for policies. 

At the same time [ /agent_policy/{id}](https://petstore.swagger.io/?url=https://raw.githubusercontent.com/elastic/kibana/master/x-pack/plugins/fleet/common/openapi/bundled.json#/default/agent-policy-info) response has package_policies.

Version 8.4.1 returned list of package policies for both requests. 

## Vesion 8.5.0
  * /agent_policies response. policy-elastic-agent-on-cloud don't have package policies
  
    ![image](https://user-images.githubusercontent.com/6763845/190249934-bd88eedd-16db-4cdb-b259-9ac673a348ab.png)

 
  * /agent_policies/policy-elastic-agent-on-cloud. package policies are present
     
    ![image](https://user-images.githubusercontent.com/6763845/190250061-b7e49d3d-9123-4d80-ad78-b3bbed215d67.png)

 
## Version 8.4.1
  * /agent_policies response
    
    ![image](https://user-images.githubusercontent.com/6763845/190249799-bf9f14b9-3c21-4b5b-a38d-6d985bb978d0.png)

**Comment by nchaulet** [comment]
Hi @kpashko 

We made a breaking change in 8.5 https://github.com/elastic/kibana/pull/138677 (Fleet API are still beta)
If you need the package policies in the `GET /agent_policies` this could be done by calling the API with `?full=true`

**Comment by kpashko** [comment]
@nchaulet got it, thanks! 
Should I open an issue to kibana team to update the [api doc](https://petstore.swagger.io/?url=https://raw.githubusercontent.com/elastic/kibana/master/x-pack/plugins/fleet/common/openapi/bundled.json#/default/agent-policy-list)?

**Comment by nchaulet** [comment]
Thanks for catching this I created the following PR to fix the documentation https://github.com/elastic/kibana/pull/140857

**Comment by kpashko** [comment]
Thanks @nchaulet! Feel free to close the issue. All good on our side.
