### ISSUE TITLE
[Fleet] Support new "request diagnostics" action type

### ISSUE THREAD

**Issue by kpollich** [elastic/fleet-server#1883]
Relates to https://github.com/elastic/kibana/issues/141074
Blocked by https://github.com/elastic/security-team/issues/4661
Blocked by https://github.com/elastic/fleet-server/pull/1902

## Summary

We're looking to add a "request diagnostics" workflow to Fleet UI that allows users to remotely fetch diagnostics from their running agents, then download the resulting `.zip` files in Fleet UI. This will improve supportability quite a bit, and reduce a lot of the support overhead associated with retrieving diagnostics from agents today. 

## Implementation

Fleet UI will create a new action type, e.g. `REQUEST_DIAGNOSTICS` that Fleet Server and Elastic Agent will need to understand and respond to appropriately.

- [ ] Fleet Server
  - [ ] Receive `REQUEST_DIAGNOSTICS` actions written to the `.fleet-actions` index by Fleet UI
  - [ ] Update the status (pending, complete, error) of the action as appropriate, based on the results from Agent. e.g. the action should be in an error state if the agent is offline/unreachable.
  - [ ] Dispatch the request for diagnostics based on the agent ID included in the `REQUEST_DIAGNOSTICS` action payload
- [ ] Elastic Agent
  - [ ] Receive requests for diagnostics from Fleet Server
  - [ ] Collect diagnostics using the existing `elastic-agent diagnostics collect` command
  - [ ] Upload the resulting `.zip` file using the new Fleet Server file upload API
  - [ ] Report errors/completion status and ensure the action's status is updated based on the result of the operation

**Comment by juliaElastic** [comment]
> Update the status (pending, complete, error) of the action as appropriate, based on the results from Agent. e.g. the action should be in an error state if the agent is offline/unreachable.

Currently the actions work in a way that actions are delivered on check-in, so Fleet Server is not doing anything with an action if the agent is offline (not checking in). Eventually the action will expire though (expiration is set to 1 month for unenroll and reassign, 1 or more hours for upgrade).

**Comment by kpollich** [comment]
> Eventually the action will expire though (expiration is set to 1 month for unenroll and reassign, 1 or more hours for upgrade).

This makes sense. We'll probably want a shorter TTL on these actions so we can display an error state in the file listing UI once we're confident the agent isn't going to successfully upload them.

**Comment by juliaElastic** [comment]
I had a look at the Fleet Server code, and it doesn't seem like we need any special logic for the new action type. 
Tested with local FS, and the `REQUEST_DIAGNOSTICS` action was delivered to agents and was acked immediately without any code change. I suppose it works as a no-op on Agent and FS side. 
@michel-laterman do you find this assumption correct?

**Comment by juliaElastic** [comment]
Changes needed in elastic-agent:

- [ ] Add a new handler for request diagnostics action [here](https://github.com/elastic/elastic-agent/tree/main/internal/pkg/agent/application/pipeline/actions/handlers)
- [ ] call the [function](https://github.com/elastic/elastic-agent/blob/main/internal/pkg/agent/cmd/diagnostics.go#L197) that collects diagnostics and creates a zip file
- [ ] upload zip file to the new Fleet Server [upload API](https://github.com/elastic/fleet-server/pull/1902)
- [ ] save action id in file metadata (or send file id in action result)

**Comment by jlind23** [comment]
@juliaElastic Who is working on the Elastic Agent end?
@pierrehilbert @cmacknz was this plan in the first sprint?

**Comment by juliaElastic** [comment]
@jlind23 I pinged @michel-laterman to find out if he has time, otherwise I can look into it, though it might take longer as I am not familiar with the agent codebase.

**Comment by jlind23** [comment]
@juliaElastic thanks for the answer. @michel-laterman would indeed be a perfect fit here 😄

**Comment by michel-laterman** [comment]
Oops, sorry I missed the earlier discussion.

Yes, the `fleet-server` changes are not going to be very extensive, we would just need to determine signaling for successful/failed actions, does a successful ack contain any metadata about the uploaded archive? how does a failed attempt/upload indicate an issue?

With the v2 changes the diagnostics collection will have changed slightly(pr https://github.com/elastic/elastic-agent/pull/1140); it should be even easier to wrap a call to the coordinator or control server with a handler to collect the data. We just need to collect local log information to complete the bundle.

I'm assuming we want to upload the same `.zip` archive and not a series of files, correct?

**Comment by jlind23** [comment]
@kpollich has the most knowledge here and should be able to answer ^

**Comment by juliaElastic** [comment]
> Oops, sorry I missed the earlier discussion.
> 
> Yes, the `fleet-server` changes are not going to be very extensive, we would just need to determine signaling for successful/failed actions, does a successful ack contain any metadata about the uploaded archive? how does a failed attempt/upload indicate an issue?

I think Fleet Server should receive the file ID (should be returned by the upload API) on ack and save it in `.fleet-actions-results`, so then Fleet UI can retrieve the file by ID.
Failure messages can also be saved in `.fleet-actions-results` in the `error` field similarly to other actions.

> I'm assuming we want to upload the same `.zip` archive and not a series of files, correct?

Yes, we want to upload the diagnostics `.zip` file.
