### ISSUE TITLE
E2E testing and Fleet Server

### ISSUE THREAD

**Issue by cachedout** [elastic/fleet-server#1927]
This is a downstream issue from a tracking issue located here: https://github.com/elastic/e2e-testing/issues/3053

## Fleet Server pipeline

We have a pipeline which was at one time running on the Beats CI, called [Pipeline Fleet Server e2e tests Pipeline](https://beats-ci.elastic.co/job/e2e-tests/job/e2e-testing-fleet-server/). It has not been executed since [October of 2021](https://beats-ci.elastic.co/job/e2e-tests/job/e2e-testing-fleet-server/10/).

I would like to either delete this pipeline entirely or to understand if this is something that the Fleet team intends to revive at some point in the future.

## Fleet E2E pipeline

This is only triggered via a daily job, so far as I can tell. It's unclear to me whether this job is monitored by the product team or whether it serves as a quality gate of any kind. The pipeline is located here: https://beats-ci.elastic.co/job/e2e-tests/job/e2e-testing-fleet-daily-mbp/

As with the above, I would like to either delete this pipeline entirely or to understand if this is something that the Fleet team intends to revive at some point in the future. If there is currently ongoing work to fix it, I would like to have a tracking issue to follow, please.

cc: @joshdover

**Comment by joshdover** [comment]
Let's close this in favor of https://github.com/elastic/elastic-agent/issues/1174
