### ISSUE TITLE
Policy change acknowloedgement does not set the correct value for `packages` which causes kibana filtering to fail if trying to query against this field

### ISSUE THREAD

**Issue by paul-tavares** [elastic/fleet-server#196]
#### Background
In Kibana, when agents are enrolled and running Endpoint, the following KQL filter in the Agents list view is no longer displaying only the agents that are running endpoint integration:

```
packages : "endpoint"
```

![agents-filter-issue-fleet](https://user-images.githubusercontent.com/56442535/113204952-af7f1880-923b-11eb-87d7-d1d1f2ac4da4.gif)

**Comment by paul-tavares** [comment]
@nchaulet can fill in more details if needed. He mentioned a change that was done in Kibana that perhaps has not yet been done in Agent.

**Comment by nchaulet** [comment]
To give a little more context, previously when we were acknowledging a `POLICY_CHANGE` in kibana we were populating the field `packages` of the agent with the packages contained in the policy

**Comment by blakerouse** [comment]
@nchaulet How would fleet-server know that packages that agent is running? Idk if that information is available at the fleet-server level? Seems that maybe that should just be set by Kibana, why would fleet-server need to set that information?

**Comment by mostlyjason** [comment]
There has been some discussion about whether this should be implemented in Kibana or Elastic Agent. It seems like a useful feature to have in Kibana because it could work for any package. We've also discussed  UI designs for integration-specific views that would provide a list of agents. https://github.com/elastic/obs-dc-team/issues/380

@nchaulet @paul-tavares what is the use case for implementing this in Elastic Agent or Fleet Server? Wouldn't this require an extra round trip? It also wouldn't work if Fleet server is offline and Kibana is online.

**Comment by paul-tavares** [comment]
I'll defer to @nchaulet on that, but thinking a little more about this today, I can see why the suggestion is being made to have the Agent or fleet-server populate this information now that we have agent management out of Kibana.

Kibana no longer have the ability to detect when an agent has ack'd a change to the policy _(that is done via fleet-server now)_, so it becomes tricky as to when we update the agents with the list of Package Integrations they are using/running. Attempting to update all Agents in kibana as soon as the Policy is updated/saved:

1. could be a performance issue with large numbers of agents ridding on the policy
2. could provide a false sense of what an agent is actually using because we are doing this ahead of us knowing that the agent has received/applied the new policy

**Comment by ruflin** [comment]
Moving forward, a package will be able to contain multiple integrations and an integration can contain multiple inputs. The Elastic Agent itself only knows about input. In the Endpoint case, package, integration, input are all the same but this is not the usual case.

Taking the above, I think what we are normally interested in is what input is actually running on an Agent and its state. Even if a policy is acked, it could still be that some inputs do not run. An integration could have 2 inputs running, one input not running. Unfortunately input reporting we don't have yet.

How do we get the info? First, I assume today we know which Agent has which policy and if the policy was acked or not. This will allow us to do the following:

* Get all policy ids for policies which contain endpoint integration
* Get all agents which acked this policy id with version x

I would assume the above should not be too bad if the number policies is low. It does not give us the info, which of the agents might still run an older policy with endpoint which was not acked yet.

Lets assume we have input reporting from each Elastic Agent. We query for all elastic agents where the current state contains the endpoint input. This gives us the "mostly" up to date info on what is running on the Agents and is not attached to the policy.

Even if we can't do all the above right now, we should probably focus on reporting the integrations as part of the metadata and not the packages (or packages in addition). Reason is that a package has multiple integrations. Most important for me is that we don't introduce logic around knowing what a package is on the Elastic Agent side.

**Comment by kevinlog** [comment]
> Even if we can't do all the above right now, we should probably focus on reporting the integrations as part of the metadata and not the packages (or packages in addition). Reason is that a package has multiple integrations. Most important for me is that we don't introduce logic around knowing what a package is on the Elastic Agent side.

Is this minimum piece doable before `7.13` @paul-tavares @ruflin @nchaulet

**Comment by nchaulet** [comment]
@michalpristas  @blakerouse do you think it's doable to have the agent report the integrations/packages in the local_metadata for 7.13.0?

**Comment by blakerouse** [comment]
When speaking about this the other day I was of the idea that Elastic Agent should not provide this information, but @ruflin mentions a good point. With capabilities and coordinations it would be really hard for Kibana to know which packages an Elastic Agent is actually running.

Adding this to `local_metadata` would be the best idea. It will need to have this change also in Fleet Server to add this to the index.

**Comment by ruflin** [comment]
I'm a bit concerned that for additional metadata we need to modify the fleet-server. Is this because of a strict mapping? Could we allow some metadata to be free form / all keywords? If we move forward here, it is important that we find a better solution down the road.

**Comment by kevinlog** [comment]
@ruflin

> I'm a bit concerned that for additional metadata we need to modify the fleet-server. Is this because of a strict mapping? Could we allow some metadata to be free form / all keywords?

What's important for us is that we'll be able to use the `AgentService` to pull only Agents with an Endpoint integration/Endpoint installed, etc.  Just want to make sure we could figure that out with whichever solution we go with.  We can update the way we construct our queries in any way.

cc\ @paul-tavares @nchaulet

**Comment by ruflin** [comment]
@kevinlog Based on some more recent discussions, I assume we don't need this at the moment and it can be closed?

**Comment by kevinlog** [comment]
@ruflin yes, we can close
