### ISSUE TITLE
ActionId lost during unenroll at 75k

### ISSUE THREAD

**Issue by pjbertels** [elastic/fleet-server#1977]
With 75k drones up and running towards the end of a test_perf02 test run we requested that all agents be force unenrolled.

FleetAgentStatus(total=75000, inactive=0, online=75000, error=0, offline=0, updating=0, other=0, events=0, doc_id=None, run_id=None, timestamp=None, kuery='local_metadata.host.hostname like eh*', cluster_name=None) 

The actionId we got back was : actionId='5bfc58f2-6c2d-4984-80c2-0cd1a1d92eaa'

Things were progressing slowly and initially 10,000 drones had been unenrolled, sometime later another(15min) 10,000 more drones had been enrolled.  

The whole thing stalled at 55,000 drones left online in the policy.

I dumped the fleet actions and I found that the actionId for the unenroll was not in the returned list. 

Fleet Actions active:

FleetActionStatus(actionId='ea1ce26a-4f18-45d7-a8ed-f90d8aa3e7e8', nbAgentsActionCreated=75000, nbAgentsAck=75021, type='UPGRADE', nbAgentsActioned=75000, status='COMPLETE', expiration='2022-10-07T18:22:10.672Z', creationTime='2022-10-07T17:57:13.268Z', nbAgentsFailed=0, completionTime='2022-10-07T18:18:44.000Z', newPolicyId=None)
FleetActionStatus(actionId='ec036012-be54-495e-b15b-a4b746a98e00', nbAgentsActionCreated=75000, nbAgentsAck=75021, type='POLICY_REASSIGN', nbAgentsActioned=75000, status='COMPLETE', expiration='2022-11-06T17:14:40.137Z', creationTime='2022-10-07T17:14:40.137Z', nbAgentsFailed=0, completionTime='2022-10-07T17:56:08.000Z', newPolicyId='bcb83760-4654-11ed-a2e2-893bb9043f3a')

Cluster details:
TF_VAR_cluster_name=pb85_c52257ee_002 
TF_VAR_cluster_template_id=gcp-io-optimized-v2
TF_VAR_cluster_mem_fleet=24G TF_VAR_cluster_mem_es=128G
TF_VAR_stack_version=8.5.0-SNAPSHOT
TF_VAR_stack_hash=c52257ee

**Comment by kpollich** [comment]
@juliaElastic - Could you provide any insight into why we might be running into this issue where the bulk unenroll action is dropped before the operation completes?

**Comment by juliaElastic** [comment]
I checked the `.fleet-actions` index and the kibana logs, and I don't see the `FORCE_UNENROLL` action anywhere.
@pjbertels do you know around which time the action was taken? I didn't see any specific error in the logs, maybe if we can narrow down the timeframe, I can check again.

**Comment by pjbertels** [comment]
I have not seen this issue since. When the issue occurred things were going very slowly, normally force unenroll is pretty fast. Need to see another instance of this issue to get better debug info.

**Comment by jlind23** [comment]
Closing this for now until further occurence.
