### ISSUE TITLE
[Self-Managed]: Unable to install fleet server using available command.

### ISSUE THREAD

**Issue by amolnater-qasource** [elastic/fleet-server#2059]
Kibana version: 8.6.0 Kibana self-managed environment

Host OS and Browser version: Windows

Build details:
VERSION: 8.6.0 Snapshot Kibana self-managed environment
BUILD: 57997
COMMIT: b78f785b3c25792e1803f7c77512bc38d1a10afa

**Preconditions:**
- 8.6.0 Snapshot Kibana self-managed environment should be available.

**Steps to reproduce:**

1. On fresh Kibana setup navigate to Fleet tab.
2. Create Fleet Server Policy.
3. Select 'Quick start'.
4. Add Fleet-server name and host say `https//10.10.6.10:8220`.
5. Copy the command in the cli.
6. Observe fleet-server is not installed.

**What's not working:**
- User is also unable to install Fleet server using `--insecure` flag.

**Expected Result:**
Fleet-server should be installed using available commands.

**Screenshots:**
![4](https://user-images.githubusercontent.com/77374876/200243471-d7529350-694f-4eef-9722-ee35652b841d.JPG)

![5](https://user-images.githubusercontent.com/77374876/200243479-cb73201e-ceff-4c4b-874c-f74f6fc32d8d.JPG)

**Comment by amolnater-qasource** [comment]
@manishgupta-qasource Please review.

**Comment by cmacknz** [comment]
@michel-laterman or @kpollich does anything seem familiar here? Any ideas what might have caused this?

**Comment by kpollich** [comment]
@nchaulet - Anything with multiple Fleet Server hosts that could've caused this?

**Comment by nchaulet** [comment]
This line in the log seems confusing to me 
<img width="1346" alt="Screen Shot 2022-11-08 at 11 24 21 AM" src="https://user-images.githubusercontent.com/1336873/200620177-3a829784-e4b8-4b33-9bcf-60464acf5e9b.png">

It's possible to get more logs, Kibana logs? and to take a look at what the Fleet server policy looks like?

**Comment by amolnater-qasource** [comment]
Hi @nchaulet 

Thank you for looking into this.

While revalidating this issue on latest 8.6 Snapshot self-managed environment and observed different issue where we are unable to add fleet server integration.

**Build details:**
```
VERSION: 8.6.0 Snapshot Kibana self-managed environment
BUILD: 58097
COMMIT: 8094003b4664dbb5c802d90d3e1bda7422327d1f
```

We have reported separate issue for this at https://github.com/elastic/kibana/issues/144880



Further we will revalidate this issue, once the above shared issue will be fixed.

Thanks

**Comment by jlind23** [comment]
@amolnater-qasource as https://github.com/elastic/kibana/issues/144880 is fixed, could you please retest this one?

**Comment by amolnater-qasource** [comment]
Hi @jlind23 
We have revalidated this issue on latest 8.6 SNAPSHOT Kibana self-managed environment and found it **fixed** now.

**Observations:**
- We are successfully able to install Fleet-Server on self-managed environment.

**Build details:**
BUILD: 58205
COMMIT: 8a34465b29c90aa996ff0c4c65a0539b392640f6

**Screenshot:**
![10](https://user-images.githubusercontent.com/77374876/201605703-e58aeff8-0803-4f7e-bf9e-71ea18144d2f.JPG)

![11](https://user-images.githubusercontent.com/77374876/201605708-8144ef0b-6897-4585-aa5c-78fb34aa2595.JPG)


Hence, we are closing this issue and marking this issue as **QA:Validated**.
Thanks

**Comment by prachigupta-qasource** [comment]
### `Bug Conversion`

- Test-Case not required as this particular checkpoint is already covered in the following testcase:
   - https://elastic.testrail.io/index.php?/cases/view/77071
 
Thanks!
