### ISSUE TITLE
[Fleet] Remove automatic unenrollment of agents

### ISSUE THREAD

**Issue by kpollich** [elastic/fleet-server#2063]
Relates to https://github.com/elastic/kibana/issues/143455

Currently, after agents haven't checked in in a time period greater than the configure "unenrollment timeout," they are automatically "unenrolled" and their API keys are decommissioned. With the work being done in https://github.com/elastic/kibana/issues/143455, this process will no longer be necessary as the filtering of "inactive" agents will become a UI-only concern. We're removing the destructive nature of unenrollment to avoid a broad set of issues that have come up in support cases and elsewhere.

**Comment by jlind23** [comment]
After discussing with @michel-laterman this one is a pretty light one and @hop-dev should be able to take this one too.
