### ISSUE TITLE
[Fleet] checkin fail if the `.fleet-actions` indice do not exists

### ISSUE THREAD

**Issue by nchaulet** [elastic/fleet-server#212]
## Description 

Related to the move to ES system indices, the agent checkin fail if the `.fleet-actions` indice do not exists

```
Could not communicate with Checking API will retry, error: could not decode the response, raw response: elastic fail 404:index_not_found_exception:no such index [.fleet-actions]
```

**Comment by blakerouse** [comment]
This was already fixed in https://github.com/elastic/fleet-server/pull/205.

Be sure you are running from latest master, the SNAPSHOT build is probably out of date.
