### ISSUE TITLE
fleet-server reports lowercase health

### ISSUE THREAD

**Issue by axw** [elastic/fleet-server#2163]
Using the latest 8.6.0 snapshot (https://snapshots.elastic.co/8.6.0-368aeeae/summary-8.6.0-SNAPSHOT.html), fleet-server reports its health status as lowercase. In 8.5 it was uppercase, then it was changed inadvertently with the Agent v2 changes; subsequently fixed, then regresse; then supposed to have been fixed again in https://github.com/elastic/fleet-server/pull/2159. Alas, it is still lowercase.

You can confirm this by running the linked snapshot. If you prefer, pull https://github.com/elastic/apm-server/pull/9746 and run `docker-compose up -d` -- fleet-server will not become healthy. Then try `curl -k https://localhost:8220/api/status`, and you'll see that it's lowercase.

**Comment by axw** [comment]
Maybe a false alarm, the latest snapshot build failed, so this one is a bit stale:

```
$ docker run --rm --entrypoint=/bin/tini docker.elastic.co/beats/elastic-agent:8.6.0-368aeeae-SNAPSHOT -- cat ./data/elastic-agent-362d2b/components/fleet-server > /tmp/fleet-server && chmod 755 /tmp/fleet-server && go version -m /tmp/fleet-server | grep vcs
        build   vcs=git
        build   vcs.revision=d5a77f9b323bcda78a7eb7f2ac3b99ffaa4c9c9b
        build   vcs.time=2022-12-02T05:38:40Z
        build   vcs.modified=false
```

**Comment by jillguyonnet** [comment]
Probably a false alarm, I am unable to reproduce this with the mentioned and subsequent versions.
