### ISSUE TITLE
APM and fleet settings failed on upgrade from 7.17.8>8.6.0

### ISSUE THREAD

**Issue by sukhwindersingh-qasource** [elastic/fleet-server#2164]
**Deployment Links:**

-  https://cloud.elastic.co/home

**Description:**

- APM and fleet settings failed on upgrade from 7.17.8 BC-2 >8.6.0 BC-5.

- Build gets into unhealthy state.

- No latest version Hosted fleet server is available.

**Build details of upgraded 8.6.0:**

```
VERSION: 8.6.0
BUILD: 58693
COMMIT: ed40c16ce9999cc47ad55c11bb097d2e443b31a6
```

**Screen-Shots**
![new1](https://user-images.githubusercontent.com/108654988/205854762-857b26a9-e7f7-48d4-9581-fe2b47b625ea.jpg)
![new2](https://user-images.githubusercontent.com/108654988/205854779-22fe8cb1-7e32-4da3-9795-e84e85ce6246.jpg)
![new3](https://user-images.githubusercontent.com/108654988/205854807-11c70827-47db-4a62-aa98-7deb4c7ab9be.jpg)

**Comment by sukhwindersingh-qasource** [comment]
@amolnater-qasource Please review

**Comment by amolnater-qasource** [comment]
Secondary review for this ticket is Done

**Comment by jen-huang** [comment]
Thank you for the bug report, we discovered this a few days ago and are tracking the work here: https://github.com/elastic/ingest-dev/issues/1437

Closing this one as a dupe.

**Comment by prachigupta-qasource** [comment]
### `Bug Conversion:`

We have updated **01 testcase** for this scenario in our fleet test suite at:
  - https://elastic.testrail.io/index.php?/cases/view/34209

Thanks
