### ISSUE TITLE
CPU usage up to 100% without traffic

### ISSUE THREAD

**Issue by simitt** [elastic/fleet-server#220]
A docker setup with Elastic Agent w. Fleet Server was running for some time without any traffic or additional agents. After some time, when uninstalling the Elastic Agent with the Fleet Server, the CPU usage for the `cgroup` containing the Fleet Server went up to `100%` and `fleet-server.logs` showed following:
```
{"log.level":"info","ctx":"policy leader manager","policy_id":"8819e7e0-9702-11eb-9afd-e7f5dd2ccc4d","coordinator":"v0","@timestamp":"2021-04-12T17:21:10.313Z","message":"starting coordinator for policy"}
{"log.level":"info","ctx":"policy leader manager","policy_id":"881ef0f0-9702-11eb-9afd-e7f5dd2ccc4d","coordinator":"v0","@timestamp":"2021-04-12T17:21:10.311Z","message":"starting coordinator for policy"}
{"log.level":"info","ctx":"policy leader manager","policy_id":"881ef0f0-9702-11eb-9afd-e7f5dd2ccc4d","coordinator":"v0","@timestamp":"2021-04-12T17:21:10.315Z","message":"starting coordinator for policy"}
{"log.level":"info","ctx":"policy leader manager","policy_id":"8819e7e0-9702-11eb-9afd-e7f5dd2ccc4d","coordinator":"v0","@timestamp":"2021-04-12T17:21:10.314Z","message":"starting coordinator for policy"}
```

What is shown as `APM Server Usage` is actually the `cgroup` container usage (stack monitoring changes addressing the title change are not yet merged):
<img width="1760" alt="Screenshot 2021-04-12 at 19 23 47" src="https://user-images.githubusercontent.com/5555349/114435899-0504df00-9bc5-11eb-9a4e-3bff66c8b510.png">

Observed on latest running `7.13` snapshot.

**Comment by ph** [comment]
@aleksmaus or @blakerouse any idea here? is that something to worry about?

**Comment by simitt** [comment]
> is that something to worry about?

From a cloud/apm perspective this is pretty much worse case scenario, as the fleet-server would consume all available CPU.

**Comment by ruflin** [comment]
Pinging @scunningham as he might be able to help. Agree, this is a worst case scenario for APM on Cloud.

**Comment by scunningham** [comment]
Looks like a bug.  @simitt can. you reproduce?

**Comment by aleksmaus** [comment]
possible tight loop on shutdown: https://github.com/elastic/fleet-server/blob/b70022150cf4d9c22b2caacff41c7ffdd4256ab2/internal/pkg/coordinator/monitor.go#L370
can take a look now

**Comment by aleksmaus** [comment]
it's possible there could be a couple of issues
1. the tight loop that caused the logging and 100% spike
2. fleet server not exiting for some other reason
The PR takes care of the loop.
@simitt what is the best way to retest it in your setup?

**Comment by simitt** [comment]
I started the elastic-agent container with:
```
docker run -it \
--env ELASTIC_AGENT_CLOUD=true \
--env APM_SERVER_PATH=/myapp/apm-server/ \
--env STATE_PATH=/myapp/elastic-agent \
--env CONFIG_PATH=/myapp/config \
--env LOGS_PATH="/myapp/logs" \
--env HOME_PATH="/myapp" \
-p 8200:8200 -p 8220:8220 -p 5066:5066 \
-v ~/coding/myapp:/myapp --rm docker.elastic.co/beats/elastic-agent:7.13.0-SNAPSHOT
```
setting Kibana and ES endpoints and credentials accordingly and using the `config/fleet-setup.yml`: 
```
fleet:
  enroll: true
  force: true
  insecure: true
fleet_server:
  enable: true
  host: "0.0.0.0" 
  insecure_http: true
kibana:
  fleet:
    setup: true
```
