### ISSUE TITLE
Certificate error occurred when installing the fleet server

### ISSUE THREAD

**Issue by lovelike123** [elastic/fleet-server#2201]
My Elasticsearch and Kibana versions are 8.5.0. When installing the fly, certificate errors are reported all the time. 
Adding -- insert or --fleet-server-es-insecure doesn't even work
This is the time of installation
![image](https://user-images.githubusercontent.com/46017757/208804904-214ae49c-4514-483b-9fc6-89c0d6d95cff.png)
![image](https://user-images.githubusercontent.com/46017757/208805185-4f4e6cb6-4c50-43fb-a357-647870bbb65f.png)
This is officially given
![image](https://user-images.githubusercontent.com/46017757/208805099-ba177be7-8fda-41e9-a654-391249081320.png)

**Comment by michel-laterman** [comment]
Are you still having issues?

**Comment by jlind23** [comment]
Hasn't been updated in a while hence closing as outdated. Feel free to reopen it if required.
