### ISSUE TITLE
Duplicate agents can be created during enrollment at scale

### ISSUE THREAD

**Issue by joshdover** [elastic/fleet-server#2254]
- Version: Likely all versions
- Steps to Reproduce: 
1. Enroll a high number of agents at once against a Fleet Server instance, must be more agents than the Fleet Server can handle, triggering rate limiting
2. Observe that there may be some duplicate agents, with some stuck in "updating" state

![image](https://user-images.githubusercontent.com/1813008/210748748-a9c9e418-dc82-4b24-8afe-c078a10061b8.png)

This can happen because the first attempt to enroll appears to fail from the Agent's perspective (eg. due to a request timeout), but Fleet Server already created a new agent record. The agent then retries the enrollment, creating a new agent record (and ID) for the same hostname, resulting in duplicate agents in the UI. Because the first agent ID was never checked in, the first agent will stay in "updating" state.

Ideally, this is automatically detected or prevented by Fleet Server somehow. In the meantime, the [inactivity timeout feature](https://github.com/elastic/kibana/issues/143455) should phase these duplicates out of the default UI views after some time.

Note: we have not actually verified this happens with real Agents yet, only with Horde-emulated agents.

**Comment by joshdover** [comment]
I only see a few options forward on this right now, hoping someone else has some better ideas:
1. We make the test harness tolerant to this by ignoring duplicate agents that didn't checkin
2. We attempt to make Fleet Server smart enough to rollback an agent if the client drops the connection before the response is sent
	- This will not be 100% foolproof since the client may drop / timeout the connection after the server has written the response but before the packets have arrived at the agent
3. We enhance Fleet Server to be able to match a second enrollment for the same agent to a previous record
	- This has some overlap with https://github.com/elastic/ingest-dev/issues/1280
	- It's important that this cannot be used to "hijack" an agent that is already in use
	- We could scope this to something simple and low-risk for now, such as:
		- On agent enrollment, first see if another agent document exists with the same hostname and mac address
		- If that agent has not yet checked in, revoke the access API key and generate a new one for the second enrollment attempt
	- This would minimize the window of time that an agent could be hijacked, since it's only possible if the agent enrolled but never checked in. After the first checkin, the system would generate a new agent instead. 
	- This could cause issues if you're enrolling a lot agents with the same hostname and mac address at the same time. This is probably not very likely, but should be documented if we go this route.

**Comment by cmacknz** [comment]
The agent can safely be stateful. The agent could generate a UUID / idempotency token for the enrolment request and then write it to disk in a known location relative to the install path before it makes the network request to enrol. 

Then every subsequent request would use that same UUID, and if we include it in the enrolment request subsequent retries won't create new agents.

**Comment by joshdover** [comment]
Interesting that could work. I think the key here is that the enrollment UUID is distinct from the Agent ID. This prevents someone from trying to masquerade as a specific Agent since the enrollment ID won't be as easily accessible in the Fleet UI or Fleet Server URLs. It's completely in our control.

We could also use this to during re-installs/enrolls of the agent when using the `-f` flag. We'd first grab the enrollment ID from disk, uninstall the old agent, and then install/enroll the new one using the same UUID.

@ferullo do you have any concerns with this approach from the endpoint side?

**Comment by juliaElastic** [comment]
Does it sound feasible to do this in horde to fix the flakiness scalability tests?

**Comment by juliaElastic** [comment]
I found a [SharedId](https://github.com/elastic/fleet-server/blob/fd966720f8eb4bed63c7029d0252963ee25b7cf8/internal/pkg/api/handleEnroll.go#L135) field in [fleet-server](https://github.com/elastic/fleet-server/blob/fd966720f8eb4bed63c7029d0252963ee25b7cf8/model/openapi.yml#L138) that is also there in the [fleet-agents index](https://github.com/elastic/elasticsearch/blob/main/x-pack/plugin/core/src/main/resources/fleet-agents.json#L220) which seems to be intended as an id to reuse for the same agent enrollment. I think we can reuse that.

**Comment by cmacknz** [comment]
I think the solution here should also address the request in https://github.com/elastic/elastic-agent/issues/1277, so linking it here.

**Comment by cmacknz** [comment]
> It doesn't solve some of the use cases in the linked issue where the re-enrollment would be used as a corrective action for an agent that was checking in before. There were concerns about a potential vulnerability if we allowed overriding/deleting a healthy agent.

I do agree that this introduces another way for the agent API key to invalided or leaked (if we just returned the value for the previous agent instead of replacing it), but you would need both the enrollment token and the enrollment ID (like to be owned by root in the agent's encrypted store). If you can get access to both of those likely the agent is already compromised on the host.

That said we can leave handling https://github.com/elastic/elastic-agent/issues/1277 as a future revision of this implementation, it is really a feature request. What is in the current PR solves the bug where valid retries create duplicate agents, which is more of a bug fix and we can limit the scope initially.

**Comment by cmacknz** [comment]
I created https://github.com/elastic/elastic-agent/issues/2820 for the agent side of this implementation, separate from https://github.com/elastic/elastic-agent/issues/1277

**Comment by juliaElastic** [comment]
Merged the fleet-server and horde prs.
Pending: when the new fleet-server snapshot is ready, deploy the leatest version of horde on gke clusters, to have the new version running.

**Comment by juliaElastic** [comment]
Applied the latest horde change to the oblt perf clusters and ran a successful 10k build.
100k run in progress.

**Comment by joshdover** [comment]
I think this happened again in the latest 100k build: https://buildkite.com/elastic/observability-perf/builds/1266#01896657-f0d7-40ff-8723-fe801e88ba67

Any idea on this one, @juliaElastic?

**Comment by juliaElastic** [comment]
@joshdover I had a look and all drones have enrollment_id, but interestingly 2 drones have the same one, so it looks like the fix is not perfect.
```
GET .fleet-agents/_search?q=enrollment_id:*
{
    "track_total_hits": true,
    "size": 0,
    "aggs": {
        "enrollment_id": {
            "terms": {
                "field":"enrollment_id"
            }
        }
    }
}


200 — OK (291 ms)

{
  "took": 82,
  "timed_out": false,
  "_shards": {
    "total": 1,
    "successful": 1,
    "skipped": 0,
    "failed": 0
  },
  "hits": {
    "total": {
      "value": 100001,
      "relation": "eq"
    },
    "max_score": null,
    "hits": []
  },
  "aggregations": {
    "enrollment_id": {
      "doc_count_error_upper_bound": 0,
      "sum_other_doc_count": 99990,
      "buckets": [
        {
          "key": "6jey2JtwRMMtcA5e9VZLmL",
          "doc_count": 2
        },
        {

```
