### ISSUE TITLE
Upgrade from version 8.5 to 8.6 - license error 

### ISSUE THREAD

**Issue by thiavscapital** [elastic/fleet-server#2270]
After updating from version 8.5 to 8.6, my fleet server does not work, I cannot see my agents online, in the logs I have the following situation:

   Reason: current license is non-compliant for [categorize-text-agg]","log":{"level":"ERROR","logger":"plugins.fleet"}

My license is basic

Has anyone ever experienced this? do you know how to fix?

**Comment by cmacknz** [comment]
I'm not sure this is a bug in fleet server itself, that log looks to be coming from the Fleet plugin in Kibana.

For the fleet-server error we would logs from fleet-server itself or ideally the archive output from `elastic-agent diagnostics collect` for the elastic-agent that is running fleet-server.

**Comment by UchihaYuki** [comment]
I upgrade from 8.1.2 to 8.6, but I didn't pay attention to logs before. I run the official docker container. In the docker logs, I see this line keeps repeating itself:
```
[2023-01-31T04:34:22.853+00:00][ERROR][plugins.fleet] Error occurred while sending Fleet Usage telemetry: ResponseError: security_exception: [security_exception] Reason: current license is non-compliant for [categorize-text-agg]
```
I run elastic agent in standalone mode. Is there anything I should do to make this error disappear?

**Comment by jlind23** [comment]
This categorize text aggregation has been removed in the meantime hence closing.
