### ISSUE TITLE
Problem while installing fleet server (elastic-agent)

### ISSUE THREAD

**Issue by Sirajbu** [elastic/fleet-server#2278]
Please see the screenshot to understand the error I am facing.

![image](https://user-images.githubusercontent.com/76399469/212754091-aa35d39a-5992-49ed-a728-f85ffc30a15c.png)

Any solution would help greatly. Thanks in advance!

**Comment by michel-laterman** [comment]
Sorry for the late response,

Generally for issues like this the [discuss forums](https://discuss.elastic.co/) should be used.
Are you still having an issue?

**Comment by jlind23** [comment]
Closing this as outdated, will reopen if required.
