### ISSUE TITLE
Automatically choose a default load limit present based on available memory

### ISSUE THREAD

**Issue by joshdover** [elastic/fleet-server#2308]
Related to:
- https://github.com/elastic/fleet-server/issues/1860
- https://github.com/elastic/fleet-server/issues/1857

We want to make scaling Fleet Server easy and stable, for both end users and scale testing purposes. Automatically configuring as much as possible will help our scale tests to more accurately reflect what a typical user will see in production when using Fleet Server on Cloud or on-premise.

In addition, this configuration setting is hard to set because it's on a per-instance basis, while customers tend to think about the size of their entire Fleet. We have no way to automatically determine how many instances are running in order to calculate the per-instance agent count.

### Requirements
- When "max agents" config is not set, Fleet Server should be able to use most of available resources in order to maximize the number of agents it can serve and how 
- When "max agents" is set, we should not automatically calculate any load limits. The purpose of this is to either:
	1. Support mixed APM Server / Fleet Server uses cases on Cloud where these processes share a single container. If the user has high APM usage, they may desire to throttle the amount of resources (mostly memory) that Fleet Server will use and this is the only knob we currently have.
	2. If Fleet is putting too much load on Elasticsearch, this knob is an easy way to turn down that traffic without having to set each individual rate limit setting.
- We should not assume that the entire memory space is available just for Fleet Server, because we need to be sure that we can run a minimal APM Server, Metricbeat, and Filebeat in the same container for metric and logs collection. We should ensure that the presets already take this into account.

**Comment by michel-laterman** [comment]
This should not be too complex to do, we can alter our limit loading to work on mem size if agents is not set:
https://github.com/elastic/fleet-server/blob/25be4e26e479b0263d4499ecf8123bf082901a88/internal/pkg/config/env_defaults.go#L187-L204
