### ISSUE TITLE
Upgrade to go1.20

### ISSUE THREAD

**Issue by joshdover** [elastic/fleet-server#2330]
Go 1.20 offers an optimization which may have a very large impact on Fleet Server's memory footprint:

> Parsed certificates are now shared across all clients actively using that certificate. The memory savings can be significant in programs that make many concurrent connections to a server or collection of servers sharing any part of their certificate chains.

This is especially pertinent as we're building out our Fleet Service and trying to decide on autoscaling and sizing. Reducing the memory footprint could allow us to serve many more agents with the same amount of memory.

**Comment by joshdover** [comment]
Reading again, this may only impact outbound connections and not inbound ones so this may not help us. It will need investigation.

**Comment by michel-laterman** [comment]
Either way, upgrading to 1.20 is desired as 1.18 will no longer be patched

**Comment by michel-laterman** [comment]
Done in https://github.com/elastic/fleet-server/pull/2482
