### ISSUE TITLE
[Inconsistent]: Fleet Server gets stuck in Updating and then goes to Offline state on installation.

### ISSUE THREAD

**Issue by amolnater-qasource** [elastic/fleet-server#2336]
**Kibana version:**  8.7 BC1 kibana cloud environment

**Host OS and Browser version:** All, All

**Build details:**
```
VERSION: 8.7 BC1
BUILD: 60614
COMMIT: d3b239d76aa04f073836f6100782134ac86887e2
```

**Preconditions:**
1. 8.7 BC1 kibana cloud environment should be available.

**Steps to reproduce:**
1. Navigate to Fleet>Add Fleet Server.
2. Add Fleet Server host url: `https://public-ip:8220`
3. Install fleet server using created Fleet Server policy.
4. Observe fleet server gets stuck in updating state and later goes to offline state.

**Note:**
- This issue is observed inconsistently several times on different OS's.
- We are also successfully able to run fleet server without any errors inconsistently.

**Expected Result:**
Fleet Server should get healthy under agents tab on installation.

**Screenshots:**
![3](https://user-images.githubusercontent.com/77374876/218371819-2cbaa520-1347-45e9-9d41-34b46e627b2b.JPG)
![4](https://user-images.githubusercontent.com/77374876/218371823-8cd10a95-cbb5-4b97-bfc2-66592b555505.JPG)
![5](https://user-images.githubusercontent.com/77374876/218372604-d2db34ea-b6bd-40a1-b742-88c0b1afb746.JPG)
![6](https://user-images.githubusercontent.com/77374876/218371827-76c7ad95-d724-4049-ab7a-06a5b6b351dc.JPG)
![7](https://user-images.githubusercontent.com/77374876/218371830-1552035b-d0f1-4ad3-8d5e-2244a9c934c5.JPG)
![8](https://user-images.githubusercontent.com/77374876/218371834-78f884e7-2538-479d-8f10-974841449693.JPG)

**Logs:**
[elastic-agent-diagnostics-2023-02-12T20-04-12Z-00.zip](https://github.com/elastic/fleet-server/files/10718755/elastic-agent-diagnostics-2023-02-12T20-04-12Z-00.zip)

**Comment by amolnater-qasource** [comment]
@manishgupta-qasource Please review.

**Comment by manishgupta-qasource** [comment]
Secondary review for this ticket is Done

**Comment by jlind23** [comment]
@kpollich @michel-laterman Could you please take a look at this one?
@amolnater-qasource @manishgupta-qasource be aware that fleet-server rather belong to the fleet and integrations area.

**Comment by michel-laterman** [comment]
With a brief look at the logs included we can see that the agent is sending a sigterm to fleet-server; that's why the agent is unable to checkin after.
```
{"log.level":"info","@timestamp":"2023-02-12T20:01:59.115Z","message":"On signal","component":{"binary":"fleet-server","dataset":"elastic_agent.fleet_server","id":"fleet-server-default","type":"fleet-server"},"log":{"source":"fleet-server-default"},"sig":"terminated","ecs.version":"1.6.0","service.name":"fleet-server","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2023-02-12T20:01:59.118Z","log.origin":{"file.name":"coordinator/coordinator.go","file.line":861},"message":"Component state changed fleet-server-default (HEALTHY->STOPPED): Stopped: pid '3295' exited with code '0'","log":{"source":"elastic-agent"},"component":{"id":"fleet-server-default","state":"STOPPED","old_state":"HEALTHY"},"ecs.version":"1.6.0"}
```
However we can't see why the agent is stopping the fleet-server, can you please try to run with debug logs enabled?

**Comment by amolnater-qasource** [comment]
Hi @michel-laterman 

Thank you for looking into this issue.
We have attempted to reproduce this issue for fetching fleet-server debug logs on 8.7.0 BC1, however in multiple attempts we are unable to reproduce this again due to shared inconsistency.

**Screenshot:**
![16](https://user-images.githubusercontent.com/77374876/219281230-aa715222-2b2b-4235-af54-f7ae0efea7aa.JPG)


Please let us know if we can close this issue for now and we can track it on future builds.

Thanks

**Comment by jlind23** [comment]
@amolnater-qasource Thanks for letting us know. Closing for now and we will reopen if another occurence appears.
