### ISSUE TITLE
Should prevent install on x86 systems and/or show helpful error message from Fleet Server usage if attempted

### ISSUE THREAD

**Issue by amolnater-qasource** [elastic/fleet-server#234]
**Kibana version:** 8.0 Snapshot Kibana cloud environment

**Host OS and Browser version:** Windows 7 x32, All

**Build Details:**
```
  Artifact link used: https://snapshots.elastic.co/8.0.0-c711755c/downloads/beats/elastic-agent/elastic-agent-8.0.0-SNAPSHOT-windows-x86.zip
  Build: 41953
  Commit: cb3c4e3a212255a9e9b8c89e784e0e452b661233
```

**Preconditions:**
1. 8.0 Snapshot Kibana cloud environment should be available.

**Steps to reproduce:**
1. Login to Kibana environment.
2. Run Fleet server install command on windows powershell.
3. Observe repetitive Fleet-Server Starting, Restarting errors.

**Expected Result:**
Appropriate error message should be thrown when the detected OS is not supported by Fleet Server.

**Screenshots:**
![7](https://user-images.githubusercontent.com/77374876/114700125-bed38b00-9d3e-11eb-80ca-d51939a9eebd.JPG)

**Comment by karanbirsingh-qasource** [comment]
Reviewed and assigned to @EricDavisX

**Comment by EricDavisX** [comment]
I think we have documented this at least minimally that it is not recommended - but we can leave it open as a note for users to find if / when they search.  If an x86 machine has enough memeory to run FS / stack and they wish to do so, I think it is ok to let them try / use it for whatever purpose they seek.  We need not 'fix' the access to this further.  

x86 architectures with Fleet Server is confirmed as not being a supported environment so we are not obligated to fix problems that do arise, but if it works, it is ok for it it work.

**Comment by dikshachauhan-qasource** [comment]
hi @EricDavisX 

Thanks for the feedback.

Further, as currently x86 artifacts availability after 7.13 has been stopped [Refer: https://github.com/elastic/beats/issues/25533#issuecomment-870777973], so above scenario will not be valid now.

Screenshot:
![image](https://user-images.githubusercontent.com/72375798/131470512-8f968110-4a18-4b4d-a895-927884f90471.png)


Thanks
QAS
