### ISSUE TITLE
Add CI pipeline to publish docker images for standalone mode

### ISSUE THREAD

**Issue by jsoriano** [elastic/fleet-server#2352]
Once https://github.com/elastic/fleet-server/issues/2294 is ready, add a pipeline to publish docker images.

These docker images should be published on each commit on `main` by now.

**Comment by joshdover** [comment]
A couple of notes about requirements here:
- We don't need this image to be public, but it's ok if it is. It should be clear though that this is not a supported artifact for customers to deploy.
- We should publish a new image on each commit to main and tag it with `latest`
- We should publish a new image on each git tag push
- We should use the same base image we use for elastic-agent's image

**Comment by alexsapran** [comment]
[ cross-posting from #2359 ]
We discussed this with @joshdover.

We could use the [internal docker registry](https://github.com/elastic/infra/blob/master/docs/container-registry/accessing-the-docker-registry.md?rgh-link-date=2023-02-21T11%3A27%3A07Z) and publish the container image under the employee's path.

After some quick searching in GH I noticed how it's done in [endpoint-dev repo for some dockery-related builds](https://github.com/elastic/endpoint-dev/blob/46819ce5fce831cf6fddd2d8561d6e6a3b4d6133/Containers/Makefile#L7), setting an NS (namespace) to docker.elastic.co/employees/ instead of docker.elastic.co/.

**Comment by jsoriano** [comment]
> We could use the [internal docker registry](https://github.com/elastic/infra/blob/master/docs/container-registry/accessing-the-docker-registry.md?rgh-link-date=2023-02-21T11%3A27%3A07Z) and publish the container image under the employee's path.

These images are going to be used in the production service, we souldn't use an employee's path.

In https://github.com/elastic/fleet-server/pull/2359 I am using `docker.elastic.co/elastic-agent/fleet-server`, but I am fine with changing this name. Maybe another option would be to use `docker.elastic.co/fleet-server/fleet-server`.

**Comment by jlind23** [comment]
@mrodm could you make a high priority on your end as this is needed for the fleet service project. Anything we can do to help you here?

**Comment by mrodm** [comment]
@jlind23 :+1: 
to avoid any possible blockers or issues, I was thinking to do it for the time being with Jenkins CI pipelines.

As mentioned here, I'll check the pipelines and Makefile to use the URL mentioned in https://github.com/elastic/fleet-server/issues/2352#issuecomment-1455872594
`docker.elastic.co/elastic-agent/fleet-server` , ok ? @jsoriano @joshdover

**Comment by jlind23** [comment]
@mrodm sounds good to me.

**Comment by jsoriano** [comment]
> to avoid any possible blockers or issues, I was thinking to do it for the time being with Jenkins CI pipelines.

++

> As mentioned here, I'll check the pipelines and Makefile to use the URL mentioned in [#2352 (comment)](https://github.com/elastic/fleet-server/issues/2352#issuecomment-1455872594)
> `docker.elastic.co/elastic-agent/fleet-server` , ok ?

Would `docker.elastic.co/fleet-server/fleet-server` require additional effort? (Thinking about decoupling fleet-server from elastic-agent, though both options sgtm).

**Comment by joshdover** [comment]
I don't have a strong opinion on naming but would prefer we don't publish this publicly at this time.
