### ISSUE TITLE
[Linux .deb and .rpm]: No System integration Data displayed under Data Streams tab for agent enrolled with Fleet Server URL

### ISSUE THREAD

**Issue by amolnater-qasource** [elastic/fleet-server#236]
**Kibana version:** 8.0 Snapshot Kibana cloud environment

**Host OS and Browser version:** Centos 7.5 and Debian 9, All

**Build Details:**
```
  Artifact link used: https://snapshots.elastic.co/8.0.0-c711755c/downloads/beats/elastic-agent/elastic-agent-8.0.0-SNAPSHOT-x86_64.rpm
  Build: 41953
  Commit: cb3c4e3a212255a9e9b8c89e784e0e452b661233
```

**Preconditions:**
1. 8.0 Snapshot Kibana cloud environment should be available.
2. Fleet server must be setup for Centos and Debian.
3. Enroll .rpm and .deb agents with default policy having System and Endpoint Security integrations using respective Fleet Server url.

**Steps to reproduce:**
1. Login to Kibana environment.
2. Navigate to agent "Logs" tab.
3. Observe no Logs.
4. Navigate to "Data Streams" and observe no data for System

**Expected Result:**
Data should stream for integrations in default policy under Data Streams tab when agent is enrolled using Fleet Server URL.

**Screenshots:**
![Data and Logs](https://user-images.githubusercontent.com/77374876/114704600-6c956880-9d44-11eb-9b73-e525b6cfdbeb.jpg)

**Comment by karanbirsingh-qasource** [comment]
Reviewed and assigned to @EricDavisX

**Comment by EricDavisX** [comment]
hi - i used a deb Agent install against a working Fleet Server:

zeus@mainqa-atlcolo-10-0-6-185:~$ sudo elastic-agent enroll -f --url=https://1.0.0.1:8220 --enrollment-token=asdf1234asf1234== --insecure

![Screen Shot 2021-04-21 at 5 43 02 PM](https://user-images.githubusercontent.com/12970373/115625291-d7f1b400-a2c9-11eb-9eb9-e165b3464e33.png)

I then 'unenrolled it' from the Fleet UI and then back on the CLI enrolled it as a Fleet Server:

sudo elastic-agent enroll -f --fleet-server-es=https://elastic:adfadfasdf@adsfasdf.us-central1.gcp.foundit.no:443 --fleet-server-policy=adf-asdf-adf-adsf-asdf

and this worked immediately to stand up fleet server - so i think we have working product and can close out a few tickets, including this one.  there are other bugs for sure, so be on the look out.  :)
