### ISSUE TITLE
Revert long poll default to ~10 minutes for 8.8 only

### ISSUE THREAD

**Issue by jlind23** [elastic/fleet-server#2387]
In this issue https://github.com/elastic/fleet-server/issues/2337 we changed the default value for the long poll to 30 minutes. It has to be changed back to 10 minutes for 8.8 only.

This has to be done on the 8.8 branch as soon as it is created.

**Comment by michel-laterman** [comment]
As we discussed this revert may be more permanent then just the 8.8 release as the duration changes will introduce unwanted behaviour in older agent versions. We should keep the discussion in #2337
