### ISSUE TITLE
[Fleet] Investigate Fleet Server stuck in `Updating` status when output is unreachable during stack upgrade in ECK

### ISSUE THREAD

**Issue by kpollich** [elastic/fleet-server#2442]
Attempt to reproduce an issue from an SDH wherein the Fleet Server policy's output was erroneously set to `localhost:9200`, the user upgrade from 8.4 to 8.6, and observed their Fleet Server agent was stuck in `Updating` until they fixed the output and provided a new certificate authority.

Try to determine whether there are any ECK specific oddities that could cause this issue to break the Fleet Server agent's status reporting.

**Comment by jlind23** [comment]
Closing this as outdated, will reopen if required.
