### ISSUE TITLE
[Fleet] Improve error message for expired certificate authority

### ISSUE THREAD

**Issue by kpollich** [elastic/fleet-server#2447]
Currently, providing an expired certificate authority for Fleet Server, Logstash, etc will report a generic `Unknown Certificate Authority` error. It'd be ideal if we could detect the expiration case explicitly and provide a more specific error message.

**Comment by kaanyalti** [comment]
Created this PR that shows that the error message mentioned in this issue is most probably not due to an expired CA. 

https://github.com/elastic/fleet-server/pull/3423/files

**Comment by kpollich** [comment]
Thanks Kaan, that PR demonstrates the specific error cases well. Appreciate you creating it and investigating here 🙏

The error messages in question come from Go's HTTP internals, and as such we don't really have a way to replace or improve them. I'm going to close this as not planned as a result.
