### ISSUE TITLE
[Deployment]: Hosted fleet server is not available under Agents tab for 8.8 SNAPSHOT.

### ISSUE THREAD

**Issue by amolnater-qasource** [elastic/fleet-server#2479]
**Deployment Links:**
- https://staging.found.no/
- https://cloud.elastic.co/

**Description:**
- Hosted fleet server is not available under Agents tab.

**Screenshots:**
![image](https://user-images.githubusercontent.com/77374876/230847358-82066c0a-a51c-4618-a7b4-1bdc1da93334.png)
![image](https://user-images.githubusercontent.com/77374876/230847410-def60b4e-602f-40e6-8315-42537547580d.png)
![image](https://user-images.githubusercontent.com/77374876/230847475-a62d885f-49a4-42c3-b37e-a9afb4c26d94.png)

**Comment by amolnater-qasource** [comment]
@manishgupta-qasource Please review.

**Comment by manishgupta-qasource** [comment]
Secondary review for this ticket is Done

**Comment by juliaElastic** [comment]
Facing the same issue today with the latest snapshot: https://admin.found.no/deployments/f9376976c7dd3875d0bc6a8a2843a437/integrations_server

**Comment by jlind23** [comment]
@juliaElastic on your deployment I can see some `"message":"service_token is undefined accessing config"`
Looks like it failed getting a service token, any logs on ES end that we can use?

**Comment by juliaElastic** [comment]
@jlind23 I don't see related issue in ES logs: https://logging.us-west2.gcp.elastic-cloud.com/app/discover#/?_a=h@01ea9a0&_g=(filters:!(('$state':(store:globalState),meta:(alias:!n,disabled:!f,index:'cluster-elasticsearch-*',key:input_type,negate:!f,params:(query:elasticsearch,type:phrase),type:phrase,value:elasticsearch),query:(match:(input_type:(query:elasticsearch,type:phrase)))),('$state':(store:globalState),meta:(alias:!n,disabled:!f,index:'cluster-elasticsearch-*',key:ece.cluster,negate:!f,params:(query:'967f0274c0194b60a35399b002fa037b',type:phrase),type:phrase,value:'967f0274c0194b60a35399b002fa037b'),query:(match:(ece.cluster:(query:'967f0274c0194b60a35399b002fa037b',type:phrase))))),refreshInterval:(display:Off,pause:!f,value:0),time:(from:now-24h,mode:quick,to:now))

**Comment by jlind23** [comment]
We might need @michel-laterman help here 🤐

**Comment by joshdover** [comment]
Let's be sure to test our changes before merging with the new scripts for building and deploying a custom image: https://github.com/elastic/fleet-server/blob/main/dev-tools/cloud/docker/build.sh

**Comment by michel-laterman** [comment]
I'll remove the validation segment from the changes; I think what's happening is that for cloud deployments we use username:password to gather a service token and the validation occurs before then

**Comment by harshitgupta-qasource** [comment]
### `Bug Conversion`

- Test-Case not required as this particular checkpoint is already covered in the following testcase:
   - https://elastic.testrail.io/index.php?/cases/view/149907
 
Thanks!
