### ISSUE TITLE
[E2E][Cloud] Spin up a cloud stack on cloud testing region and make sure an Hosted Fleet server is available

### ISSUE THREAD

**Issue by jlind23** [elastic/fleet-server#2484]
In fleet server repository, a new test should be added, this test will:
- [ ] Run on every PR as a mandatory step
- [ ] Build Fleet server with the latest Elastic Agent image
- [ ] Use this specific image built to trigger a deployment
- [ ] This deployment should be done on a Cloud First Testing region
- [ ] Fleet Server should be running and healthy after this deployment
- [ ] Tear down and clean up

**Comment by jlind23** [comment]
PR Artifacts won't be available on staging, you have to have until it is pushed to the registry. Having this test run on a daily basis might be a better option.
cc @kpollich

**Comment by kpollich** [comment]
Daily run makes sense here

**Comment by jlind23** [comment]
@nchaulet is this something you can take on? It looks like using the CFT script that you did should be automated in CI, what do you think?

**Comment by jlind23** [comment]
@nchaulet let me update the description accordingly in order to give more guidance. Thanks.
