### ISSUE TITLE
Upgrade action sometimes leaves agent in Updating state

### ISSUE THREAD

**Issue by juliaElastic** [elastic/fleet-server#2519]
While investigating the issue of some horde drones converging slowly during an upgrade, encountered an issue where a few drones were left in Updating state indefinitely (no change in a few hours).

When looking at the logs, I saw that the action was delivered, and during ack it encountered an error when writing out action result (temporary connection issue with ES): https://github.com/elastic/fleet-server/blob/main/internal/pkg/api/handleAck.go#L323

It seems that when hitting this error, the upgrade action didn't continue and didn't retry, the agent was left in `Updating` state.

This could be solved by the redesign of upgrade action https://github.com/elastic/ingest-dev/issues/1621

**Comment by joshdover** [comment]
Let's not couple this to the https://github.com/elastic/ingest-dev/issues/1621 as that is likely to be smaller in scope to begin with.

Do you have any logs of what the error was? I remember @blakerouse fixed an issue where we were silently dropping errors and not retrying. I believe we added retries up to 3 attempts, but maybe it's not enough, or only covered one error (I think was retrying on conflict errors): https://github.com/elastic/fleet-server/pull/1896

**Comment by joshdover** [comment]
We discussed that this old PR may also be a potential workaround/fix for these transient issues by ensuring that the agent's version and upgrading status is always updated on every checkin: https://github.com/elastic/fleet-server/pull/1731

**Comment by juliaElastic** [comment]
The error was a connection issue to ES when trying to create action result, as far as I saw the code didn't retry after this error at all.

**Comment by cmacknz** [comment]
> I believe we added retries up to 3 attempts, but maybe it's not enough, or only covered one error (I think was retrying on conflict errors): https://github.com/elastic/fleet-server/pull/1896

> The error was a connection issue to ES when trying to create action result, as far as I saw the code didn't retry after this error at all.

Let's do a thought experiment here. In the middle of an attempt to upgrade 10K agents, the Elasticsearch deployment for Fleet server has 20 minutes of continuous downtime. What happens to all of our upgrade actions? I don't consider "many agents get stuck in updating until the user manually intervenes" to be the right answer. 

Note that I have used upgrades as an easy example, and some of the changes in https://github.com/elastic/ingest-dev/issues/1621 could be a bandaid for this specifically for upgrades. This would do absolutely nothing for any other action type however. What if instead of upgrades they were security response actions? 

How do we ensure that any type of action is eventually acknowledged?

**Comment by cmacknz** [comment]
We also need a way for Fleet Server to confirm that the agent has successfully persisted an action it was sent. Otherwise it seems possible for the agent to restart immediately after receiving a checkin response with an action before it has enqueued it.

**Comment by joshdover** [comment]
> We also need a way for Fleet Server to confirm that the agent has successfully persisted an action it was sent.

I believe we already have this via the `ack_token` field during checkin. Agent should always send the ack_token of the last persisted action and Fleet Server should always deliver any newer ones than that.

**Comment by joshdover** [comment]
I dug into the Agent code and AFAICT we never stop retrying failed acks, Horde should definitely do the same

**Comment by juliaElastic** [comment]
I found this, I thought it is defining 5 retries by default, or is it referring to something else? https://github.com/elastic/elastic-agent/blob/main/internal/pkg/fleetapi/acker/retrier/retrier.go#L19

It is not that trivial to remove the max retries from horde, currently it is doing a 20 retry in a for loop in `handleAck`. We can't  indefinitely retry as it would block other actions from being acked I think.
https://github.com/elastic/horde/blob/main/internal/pkg/drone/action.go#L169

**Comment by joshdover** [comment]
Seems there are multiple ackers and retries in here, I don't really understand the difference or the reason for the complexity. @pchila you've been in the Fleet gateway code recently. Can you help us understand the actual agent behavior on ack retries (ideally with manual testing)? Any idea what the reason is for this complexity?

For the horde problem, this seems to be another reason we'd benefit from having acks flow through the checkin endpoint. This way there's only a single loop for message exchange in horde.

**Comment by juliaElastic** [comment]
While debugging this, I encountered another issue where the drone is stuck in updating after upgrade.
For 2 drones out of 5000, I see this in the logs:
`Agent is not currently connected. Not dispatching actions.`

And it is not followed by any action delivered messages, even though the drone does successful checkins after.

The action was started at `2023-05-08T12:27:11.715Z` with a 10m rollout period.

Fleet Server logs:
https://logging.us-west2.gcp.elastic-cloud.com/app/r/s/u2wD8
https://admin.found.no/deployments/b7634a61d2cdfbfa88629b9a2df305f9/integrations_server

**Comment by joshdover** [comment]
@juliaElastic what's your plan to close this one out? From my reading of this so far we should:
- Ensure Fleet Server doesn't swallow any errors during ack, they need to be returned to the client
- Fix the query for the action_seq_no being 0

**Comment by juliaElastic** [comment]
I was trying to reproduce the original issue in the description, to see why the agent didn't retry if the action result failed to persist. It is hard to reproduce, I might have to hardcode an error to see what agent does.

With the seq_no issue, I think it will be easy to fix for the 0 special case, trying to come up with a way to test it, not to rely on the 5k run where it doesn't always happen.

**Comment by cmacknz** [comment]
> I was trying to reproduce the original issue in the description, to see why the agent didn't retry if the action result failed to persist. It is hard to reproduce, I might have to hardcode an error to see what agent does.

Related to the testing aspect of this, we want to build a mock Fleet server purely for testing agent: https://github.com/elastic/elastic-agent/issues/2630. This would give us complete control over the checking and ack responses returned to the agent without needing to figure out how to force errors or particular timings with the real system.

**Comment by juliaElastic** [comment]
I found where is the bug with the seq_no, raised a fix: https://github.com/elastic/fleet-server/pull/2582

**Comment by juliaElastic** [comment]
Simulated the original error locally by throwing an error always instead of writing out action result [here](https://github.com/elastic/fleet-server/blob/main/internal/pkg/api/handleAck.go#L323).

What I observed is that the drone acks the action (action seq_no:1, agent seq_no:1) and it is stuck in updating. No wonder that there is no retry as the drone incorrectly acks the action.
I'll check where to fix this.

**Comment by juliaElastic** [comment]
Merged the fix, and ran a 25k test with an image containing the change: https://buildkite.com/elastic/observability-perf/builds/940#0188238a-642c-4d1f-88ea-3052351a82a0

What I'm seeing in upgrade and unenroll, is that 3 acks seem to be missing, but the drones were actually upgraded and then unenrolled. Since the drones are in a right state, the missing ack agent ids are not logged, so it is difficult to investigate. We should be logging out the agents missing acks in this case (by querying all agents in the action and comparing it with a list of acked agents in action results).
The only issue here is that Agent activity shows these actions as not completed.

**Comment by joshdover** [comment]
Your last two observations seems consistent with Fleet Server silently ignoring some error and not returning the result back to the drone correctly. In that case the drone wouldn't retry and the ack wouldn't be written.
