### ISSUE TITLE
Elastic-Agent setup errors regarding certs usage in Fleet Server

### ISSUE THREAD

**Issue by amolnater-qasource** [elastic/fleet-server#253]
We have attempted to Install Elastic-Agent setup with the following ways:

**Scenario 1:**
If we try to install fleet server with "--fleet-server-insecure-http"
CLI shows errors.

**Scenario 2:** 
If we try to install fleet server without "--fleet-server-insecure-http"
Able to install Fleet server.

**Following this:**
Ideally, secondary agent should be installed without --insecure
but CLI shows that we need to add --insecure
So when we actually add "--insecure" it again shows errors.

**Please refer below screenshots:**
![Fleet Commands](https://user-images.githubusercontent.com/77374876/115404385-e7f68e80-a20a-11eb-82e8-ea70c456f345.png)

**Comment by amolnater-qasource** [comment]
@manishgupta-qasource Please review.

**Comment by manishgupta-qasource** [comment]
Reviewed & Assigned to @EricDavisX

**Comment by ph** [comment]
Can you restest the above scenario, we think we have fixed that issue

**Comment by EricDavisX** [comment]
@dikshachauhan-qasource please see above, and re-test

**Comment by dikshachauhan-qasource** [comment]
Hi @EricDavisX 

We have validated above mentioned issue and found it not reproducible on 7.13 BC3 Cloud-qa build.

We are able to install fleet server and elastic agent without any errors. Screenshot is attached here for reference:

![image](https://user-images.githubusercontent.com/72375798/116992678-0ae96e00-acf4-11eb-834c-720e6aa90d28.png)

Please let us know if anything else is required to cover or we can close this.

Thanks
QAS

**Comment by EricDavisX** [comment]
let's close it out.  thanks Diksha
