### ISSUE TITLE
./elastic-agent: 2: Syntax error: Unterminated quoted string

### ISSUE THREAD

**Issue by TURKYMAGIC** [elastic/fleet-server#2537]
I have a problem when installing a fleet agent on the fleet host,

after I past this code on the fleet host to install the agent it shows an error and the fleet agent not installed 

Note I removed token and IP and fingerprint for security purposes 

"curl -L -O https://artifacts.elastic.co/downloads/beats/elastic-agent/elastic-agent-8.7.0-linux-x86_64.tar.gz
tar xzvf elastic-agent-8.7.0-linux-x86_64.tar.gz
cd elastic-agent-8.7.0-linux-x86_64
sudo ./elastic-agent install \
  --fleet-server-es=https://xxx.xxx.xxx.xxx:9200 \
  --fleet-server-service-token=xxxxx \
  --fleet-server-policy=fleet-server-policy \
  --fleet-server-es-ca-trusted-fingerprint=xxxxxx"

I receive this error and the install cant be completed:

elastic-agent-8.7.0-linux-x86_64/data/elastic-agent-fc4a15/components/monitors.d/sample.http.yml.disabled
elastic-agent-8.7.0-linux-x86_64/data/elastic-agent-fc4a15/components/monitors.d/sample.icmp.yml.disabled
elastic-agent-8.7.0-linux-x86_64/data/elastic-agent-fc4a15/components/monitors.d/sample.tcp.yml.disabled
elastic-agent-8.7.0-linux-x86_64/data/elastic-agent-fc4a15/components/osquery-extension.ext
elastic-agent-8.7.0-linux-x86_64/data/elastic-agent-fc4a15/components/osquerybeat
elastic-agent-8.7.0-linux-x86_64/data/elastic-agent-fc4a15/components/osquerybeat.reference.yml
elastic-agent-8.7.0-linux-x86_64/data/elastic-agent-fc4a15/components/osquerybeat.spec.yml
elastic-agent-8.7.0-linux-x86_64/data/elastic-agent-fc4a15/components/osquerybeat.yml
elastic-agent-8.7.0-linux-x86_64/data/elastic-agent-fc4a15/components/osqueryd
elastic-agent-8.7.0-linux-x86_64/data/elastic-agent-fc4a15/components/packetbeat
elastic-agent-8.7.0-linux-x86_64/data/elastic-agent-fc4a15/components/packetbeat.reference.yml
elastic-agent-8.7.0-linux-x86_64/data/elastic-agent-fc4a15/components/packetbeat.spec.yml
elastic-agent-8.7.0-linux-x86_64/data/elastic-agent-fc4a15/components/packetbeat.yml
elastic-agent-8.7.0-linux-x86_64/data/elastic-agent-fc4a15/components/pf-host-agent
elastic-agent-8.7.0-linux-x86_64/data/elastic-agent-fc4a15/components/pf-host-agent.spec.yml
elastic-agent-8.7.0-linux-x86_64/elastic-agent
./elastic-agent: 2: Syntax error: Unterminated quoted string

**Comment by mohamedziada** [comment]
It looks like you use a different Arch
for me, it works "**arm64**"

curl -L -O https://artifacts.elastic.co/downloads/beats/elastic-agent/elastic-agent-8.7.0-linux-arm64.tar.gz
tar xzvf elastic-agent-8.7.0-linux-arm64.tar.gz
cd elastic-agent-8.7.0-linux-arm64/

**Comment by cmacknz** [comment]
The official elastic-agent-8.7.0-linux-x86_64.tar.gz works for me in a fresh Ubuntu container.

> ./elastic-agent: 2: Syntax error: Unterminated quoted string

There must be a missing quote in your configuration, given it suggests line two it is probably the output configuration:

```yaml
outputs:
  default:
    type: elasticsearch
    hosts: [127.0.0.1:9200]
    api-key: "example-key"
```

If this does not resolve your problem, please ask a question in https://discuss.elastic.co/c/elastic-stack/elastic-agent/91. The issue tracker is confirmed bugs, not help requests.

**Comment by TURKYMAGIC** [comment]
It worked, thanks guys
