### ISSUE TITLE
Support ECS logging in JSON format to stdout/stderr

### ISSUE THREAD

**Issue by jsoriano** [elastic/fleet-server#2541]
**Describe the enhancement:**

In order to align Fleet Server with other Elastic products, support ECS logging in JSON format to stdout/stderr.

**Describe a specific use case for the enhancement or feature:**

Deployments in Kubernetes for cloud and serverless offerings.

**Comment by michel-laterman** [comment]
Are we missing any fields on the log messages (I know that the agent adds some attributes when it aggregates the logs)?
I think we just need to change the configuration to have:
```json
logging.to_stderr: true
```
for stderr output

**Comment by joshdover** [comment]
One thing that is important is that we don't diverge the schema between Fleet Server under Agent and standalone Fleet Server for serverless. It should have the same schema so we can use the same mappings, etc.

**Comment by jsoriano** [comment]
> I thought we already log to ECS JSON in Integrations Server? I think maybe @michel-laterman is saying that when we add that config, it switches to JSON too. Here's how agent starts Fleet Server and it logs in JSON in this case: https://github.com/elastic/elastic-agent/blob/2d71070998d0df70b438d61acc8364ba174e60fc/specs/fleet-server.spec.yml#L16-L21

You are right. The problem was that I was trying with the configuration file in the repository, that includes `pretty: true`. Commeting this line out makes fleet-server to log in JSON format.
