### ISSUE TITLE
Support dynamically enabling APM instrumentation from agent control protocol

### ISSUE THREAD

**Issue by joshdover** [elastic/fleet-server#2565]
Follow up to agent support in https://github.com/elastic/elastic-agent/issues/2612

We need to support enabling APM instrumentation when agent provides it over the control protocol. This may require restarting some internal pieces such as the the bulker, but this should be done only if necessary. Ideally we can enable instrumentation without having to restart anything or drop caches.

**Comment by michel-laterman** [comment]
I think it may already automatically reload when it detects server configuration has changed as part of:
https://github.com/elastic/fleet-server/blob/main/internal/pkg/server/fleet.go#L176

As part of the reload various internal structs are replaced, including any existing tracer, the bulker (and any thing that uses the bulker), as well as the API server.
The cache is not replaced.

we can go through it to see if there's anything we can improve, but I don't think there will be much to do (if it's working)

**Comment by jlind23** [comment]
@michel-laterman I am correct to assume that you are going to test it and report back here?

**Comment by joshdover** [comment]
We can also delay this as the upstream work in agent was delayed. Might be best just to wait to test it until then.

**Comment by joshdover** [comment]
Close as dupe of https://github.com/elastic/fleet-server/issues/2868
