### ISSUE TITLE
Replace refresh=true with refresh=wait_for in Fleet Server

### ISSUE THREAD

**Issue by jlind23** [elastic/fleet-server#2581]
While calling Elasticsearch APIs, fleet server uses a refresh flag value that default to `true` this should be change to `wait_for`.

- [ ] This change should be testing against a stateful Elasticsearch first to see if whether or not we want to apply it on all deployment types.

**Comment by michel-laterman** [comment]
Changing some of these instances will be easy [as they are defined as strings by fleet-server](https://github.com/elastic/fleet-server/blob/main/internal/pkg/bulk/opBulk.go#L192).

However we may want some support from the clients team in order to do this. Currently some of our bulk requests use the underlying API, and it [defines refresh as a bool value](https://github.com/elastic/go-elasticsearch/blob/8.9/esapi/api.mget.go#L56)

**Comment by jlind23** [comment]
Will refresh false default to wait_for in this case? Or shall we ask the es team to provide a new api version?

**Comment by michel-laterman** [comment]
[false does not have the same behaviour as wait_for](https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-refresh.html); I think better support from the api would be nice I can see that some areas of the client have it, but not all calls.

**Comment by michel-laterman** [comment]
I searched through the fleet-server codebase to find where we include the refresh param when contacting ES, I think I found all our calls.

Most of our refresh uses [bulker.WithRefresh](https://github.com/elastic/fleet-server/blob/main/internal/pkg/bulk/opt.go#L28) to abstract the behaviour, this call will result in a flag being set which is read in [the engine](https://github.com/elastic/fleet-server/blob/main/internal/pkg/bulk/engine.go#L126)
This flag can either result in a change to:
- [opBulk](https://github.com/elastic/fleet-server/blob/main/internal/pkg/bulk/opBulk.go#L192) that uses a string directly and can be easily changed by us
- [opRead](https://github.com/elastic/fleet-server/blob/main/internal/pkg/bulk/opRead.go#L84) which uses the go-elasticsearch client's [mget api](https://github.com/elastic/go-elasticsearch/blob/bf2725f236461e0892b7375b70b4b4e217b415d9/esapi/api.mget.go#L56)

The other areas are
- [creating an api key](https://github.com/elastic/fleet-server/blob/main/internal/pkg/apikey/create.go#L38) which uses a string we can change (note that all calls use [`refresh=false` for performance reasons](https://github.com/elastic/fleet-server/blob/main/internal/pkg/api/handleEnroll.go#L274))
- the [file upload api](https://github.com/elastic/fleet-server/blob/main/internal/pkg/file/uploader/es.go#L126) which uses a string we can change
- a call in [dl/migration.go](https://github.com/elastic/fleet-server/blob/main/internal/pkg/dl/migration.go#L98) which uses the [update by query api](https://github.com/elastic/go-elasticsearch/blob/bf2725f236461e0892b7375b70b4b4e217b415d9/esapi/api.update_by_query.go#L422)
- some [testing setup code](https://github.com/elastic/fleet-server/blob/main/internal/pkg/testing/setup.go#L114) for integration tests which uses the [delete by query api call](https://github.com/elastic/go-elasticsearch/blob/bf2725f236461e0892b7375b70b4b4e217b415d9/esapi/api.delete_by_query.go#L397)

**Comment by jlind23** [comment]
@joshdover @jsoriano do you happened to know if there is already a new ES version that will contains this change related to the `wait_for` param instead of a boolean for the refresh value?

**Comment by jsoriano** [comment]
> @joshdover @jsoriano do you happened to know if there is already a new ES version that will contains this change related to the `wait_for` param instead of a boolean for the refresh value?

`wait_for` seems to be available in the module we use https://github.com/elastic/go-elasticsearch/blob/d28715c21ed123d6a7794c57c9f234dcaec734b2/typedapi/types/enums/refresh/refresh.go#L36

Is there something else we are missing?

**Comment by joshdover** [comment]
Yes that's right. `wait_for` is not a new feature - it's already available.

There are some additional features to  that are still in flight that we may need, but based on our early testing from https://github.com/elastic/ingest-dev/issues/1401, we won't need to start using these for our initial target of 25k.

**Comment by michel-laterman** [comment]
I'll take a look at the typed API, however I don't see support for in in the [typed mget api](https://github.com/elastic/go-elasticsearch/blob/main/typedapi/core/mget/mget.go#L275)

**Comment by joshdover** [comment]
@michel-laterman I think it's only relevant on writes where you want to be sure that your next read has the specific write you just made. So ideally any refresh=true on mgets could be removed and replaced with a refresh=wait_for on any writes that we need. If we do find that we still need refresh=true on those mgets, we can look into leveraging the fash_refresh setting: https://docs.google.com/document/d/1UDCOOE9vnqK_ypQO6B5cIcwNi3gIFGaQMpShOEjDPRU/edit#

**Comment by michel-laterman** [comment]
The refresh api page has the `wait_for` option, but the [mget page does not](https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-multi-get.html), it's still listed as a boolean

**Comment by michel-laterman** [comment]
I've created a [pr in the elasticsearch repo](https://github.com/elastic/elasticsearch/pull/97856) to add the `index.fast_refresh: "true"` setting to all our frequently used fleet-server indices

**Comment by jlind23** [comment]
@michel-laterman shouldn't we mark https://github.com/elastic/elasticsearch/pull/97856 as closing this issue?
