### ISSUE TITLE
Fleet server permanently goes offline on assigning to the new policy not having Fleet Server integration.

### ISSUE THREAD

**Issue by harshitgupta-qasource** [elastic/fleet-server#2603]
**Kibana Build details:**
```
VERSION: 8.8 BC5 Kibana cloud environment
BUILD: 63092
COMMIT: ba9b182a3422f5e162c1ca74baafb91833eca059
```
**Host OS and Browser version:** All, All
**Preconditions:**
1. 8.8 BC5 Kibana cloud environment should be available.
2. Fleet server should be installed manually using Fleet Server policy having Fleet server integration.

**Steps to reproduce:**
1. Navigate to the Fleet tab.
2. Select the installed fleet server agent and assign it to a new policy not having fleet server integration.

3. Assign the fleet server back to the policy with Fleet server integration.

4. Observe the fleet server remains offline permanently.

**Expected:**
Fleet server should get back healthy on assigning back to the policy having Fleet Server integration.

**Note:**
- This issue is reproducible on all OSs.

**Screencast:**

https://github.com/elastic/fleet-server/assets/101545338/e03ac147-105b-459f-ae0b-df6a4a49184e

**Screen-shot**
- On assigning back to the policy having Fleet Server integration
![image](https://github.com/elastic/fleet-server/assets/101545338/00acafd0-1879-46ac-a316-3d4516fb4e06)

- Relates https://github.com/elastic/fleet-server/issues/2603

**Comment by harshitgupta-qasource** [comment]
@amolnater-qasource Kindly review

**Comment by amolnater-qasource** [comment]
Secondary review for this ticket is Done.

**Comment by juliaElastic** [comment]
I think we said on the QA sync last week that it is expected that the agent comes back online after reassigning it to the right policy, we should investigate why it stays offline. Though it is not likely that users intentionally reassign a Fleet Server to a regular policy.

**Comment by jlind23** [comment]
thanks @michel-laterman @harshitgupta-qasource I believe we can close this as won't fix then.

**Comment by harshitgupta-qasource** [comment]
Hi Team,

Thank you for confirming the expected behavior. Hence, we are closing this issue.

Thanks!!
