### ISSUE TITLE
Pre-installed Fleet-Server agent under Agents tab on 7.13.0 BC-1 Kibana cloud environment.

### ISSUE THREAD

**Issue by amolnater-qasource** [elastic/fleet-server#264]
**Kibana version:** 7.13.0 BC-1 Kibana cloud environment

**Host OS and Browser version:** All, All

**Build Details:**
```
  Build: 40542
  Commit: a93a7fe471bdcf6c06e18c0312af2435e7613e44
```

**Preconditions:**
1. 7.13.0 Snapshot Kibana cloud environment should be available.

**Steps to reproduce:**
1. Login to Kibana environment.
2. Navigate to Agents tab.
3. Observe pre installed Agent with "Elastic Agent on Cloud policy".

**Expected Result:**
No agent should be pre-installed under Agents tab on 7.13.0 BC-1 Kibana cloud environment.

**Screenshots:**
![Agent](https://user-images.githubusercontent.com/77374876/115821857-2cf40e00-a421-11eb-8f5c-fe72860c0a19.jpg)

**Question:**
Please let us know if this is expected and usage of this pre-installed Fleet-Server agent.

**Comment by amolnater-qasource** [comment]
@manishgupta-qasource Please review.

**Comment by manishgupta-qasource** [comment]
Reviewed & Assigned to @EricDavisX

**Comment by simitt** [comment]
If you had `APM & Fleet Server` enabled, then this is expected behavior on cloud. From `7.13` on ESS/ECE will always create a policy with an elastic-agent and a fleet-server running when `APM & Fleet Server` is enabled for the cluster.

**Comment by amolnater-qasource** [comment]
Hi @simitt 
Thank you for the feedback.
> If you had APM & Fleet Server enabled

We have observed this agent already installed when we logged into kibana just after deployment from staging. We didn't enabled any `APM & Fleet server` settings manually. 
It would be very helpful if you could share related PR, so that we can validate and update our test content accordingly.

Thanks
QAS

**Comment by simitt** [comment]
> just after deployment from staging.

**Comment by EricDavisX** [comment]
closing as this is working as designed, and is exemplifying the beginning of the new cloud based 'hosted agent' work-flow!

**Comment by EricDavisX** [comment]
the UI is subject to change of course, but one more thing on this:

@dikshachauhan-qasource if you click the 'customize' button you see here: 
<img width="268" alt="Screen Shot 2021-04-26 at 8 55 11 AM" src="https://user-images.githubusercontent.com/12970373/116085960-56a17500-a66d-11eb-92a3-6ddce2d9447a.png">

this screen shows with the 'APM & Fleet nodes' on by default in a given cloud deployment:
<img width="805" alt="Screen Shot 2021-04-26 at 8 55 32 AM" src="https://user-images.githubusercontent.com/12970373/116085924-4db0a380-a66d-11eb-8139-1d7b501e152a.png">

**Comment by simitt** [comment]
This is an expected bug until https://github.com/elastic/kibana/issues/97673 is backported and integrated in the `7.13` snapshots, and the cloud setup is adapted accordingly to use the policy ID instead of the `is_default_fleet_server` flag.

**Comment by dikshachauhan-qasource** [comment]
Thanks @simitt for the update.
