### ISSUE TITLE
get 404 response from fleet-server api/fleet/status, when it appears to be running, even over localhost

### ISSUE THREAD

**Issue by EricDavisX** [elastic/fleet-server#273]
this is using the latest 8.0 artifacts as of April 23

Kibana is self-managed snapshot deploy commit:
commit f094d9fdc23d0bc393c072b96e437cdefc12bc4f
Date: Thu Apr 22 12:50:35 2021 +0100

Agent artifacts are deployed to debian9 in GCP
elastic-agent version yields:
Binary: 8.0.0-SNAPSHOT (build: 43280e0f690bdacca03d313bd3121247833854ea at 2021-04-22 16:20:05 +0000 UTC)

I have set up fleet server using a 'stand-alone' agent install just to get it to disk, and then i have enrolled it using http (https didn't work, it fails for some reason).
the install is akin to this:
sudo ./elastic-agent install -f --fleet-server-es=http://elastic:asdfasdf@bastion.endpoint.elastic.dev:9201 --fleet-server-policy=c6ac67d0-a418-11eb-a4bb-ddac73bf3875

responses from the command line:
admin@security-linux-1:~/elastic-agent-8.0.0-SNAPSHOT-linux-x86_64$ curl --insecure https://security-linux-1.endpoint.elastic.dev:8220/api/fleet/status
404 page not found

admin@security-linux-1:~/elastic-agent-8.0.0-SNAPSHOT-linux-x86_64$ curl --insecure https://localhost:8220/api/fleet/status
404 page not found

this must indicate the fleet server isn't set up or running quite right i believe.  the fleet server is however, indexing documents to elasticsearch and shown in this screenshot:
![cannot-connect-locally-to-fleet-server](https://user-images.githubusercontent.com/12970373/115929261-837b3f80-a455-11eb-9806-fae982ee3f80.png)

I have captured relating logs in other preceding tickets... I can re-attach as needed, but cannot easily make time *just right now to do so.

**Comment by blakerouse** [comment]
Sorry the API for status should be `/api/status`, can you try that.

**Comment by EricDavisX** [comment]
with the adjusted api, it returns successful / healthy.  I will close this out, thanks - I'm still debugging the overall goal of connecting 2 hosts with fleet server, this gets us one debug step closer though!
