### ISSUE TITLE
[Inconsistent]: Fleet server failed to install or gets stuck in updating state.

### ISSUE THREAD

**Issue by harshitgupta-qasource** [elastic/fleet-server#2742]
**Kibana Build details:**
```
VERSION: 8.9.0 BC1 Kibana cloud environment
BUILD: 64385
COMMIT: 313dac73d8d3bc5930447f732e3ae163fb1b7f70
```
**Host OS and Browser version:** All, All
**Preconditions:**
1. 8.9.0 BC1 Kibana cloud environment should be available.
2. Different agents should be installed.

**Steps to reproduce:**
1. Navigate to the Fleet tab.
2. Click on Add Fleet Server button.
3. Add new Fleet server Host by adding the host URL `https://public-ip-host:8220`.
4.  Now run the fleet server installation command.
5. Observe that Fleet server failed to install or gets stuck in updating state.

**Observations:**
- We have observed below three scenarios:

1. Sometime fleet server installed Successfully.[**Working Fine**]

2. After installing fleet server gets stuck in updating state and then move to offline state after sometime:
![image](https://github.com/elastic/fleet-server/assets/101545338/e92924b3-e1ce-4657-a09f-89d2e7014ba8)

3. On running fleet server install command showing error:
![image](https://github.com/elastic/fleet-server/assets/101545338/6da8c29d-113b-4cf6-a43b-96a3a316c06b)

**Expected:**
Fleet server should install healthy on kibana cloud enviroment.

**Note:**
Issue is Inconsistently reproducible on 8.8.2 BC2 as well.

**Comment by harshitgupta-qasource** [comment]
@amolnater-qasource Kindly review

**Comment by amolnater-qasource** [comment]
Secondary review for this ticket is Done

**Comment by harshitgupta-qasource** [comment]
Hi Team

While testing on 8.9.2 BC1 build, we observed this issue reproducible there.

**Observations:**

- After installing fleet server gets stuck in updating state and then move to offline state.
- On running fleet server install command showing error.

**Build details:**
VERSION: 8.9.2 BC1
BUILD: 64883
COMMIT: 21f3ebd6e951d102f41b0299c35e030c3c9e8eb6
Artifacts: https://staging.elastic.co/8.9.2-e4235bb7/summary-8.9.2.html

**Screenshot**
![image (1)](https://github.com/elastic/fleet-server/assets/101545338/f9114d7d-f577-4c6f-9430-168a58772016)


Please let us know if anything else is required from our end.

Thanks!

**Comment by jlind23** [comment]
@harshitgupta-qasource is this something still reproducible with the latest minors?

**Comment by harshitgupta-qasource** [comment]
Hi @jlind23 ,

We have re-validated this issue on the latest 8.15.2 Kibana cloud environment and found it **not reproducible**.

Observations:
- Fleet server installed Successfully and not stucked in updating state.

**Build details:**
VERSION: 8.15.2
BUILD: 76625
COMMIT: 5a522bfe14bc6d06c20bc337477fd53f7c538973

**Screen-Shot:**
![Image](https://github.com/user-attachments/assets/e3d39f74-b5f1-4109-ba49-9e84806549a5)



Hence, we are closing this issue and marking as **QA: Validated**.

Thanks
