### ISSUE TITLE
Add CI pipeline for OSX

### ISSUE THREAD

**Issue by jsoriano** [elastic/fleet-server#2765]
Even if we don't generate fleet-server artifacts for OSX, many of our developers use it on a daily basis. We need to ensure that we can always reliably run tests locally. For this we should have a CI pipeline that run tests on OSX and detect regressions there.

Context: On a recent change on E2E tests (https://github.com/elastic/fleet-server/pull/2710), I broke them for OSX, this was not detected because neither I or CI use OSX. We discovered it while testing a different change and we had to dedicate some time to investigate and fix it, as part of an unrelated task. This kind of issues slow down development.

**Comment by jlind23** [comment]
@pazone i am for now assigning you this as it is also blocked on the Mac OS worker availability.

**Comment by pazone** [comment]
@jsoriano We are ready to start implementation on that since the ephemeral macos instances are available for us. 
However, we have a quite limited amount of macOS VMs capacity, and as we discovered recently they are quite slow because of the lack of CPUs. 
So what kind of tests do we need to execute on MacOS? Keeping in mind that might be slower we can probably have some subsets of tests for MacOS

**Comment by jsoriano** [comment]
@pazone, this is great. I think that we can start with the [check and build](https://github.com/elastic/fleet-server/blob/8daafefd267cd26c8f6f09cfd1f7c96986e50db1/.buildkite/pipeline.yml#L15) and [unit test](https://github.com/elastic/fleet-server/blob/8daafefd267cd26c8f6f09cfd1f7c96986e50db1/.buildkite/pipeline.yml#L73) steps. They should be light and a good starting point.

Later we can add integration and e2e tests if there is enough capacity. The issue that originated this request was with e2e tests.

cc @michel-laterman

Thanks!

**Comment by pazone** [comment]
@jsoriano Do we also need MacOS 13 arm?

**Comment by jsoriano** [comment]
> Do we also need MacOS 13 arm?

Not sure about the versions that we need. The original intention of this issue was to keep things working for developers that use to work in MacOS. Do you have stats on the current usage share? cc @michel-laterman in case he has more details.

> Should we proceed with e2e tests?

Sounds good to me if we have capacity.
