### ISSUE TITLE
Self-hosted agent shouldn't be allowed to enroll into hosted agent policies

### ISSUE THREAD

**Issue by jen-huang** [elastic/fleet-server#278]
From discussion in https://github.com/elastic/kibana/issues/98343.

In https://github.com/elastic/kibana/issues/76843 when we added support for hosted agent policies (aka agent policies that have `is_managed: true` attribute), one of the requirements was to block self-hosted agents from enrolling in hosted agent policies. This requirement was fulfilled in PR https://github.com/elastic/kibana/pull/90458 but needs to get re-added to Fleet server code now that enrollment isn't handled by Kibana.

**Comment by jlind23** [comment]
@jen-huang Closing this for now as I don't think it is relevant anymore.
