### ISSUE TITLE
Consume APM configuration over the control protocol

### ISSUE THREAD

**Issue by joshdover** [elastic/fleet-server#2868]
In order to enable APM tracing when Fleet Server is managed by Elastic Agent, Fleet Server needs to apply APM configuration settings when they're passed over the control protocol.

This may require that we change how the `apm.Tracer` object is created and passed to internal objects as right now it is only created if APM is enabled on initial boot of Fleet Server here: https://github.com/elastic/fleet-server/blob/f76576d2e0e3c38efe20a2c2c35b2ef80d7f8f12/internal/pkg/server/fleet.go#L549-L552

We may instead want to rely on `apm.DefaultTracer` instead of manually passing a tracer around and then use `apm.SetDefaultTracer` when the config change comes over the control protocol.

References:
- elastic-agent-client changes: https://github.com/elastic/elastic-agent-client/pull/82
- https://github.com/elastic/elastic-agent/issues/2612

**Comment by jlind23** [comment]
@joshdover Can I close this one in favor of: https://github.com/elastic/fleet-server/issues/2565?

**Comment by michel-laterman** [comment]
`initTracer` is called in `runServer`, `runServer` is called if server configuration changes are detected ([see here](https://github.com/elastic/fleet-server/blob/f76576d2e0e3c38efe20a2c2c35b2ef80d7f8f12/internal/pkg/server/fleet.go#L189)) but not if env vars change.

The TestServerInstrumentation integration test already covers this as a test case. (I had to fix the test as part of [this issue](https://github.com/elastic/fleet-server/issues/2953)).

Unless this issue changes how apm tracing is specified I think we can close this and #2565

**Comment by joshdover** [comment]
Yes the other is a duplicate. Closed it. The goal of this work is to support APM configuration of Fleet Server on ESS where we do not have the flexibility to specify env vars. Agent now exposes this configuration over the control protocol, and Fleet Server needs to be updated to read it
