### ISSUE TITLE
Allow Fleet Server to serve the PGP key when stored on disk

### ISSUE THREAD

**Issue by jlind23** [elastic/fleet-server#2887]
If Elastic Agent are unable to connect with Elastic public URL to retrieve the PGP key, they will fallback to a Fleet Server URL where the public key can be hosted too.

In Fleet Server, we must define a fixed route for hosting the GPG key `downloads/signing/key.pub`  to mirror the public URL and have it read the GPG key in from its configuration using the same secure mechanisms we use to read the TLS private key. 
Mandate HTTPS on this endpoint and let Elastic Agent call it whenever needed.

Related Elastic Agent issue - https://github.com/elastic/elastic-agent/issues/3264

**Comment by cmacknz** [comment]
> My suggested route is: GET /api/agents/upgrades/<major>.<minor>.<patch>/pgp-public-key. For now Fleet Server should always serve the same file and ignore the version number in the path.

👍 great idea let's do this.

**Comment by lucabelluccini** [comment]
## Fleet Server

Fleet Server needs to be updated first.
Let's suppose the new key is used on `8.Y`.

We first upgrade Fleet Server on a version [8.9, 8.Y) to [8.Y,+Inf)
- On ECE, ESS and ECK, there is no issue as we redeploy containers
- On prem with tar.gz, bare metal:
    - If Fleet Server has public internet access, when upgrading from versions [8.9, 8.Y), it will attempt the embedded key (fails) and then the first fallback URL (success) 🟢 
    - If Fleet Server is air-gapped, when upgrading from version [8.9, 8.Y), it will attempt the embedded key (fails) and then the first fallback URL
        - If the user deployed their webserver with TLS to serve the file and updated the DNS to resolve the URL to the webserver, it will be successful 🟢 
        - Else, it will fallback on the second URL - but as it is a Fleet Server itself... It doesn't have a Fleet Server to download the key from ❓ - maybe it should load from local file?

## Elastic Agents connected to the Fleet Server

- On ECE, ESS, ECK, there is no issue as we redeploy containers
- On prem with tar.gz, bare metal:
    - If Elastic Agent has public internet access, when upgrading from versions [8.9, 8.Y), it will attempt the embedded key (fails) and then the first fallback URL (success) 🟢 
     - If Elastic Agent is air-gapped, when upgrading from version [8.9, 8.Y), it will attempt the embedded key (fails) and then the first fallback URL
        - If the user deployed their webserver with TLS to serve the file and updated the DNS to resolve the URL to the webserver, it will be successful 🟢 
        - Else, it will fallback on the second URL which is served by Fleet Server. As the user has something already in place to communicate to Fleet Server, it will be successful 🟢 

---

Is this step-by-step review of the flow correct?

As a side note, it would be nice to include the `default.pgp` in the docker images of Fleet Server/Elastic Agent to be able to support EA users attempting to upgrade when connected to Fleet servers running on ECK and ECE (within air-gapped envs).

**Comment by cmacknz** [comment]
That looks correct to me, thanks for that breakdown and it highlights an omitted edge case in the problem description:

> * If Fleet Server is air-gapped, when upgrading from version [8.9, 8.Y), it will attempt the embedded key (fails) and then the first fallback URL
>   * If the user deployed their webserver with TLS to serve the file and updated the DNS to resolve the URL to the webserver, it will be successful 🟢
>   * Else, it will fallback on the second URL - but as it is a Fleet Server itself... It doesn't have a Fleet Server to download the key from ❓ - maybe it should load from local file?

In the case of an air gapped Fleet server there are two cases, one of which we can handle easily and one we can't:

1. The problem we can handle is an upgrade of an air gapped Fleet Server after the first release that allows Fleet Server to host the GPG key. In this case the Elastic Agent supervising the Fleet Server does the download + verification, so it will have to reach out to the Fleet Server it is supervising to get the GPG key. It should be able to do this over a unix socket, the same way we handle Fleet checkins of the agent that runs Fleet Server.

2. The problem we don't handle is the case where a user is upgrading an air gapped Fleet Server from a version before the hosted GPG key was introduced. In this case I think they have to do this upgrade before the embedded GPG key is expired or they'd have to re-install. I believe we have this problem already in the agent where users need to upgrade to the version that includes the fallback GPG URL before the key is expired. This is just a different version of the same problem, although reinstalling Fleet Servers is probably more feasible than reinstalling possibly 1000s of agents.

**Comment by matthiasledergerber** [comment]
We are currently having this issue. Our Fleet Server are on 8.9.2. Our Elastic Agents on 8.9.0. We have an air gapped systems and use custom repositories that work reliable.

When trying to Upgrade the Elastic Agent from 8.9.0 to 8.9.2:
```
[elastic_agent][info] starting upgrade to version 8.9.2 in background
[elastic_agent][info] Upgrading agent
[elastic_agent][info] download from http://nexus.local.tld/repository/proxy-raw-elasticagent/beats/elastic-agent/elastic-agent-8.9.2-windows-x86_64.zip completed in Less than a second @ +InfYBps
[elastic_agent][info] download from http://nexus.local.tld/repository/proxy-raw-elasticagent/beats/elastic-agent/elastic-agent-8.9.2-windows-x86_64.zip.sha512 completed in Less than a second @ +InfYBps
[elastic_agent][info] Default PGP being appended
[elastic_agent][info] Default PGP being appended
[elastic_agent][error] upgrade to version 8.9.2 failed: failed verification of agent binary: 2 errors occurred:
	* Get "https://artifacts.elastic.co/GPG-KEY-elastic-agent": dial tcp 34.120.127.130:443: connectex: No connection could be made because the target machine actively refused it.
	* Get "https://artifacts.elastic.co/GPG-KEY-elastic-agent": dial tcp 34.120.127.130:443: connectex: No connection could be made because the target machine actively refused it.
```

**Comment by jlind23** [comment]
@cmacknz please keep me honest here but @matthiasledergerber your agent should first try to validate the binary with the signature that is bundled in the installed agent. Do you have any signature verification failure in logs?

**Comment by jlind23** [comment]
As a reference, this is the PR where this was introduced: https://github.com/elastic/elastic-agent/pull/2980

**Comment by jlind23** [comment]
@matthiasledergerber the connection blocked will trigger a problem in the agent upgrade process indeed.
@pierrehilbert will document a workaround which will help airgapped users manually downloading the key https://artifacts.elastic.co/GPG-KEY-elastic-agent and hosting it behind the same url in their air gapped environment. Most probably by changing the etc host of the agent machines.

**Comment by cmacknz** [comment]
The embedded GPG key is still valid, that we are considering the download of the fallback key at the public URL a fatal error is a bug. https://github.com/elastic/elastic-agent/issues/3368

**Comment by matthiasledergerber** [comment]
> @matthiasledergerber the connection blocked will trigger a problem in the agent upgrade process indeed. @pierrehilbert will document a workaround which will help airgapped users manually downloading the key https://artifacts.elastic.co/GPG-KEY-elastic-agent and hosting it behind the same url in their air gapped environment. Most probably by changing the etc host of the agent machines.
> 
> Would that work for you?

yes, we can try. 

We have about 100 agents. Our repositories are http only for other reasons, therefore we cannot use an workaround requiring encrypted connections and certificates (requires to have an PKI Infrastructure for the user and deployment options when self signed certificates, etc.).

But in the end if we are required to do DNS redirection / HTTP redirecton on every host we can also redeploy the agents.

There is no pressure for us on upgrading the agents currently.

**Comment by jlind23** [comment]
The [fix](https://github.com/elastic/elastic-agent/issues/3368) that Craig linked will not help in your case. 
The upgrade functionality that you are using is the one of the installed agent which will always require this DNS redirection until you are upgraded to a release that contains the fix.
So redeploying the agent would probably be better only as soon as the release containing the patch is shipped.

**Comment by pierrehilbert** [comment]
I just merged this PR https://github.com/elastic/elastic-agent/pull/3375 to add a doc with the workaround.
@kilfoyle added a known issue in addition.

**Comment by michalpristas** [comment]
just quick question. 
considering path suggested by josh. are we taking into consideration version qualifiers, snapshot flags etc? 
or are we sticking with simple `major.minor.patch`

**Comment by jlind23** [comment]
I believe we should use major.minor.patch without the snapshot flag which means that both `8.10.0` and `8.10.0-SNAPSHOT` will have their key available at the same path.
@michel-laterman is this the path you took in your PR?

**Comment by michalpristas** [comment]
do you have some branch i can work with? 
i have something that should work but i'd rather test it with 'real' server

**Comment by defensivedepth** [comment]
Side note for Elastic team - this bug would have been caught if there was some testing for Air-Gapped Agent upgrades. Is this something that can be added to your automated testing regime?

**Comment by joshdover** [comment]
Hi @defensivedepth - I think you're referring to this bug https://github.com/elastic/elastic-agent/issues/3368 which is related. This ticket is more about making it simpler for air gapped upgrades if/when our code signing key is rotated, but the change in Agent that introduced the bug shouldn't have failed upgrades before this ticket was completed.

We have scheduled work to implement tests for air gapped to prevent this from happening again: https://github.com/elastic/elastic-agent/issues/3403

**Comment by defensivedepth** [comment]
Fantastic, thanks @joshdover

**Comment by michel-laterman** [comment]
@michalpristas, https://github.com/elastic/fleet-server/pull/2977 has the work; implementation is pretty much complete, i'm just fixing the e2e tests

**Comment by lucabelluccini** [comment]
Hello @thethirstyturtle - sorry I didn't manage to update this issue.
We have a knowledge article in the support portal which reports your suggested workaround.
