### ISSUE TITLE
[Feature Request] Same integration to multiple policy

### ISSUE THREAD

**Issue by lamineer** [elastic/fleet-server#2908]
**Describe the enhancement:**
The enhancement would allow to use same integration settings on multiple policy. For example windows-1 could be applied to Policy 1, Policy 2 and Policy 3, even if the settings are the same.

**Describe a specific use case for the enhancement or feature:**
For example creating Policy for service AD and service DB and service EXCHANGE, they would all base on same Windows Server architecture, but would use different integration and need log seperation for security. So it would need 3 different integrations with same settings. Would simplify configuring integration and reuse integration settings. 

Namespace can be imported from Elastic Agent Policy settings by dynamic values.

**Comment by IanLee1521** [comment]
Agreed, the ability to "include" one policy in another policy would be really helpful to creating different but very similar agent policies built up as you suggest.

**Comment by mikecalizo** [comment]
Hi @nimarezainia I have another Aus-Fed customer that needs this feature.

**Comment by nimarezainia** [comment]
As of 8.15 Reusable Integrations Policies are available for use behind a feature flag. Please see the instructions here: https://github.com/elastic/kibana/issues/188707 - it would be ideal if the customer could try this and provide us with some feedback.

Barring any major issues this feature will be available in 8.16. 
Closing this ER, feel free to open if there is customer feedback.

**Comment by IanLee1521** [comment]
@nimarezainia - I'm interested in trying this out once we get 8.15 deployed. Happy to follow up afterwards with feedback.
