### ISSUE TITLE
[Self-Managed][Windows]:  `unexpected return pc for runtime.deferreturn` error while running uninstall command for windows fleet-server.

### ISSUE THREAD

**Issue by amolnater-qasource** [elastic/fleet-server#2935]
**Kibana Build details:**
```
VERSION: 8.10.0 BC2
BUILD: 66107
COMMIT: fa3473f42d7c5e7a3c2d66026a153e01002f5d3c
```

**Host OS and Browser version:** Windows, All

**Preconditions:**
1. 8.10.0 BC2 Kibana self-managed environment should be available.

**Steps to reproduce:**
1. Install Windows fleet-server.
2. Run usual tests over the environment.
3. Navigate back to CLI and run `.\elastic-agent.exe uninstall` and observe errors.
4. Observe agent is also uninstalled successfully.

**Expected Result:**
No errors should be there in CLI while running uninstall command for windows fleet-server on self-managed environment.

**Note:**
- The issue is observed multiple times on running Uninstall command.
- However the agent gets uninstalled successfully.

**Screenshots:**
![26](https://github.com/elastic/fleet-server/assets/77374876/c98d8eb4-55d5-423a-beda-f8ce07ad8835)
![27](https://github.com/elastic/fleet-server/assets/77374876/a47e09f5-c58a-484c-8862-c8e64e0d44bf)
![28](https://github.com/elastic/fleet-server/assets/77374876/52b5101d-0bed-41ae-8408-f714853cb180)

**Comment by amolnater-qasource** [comment]
@manishgupta-qasource Please review.

**Comment by amolnater-qasource** [comment]
**Further Update:**
In further tests this issue is observed while uninstalling the standalone agent too on self-managed kibana.

**Screenshot:**
![image](https://github.com/elastic/fleet-server/assets/77374876/935d6d25-5716-4a5c-8b9e-7bf612b5a963)

cc: @jlind23 
Thanks!

**Comment by jlind23** [comment]
@pierrehilbert I believe this should rather something diagnosed by the Agent team. Wdyt?

**Comment by pierrehilbert** [comment]
Hey @amolnater-qasource is this error happening only with fleet-server or with standalone agent too?

**Comment by amolnater-qasource** [comment]
Hi @pierrehilbert 

Thank you for looking into this.
Yes, we observed it twice for standalone agent when it was run through logstash.

Later we ran the standalone agent through elasticsearch, however didn't get the error.

For fleet servers(running through elasticsearch) installed differently through quickstart and production mode, we observed these errors in cli while running the uninstall command.

Please let us know if anything else is required from our end.
Thanks!!

**Comment by cmacknz** [comment]
The stack trace here is likely coming from the agent itself, if it were coming from fleet-server the panic would be in the underlying agent logs and not on the console.

**Comment by michalpristas** [comment]
trying to repro this without luck, can we get some more env info?
what version of windows is used, how much ram is there and how much ram is free at the time when uninstall is called

**Comment by amolnater-qasource** [comment]
Hi @michalpristas 

Thank you for looking into this.

While testing we have observed this issue reproducible for elastic-agent that was installed on cloud build unknowingly.

**Scenario:**
- The agent was installed from few days, VM was off from yesterday too and we observed it while we were removing the BC2 artifact to install fresh BC3 agent.
- We are not sure how the issue is reproducible too.

Further, please find below details of VM:
**Host:** Windows 2022 server
More VM details are attached in below screenshots:
![29](https://github.com/elastic/fleet-server/assets/77374876/a3524195-e497-4504-8180-5bace61ad697)
![30](https://github.com/elastic/fleet-server/assets/77374876/103767a3-3a71-4d8c-b7e0-deb50e9fa8b0)

Originally, the issue was reported on Windows 2022 server with 8GB RAM.

Please let us know if anything else is required from our end.
Thanks!

**Comment by michalpristas** [comment]
can you elaborate on this a bit: While testing we have observed this issue reproducible for elastic-agent that was installed on cloud build unknowingly.

cloud build is a linux build right?

**Comment by amolnater-qasource** [comment]
@michalpristas By cloud build we mean the production build deployed from https://cloud.elastic.co/deployments/

So far, we didn't observe anything like this on BC3.

**Comment by michalpristas** [comment]
was this reproducible on BC2 with some guarantees or accidental ?

**Comment by amolnater-qasource** [comment]
It was reproduced multiple times on self-managed 8.10.0 BC2 environment, while we had 1 agent and 1 fleet server installed.
- Logstash was also running on the same environment. 

**Reproduced:**
- Issue was reproduced while uninstalling fleet server installed using Quickstart and production mode.
- After reporting this issue, we observed the issue reproducible while uninstalling standalone agent.

However, the issue wasn't consistent and there are no exact steps.

Further, even while uninstalling Windows installed agent the issue was accidentally reproduced.

Please let us know if anything else is required from our end.
Thanks!

**Comment by amolnater-qasource** [comment]
Hi @michalpristas 

We have revalidated on recent few builds and the latest build too, however this issue is **no longer reproducible**.

Build details:
VERSION: 8.11.0 SNAPSHOT
BUILD: 67332
COMMIT: c20d177a036be73d7b1180dc17e644afa260994f

We have observed a separate issue for uninstallation reported at https://github.com/elastic/elastic-agent/issues/3479

Hence we are **closing** this issue for now and marking as **QA:Validated**.

Please let us know if anything else is required from our end.
Thanks!
