### ISSUE TITLE
Allow the snapshot version of the next minor release of Elastic Agent to connect.

### ISSUE THREAD

**Issue by cmacknz** [elastic/fleet-server#2960]
Fleet Server currently performs a version check when an agent connects, and prevents any agent whose version is greater than the version of Fleet Server from connecting. This helps enforce the API compatibility guarantees we currently have in place around breaking changes.

https://github.com/elastic/fleet-server/blob/4c279b0509a5b777f9add26214d1a51613f63f72/internal/pkg/api/userAgent.go#L40

However this problem causes issues during development of the next minor version of agent, in particular when the feature freeze for the next minor release occurs the version of Elastic Agent must be increased to produce the first snapshot build of the next minor. When this happens, the version of agent has been increased but there is no stack deployment with an equal version until the first snapshot build is produced.

This creates a period where all of the agent automated integration test will fail until the first snapshot build is produced, which has at points taken days. To make this process easier and automatic, let's allow the snapshot version of the next release of agent to connect to Fleet server. Snapshot versions are not officially supported for production use, so this should have no consequences besides making the feature freeze and development period easier to manage.

**Comment by cmacknz** [comment]
One complication with trying to do this only for snapshot versions is that the build constraint is on the user agent which drops the snapshot qualifier. For example with a locally built 8.10.0-SNAPSHOT agent the user agent is:

```
User-Agent: Elastic Agent v8.10.0
```

We would have to change the agent to include the snapshot qualifier if this strategy is to work.

**Comment by jlind23** [comment]
Instead of override the current User Agent value, can' we just add an extra field that would be useful to ensure BWC?

**Comment by cmacknz** [comment]
Yes a separate header is likely the best option looking at all the code that would need to be touched if we tried to fit this into the user agent header.

**Comment by michel-laterman** [comment]
We can likely change the constraint so that if the fleet-server is built with `SNAPSHOT=true` (or `DEV=true`) we allow different versions

**Comment by cmacknz** [comment]
That would be simpler, I ended up de-prioritizing this myself because I didn't like the complexity it introduced due to having to change both agent and fleet server.

Relaxing the constraint if fleet-server itself is also a snapshot makes sense to me and is (hopefully) simpler to do.
