### ISSUE TITLE
[Fleet]: Hosted fleet server remain stuck in updating state under Fleet>Agents tab on fresh deployment.

### ISSUE THREAD

**Issue by amolnater-qasource** [elastic/fleet-server#3003]
**Kibana Build details:**
```
VERSION: 8.11.0 SNAPSHOT
BUILD: 67640
COMMIT: 2174a95807a874b292fb3c821445df577ceac4e4
```

**Host OS:**  All

**Preconditions:**
1. 8.11.0 SNAPSHOT Kibana cloud environment should be available.

**Steps to reproduce:**
1. Navigate to Fleet>Agents tab and observe hosted fleet server remains stuck in Updating state.
2. Navigate to Agent details tab and observe error:
`Actions: fail to communicate with Fleet Server API client hosts: all hosts failed: 1 error occurred`

**What's working fine:**
- No error in Agent installation is observed.

**Screenshot:**
![image](https://github.com/elastic/fleet-server/assets/77374876/c7e79a3f-408c-4e81-ad46-b408e76ca352)

**Expected Result:**
Hosted fleet server should get Healthy under Fleet>Agents tab on fresh deployment.

**Agent Json:**
[af33101f98e5-agent-details.zip](https://github.com/elastic/fleet-server/files/12799819/af33101f98e5-agent-details.zip)

**Logs:**
[elastic-agent-diagnostics-2023-10-04T05-58-00Z-00.zip](https://github.com/elastic/fleet-server/files/12799831/elastic-agent-diagnostics-2023-10-04T05-58-00Z-00.zip)

**Comment by amolnater-qasource** [comment]
@manishgupta-qasource Please review.

**Comment by manishgupta-qasource** [comment]
Secondary review for this ticket is Done

**Comment by cmacknz** [comment]
Should be fixed with https://github.com/elastic/elastic-agent/commit/e8dca50386c3c99b779deec4a0779cf3416aeb65.

Closing, this will not be fixed until a new snapshot image is built but it should be fixed in the first 8.11 and 8.10.3 build candidates.

**Comment by amolnater-qasource** [comment]
Hi @cmacknz 

Thank you for the update.

We have revalidated this issue on latest 8.11.0 SNAPSHOT and found it fixed now.

**Observations:**
- Hosted fleet server remains Healthy under Fleet>Agents tab on fresh deployment.

**Screenshot:**
![image](https://github.com/elastic/fleet-server/assets/77374876/b3d8f7d5-3798-4f1e-8db7-0d46eb3db202)


**Build details:**
VERSION: 8.11.0 SNAPSHOT
BUILD: 67705
COMMIT: 5b1ae6683f34087836868fd2daca7cb22c0daaea

Hence we are marking this issue as **QA:Validated**.

Thanks!

**Comment by harshitgupta-qasource** [comment]
### `Bug Conversion`

- Test-Case not required as this particular checkpoint is already covered in the following testcase:
   - https://elastic.testrail.io/index.php?/cases/view/149907
 
Thanks!
