### ISSUE TITLE
Fix HTTP responses on client disconnects and review logging levels

### ISSUE THREAD

**Issue by joshdover** [elastic/fleet-server#3010]
We're seeing a situation where APM traces are indicating that Fleet Server returned a 503, however proxy logs these requests are a 499 - client disconnected. Though the response code is never really returned to the client, the classification of this as a 503 affects SLOs that use APM trace data.

We think that Fleet Server's default handling of `context.Canceled` errors is too wide here, and assumes we'd only get a context cancelation due to the server shutting down: https://github.com/elastic/fleet-server/blob/c247401b112de8be2062a90efa2704fa31be19f7/internal/pkg/api/error.go#L74-L82

Related, finding the cause of this was difficult (and still sort of a guess) likely because we're only logging at debug level. All 500+ errors need to be logged at least at info, but most likely at error.

### Requirements
- First, verify that this theory is correct by enabling request logs and/or APM traces and having a client disconnect from a checkin (enroll an Agent and then shut it down while it's checking in)
- Correctly handle client disconnects and report a 499 in request logs and APM traces
- Use a more specific error handler for server shutdowns to return 503s
- Review all error handlers in `internal/pkg/api/error.go` and make sure that all 500+ errors log at least at info level

**Comment by juliaElastic** [comment]
Checked that the only other debug level is 429
```
{
			ErrorThrottle,
			HTTPErrResp{
				http.StatusTooManyRequests,
				"TooManyRequests",
				"too many requests",
				zerolog.DebugLevel,
			},
		},
```

**Comment by juliaElastic** [comment]
Tested locally by changing log level to warn, the context canceled error is indeed logged as 503

```
09:08:07.561 ERR Dispatch abort response error.message="context canceled" action=fleet_search ecs.version=1.6.0 mod=bulk refresh=false rtt=263.72525 service.name=fleet-server service.type=fleet-server
09:08:07.562 DBG unsubscribe coord=0 ctx="policy agent monitor" ecs.version=1.6.0 fleet.agent.id=d8bb310d-9669-42fa-8146-fddbbc803a81 fleet.policy.id=0122fda0-61fb-11ee-95e9-8b5751f613c4 rev=0 service.name=fleet-server service.type=fleet-server
09:08:07.563 WRN HTTP request error error.message="fetchAgentPendingActions: context canceled" ecs.version=1.6.0 event.duration=535771000 http.request.id=01HBZHG97FW36T0Q1T5ZHAVB6T http.response.status_code=503 server.address= service.name=fleet-server service.type=fleet-server
09:08:07.563 INF 503 HTTP Request client.address=192.168.178.216:51339 ecs.version=1.6.0 event.duration=536287000 fleet.apikey.id=FzIY_4oB3ZNBSE2MHHPZ http.request.body.bytes=732 http.request.id=01HBZHG97FW36T0Q1T5ZHAVB6T http.request.method=POST http.response.body.bytes=78 http.response.status_code=503 http.version=1.1 server.address= service.name=fleet-server service.type=fleet-server tls.established=false url.full=/api/fleet/agents/d8bb310d-9669-42fa-8146-fddbbc803a81/checkin
```
