### ISSUE TITLE
Able to Install agents more than the limit set in Fleet server integration.

### ISSUE THREAD

**Issue by dikshachauhan-qasource** [elastic/fleet-server#303]
**Kibana version:**
7.13 BC3 Kibana Cloud Production environment 

**Host OS and Browser version:**
Linux, All

**Preconditions**
1.  Fresh newly created 7.13 BC3 Kibana Cloud Production environment should be available.
```
BUILD 40647
COMMIT ac09c73a4a7998c770b50d39177c22036ae14375
Artifact page: https://staging.elastic.co/7.13.0-100107e6/summary-7.13.0.html
```
2.  **A new policy having fleet server integration with limit on TCp connections should be available on cloud.**

**Steps to reproduce:**
1. Login to Kibana cloud environment.
2. Go to Agents tab. 
3. Go to 'Add agent' flyout, after clicking on generate token, use the command provided at step4 and install agents more than the limit server in fleet server integration.
4. Observe, all agent gets successfully installed and visible on Agents tab.

**Actual Result:**
Able to Install agents more than the limit set in Fleet server integration.

**Expected result:**
Error message should be displayed to user.

**Screenshots:** 
![image](https://user-images.githubusercontent.com/72375798/116534335-04c44d80-a900-11eb-80fb-340134500843.png)

Reference link:
https://github.com/elastic/fleet-server/issues/121

@scunningham Please let us now if merges for above are not available.

**Comment by dikshachauhan-qasource** [comment]
@manishgupta-qasource Please review

**Comment by manishgupta-qasource** [comment]
Reviewed & assigned to @EricDavisX

**Comment by scunningham** [comment]
To be clear, max connections does not prevent a customer from install more than N agents.  It prevents more than N agents from long polling at once on a specific fleet server.

This is assuming above manipulates the following.

https://github.com/elastic/fleet-server/blob/master/example/fleet-server-100.yml#L27

The total number of connections allowed on the interface at one time is specified here:

https://github.com/elastic/fleet-server/blob/master/example/fleet-server-100.yml#L23

This is generally larger than the max long poll to allow for artifacts.

**Comment by EricDavisX** [comment]
I was guessing it was not distinct named connections, but rather concurrent connections currently polling, as Sean notes.  I submit we could use a unit-test to validate this as it is potentially arduous to validate it via live testing.   @scunningham @ph we can close this if we think it is working, and log a new ticket for the test work on FS side if you agree?  

Before that though do we need to inspect the above code links on a live system to see the policy and whether Agent is respecting the policy citation? That isn't 100% clear to me, yet.

@dikshachauhan-qasource thanks for logging and bringing it up.

**Comment by dikshachauhan-qasource** [comment]
Hi @EricDavisX 

Thank you for the feedback. 

Further, it could be better if anybody can confirm how to validate above functionality, if required to test at our end.

Thanks
QAS

**Comment by EricDavisX** [comment]
I don't know if it will be feasible to test manually. Let us presume the Engineering team has or will cover this with automation, you can validate via the UI that it can be modified and saved, but we can leave the efficacy of the setting to the team.  Please update test content.

@ph I'll assign you for follow up, if that is ok.

**Comment by ph** [comment]
This look ok to me, to close, and with the load testing we are doing this should be raised if anything bad is happening.

**Comment by dikshachauhan-qasource** [comment]
Hi @ph thanks for the confirm on its coverage being help by load testing team.

Please let us know if anything related is required to verify at our end.

cc @EricDavisX 

Thanks
QAS
