### ISSUE TITLE
Error message: failed on waiting for global checkpoints advance

### ISSUE THREAD

**Issue by ruflin** [elastic/fleet-server#304]
I'm currently running a setup on Cloud QA with 7.13.0-SNAPSHOT (builds from yesterday) and from time to time the following error shows up in the error logs:

```
failed on waiting for global checkpoints advance
```

The error does not happen constantly but still shows up from time to time (see below)

![Screenshot 2021-04-29 at 13 53 52](https://user-images.githubusercontent.com/244900/116546876-74334080-a8f2-11eb-8df2-76b2c0a5f2c3.png)

Here is where this logged: https://github.com/elastic/fleet-server/blob/cb8aa6c08b238632d09241327fc164ae9bff3f69/internal/pkg/monitor/monitor.go#L247

Likely related, there is also the error around failing to checking for new docs.

I'm filing this issue to better understand why this is happening. Is it expected to happen, could we maybe add more details to the error log to help with debugging? Should it be on this log level etc? So far it did not seem to have impacted my setup.

**Comment by ruflin** [comment]
@aleksmaus You might be able to share more insights here.

**Comment by aleksmaus** [comment]
@ruflin that log should have the error details (error from Elasticsearch), it's not on the screenshot.
Could you post the details? 
The monitor logs the error from Elasticsearch and continues monitoring. Do we need to change the log level?

**Comment by aleksmaus** [comment]
Looks like error from transport:
```
read tcp 172.17.0.15:33658->172.23.180.83:9244: read: connection reset by peer
```

Current long poll request passes 5 minutes timeout by default to the request:
https://github.com/elastic/fleet-server/blob/master/internal/pkg/es/fleet_global_checkpoints.go#L91

https://github.com/elastic/fleet-server/blob/2716a45dd64e05fcc49763905fd1ea20168c466d/internal/pkg/monitor/monitor.go#L27


The long poll http transport timeout is 10 mins by default:
https://github.com/elastic/fleet-server/blob/13a5550c51ea65b491be3e9df21f55dd6071a1bb/internal/pkg/config/output.go#L25

https://github.com/elastic/fleet-server/blob/13a5550c51ea65b491be3e9df21f55dd6071a1bb/internal/pkg/config/output.go#L115

Expected the server to reply within specified 5 mins for the long poll request.

The monitor will proceed with another long poll request after this error.

Should we change the long poll timeout interval? Or not log this particular error?

**Comment by ruflin** [comment]
It seems like this is the connection between fleet-server and ES. @aleksmaus can confirm.

If we retry, maybe only log it on the info level instead of error? Do we expect this to happen from time to time?

**Comment by aleksmaus** [comment]
@ruflin we do not control when the server resets the connection on us. I can reduce the timeout from 5 min to 4min if there is a proxy in between that cuts it at 5 mins.
There might be other errors from ES that we probably still want to log at Error level, so leaning towards changing the timeout if it is set too close to the proxy default timeout.

**Comment by scunningham** [comment]
Still routes through the proxy, no?

**Comment by ruflin** [comment]
@scunningham I think the answer is yes.
