### ISSUE TITLE
[Fleet] Error triggered by the bulker seems not captured in APM

### ISSUE THREAD

**Issue by nchaulet** [elastic/fleet-server#3079]
## Description 

This probably need more investigation but it seems errors happening in the bulker and resulting in a 500 are not captured as error and not shown in the Errors tab of the APM UI.

**Comment by nchaulet** [comment]
@michel-laterman I looked at last weeks errors on apm QA and looks like there in an error for each failed transaction request, so closing this one

**Comment by michel-laterman** [comment]
Great to hear!
