### ISSUE TITLE
Enrich traces and request logs with Elasticsearch error details

### ISSUE THREAD

**Issue by joshdover** [elastic/fleet-server#3098]
We want to avoid being paged for Elasticsearch problems that the Fleet team cannot take any action on. In order to filter these alerts from our SLOs and/or route these pages to the Elasticsearch team, we need to enrich our observability data with more details about the Elasticsearch error that caused a request to fail. This will allow us to distinguish between real Fleet related problems that we can solve (eg. misconfigured ES URL or service token) from Elasticsearch or other infrastructure problems that we cannot take action on.

We should add a field that helps us do this to all traces and request logs.

TODO: fill in list of ES errors that we can safely ignore

**Comment by juliaElastic** [comment]
@joshdover I'm wondering where the `request` type [APM events](https://overview.elastic-cloud.com/app/r/s/MXMVA) are coming from, are they sent from fleet-server or proxy? 
I'm asking because I haven't found any of this logging in fleet-server, only seeing `StartTransaction` calls with `bulker`.
I'm also not seeing any logged errors in fleet-server logs in the same timeframe: https://overview.elastic-cloud.com/s/platform-ingest/app/r/s/d4m6J

**Comment by joshdover** [comment]
We wrap the `chi` router here with middleware provided by the APM go agent which automatically provides the default request transactions: https://github.com/elastic/fleet-server/blob/a465d093a882d8b4a9ec1ae97d8494b0d2f9ae39/internal/pkg/api/router.go#L23-L26

I believe from somewhere in https://github.com/elastic/fleet-server/blob/a465d093a882d8b4a9ec1ae97d8494b0d2f9ae39/internal/pkg/api/error.go#L519 we could do something like `apm.TransactionFromContext(r.Context()).SetLabel('elasticsearch_error_type', 'foo')`

> For those ES connection errors I'm seeing this in `error.message`: `read tcp 10.2.4.8:49270->10.253.48.33:443: read: connection reset by peer`

These tcp/connection level errors aren't so obvious to classify. It could be a temporary network issue, an ES or proxy pod got killed or shutdown, or ES or the proxy timed out (though I would expect the proxy to return a 504 if ES times out).

I think we can classify this type of error as a `connection_reset` and the decide at the SLO/alerting level what we will include or exclude as something we can take action on. That way we can make adjustments without having to deploy code changes.

**Comment by joshdover** [comment]
> We should also enrich the actual status code, now there is only `transaction.result: HTTP 5xx`, we might want to differentiate errors based on the status code.

I believe this already exists on some `http.*` field.
