### ISSUE TITLE
Report remote output health

### ISSUE THREAD

**Issue by juliaElastic** [elastic/fleet-server#3116]
Related to https://github.com/elastic/kibana/issues/104986
Follow up after https://github.com/elastic/fleet-server/pull/3051#issuecomment-1820648919

In the original plans of remote ES output, we planned to make Fleet Server status degraded if a remote ES output is not accessible, however this has too large impact, so we decided to do output health reporting separately.

Implementation tasks:
- Report periodic health updates per remote output to `logs-fleet_server.output_health-default` data stream or `metrics-*`
  - Check if privileges are needed in ES for fleet-server service account to write to these data streams, and kibana_system to read it ([metrics privilege](https://github.com/elastic/elasticsearch/pull/100574) already exists for kibana_system)
  - Add ILM/DLM
- From Fleet UI, read this data stream and show error status on Output UI

**Comment by juliaElastic** [comment]
I picked this up as I think this is require to roll out remote ES: https://github.com/elastic/fleet-server/pull/3051#issuecomment-1829894290

**Comment by juliaElastic** [comment]
Raised a few prs, I have the base functionality working, with some notes/suggestions here:, as the design doc was not very detailed regarding the UX: https://github.com/elastic/kibana/pull/172181
I'll continue to add tests, feel free to comment.

**Comment by juliaElastic** [comment]
@amolnater-qasource This enhancement is related to Remote ES output, adding a health reporting for remote outputs.
See screenshots and verification steps here: https://github.com/elastic/kibana/pull/172181

**Comment by amolnater-qasource** [comment]
Hi @juliaElastic 

Thank you for the update.

We have revalidated this issue on latest 8.12.0 Snapshot kibana cloud environment and found it **working fine**:

**Observations:**
- Unhealthy badge is visible with invalid Remote Elasticsearch output.
- Appropriate error message is displayed while editing invalid Remote Elasticsearch output.
- Healthy badge is visible with valid Remote Elasticsearch output.
- Healthy message is also displayed while editing valid Remote Elasticsearch output.

**Screenshot:**
![image](https://github.com/elastic/fleet-server/assets/77374876/723d2f40-76f1-40eb-ab72-5448574adcae)

![image](https://github.com/elastic/fleet-server/assets/77374876/7b0098cb-d895-4b08-833d-c528578aa4ee)

![image](https://github.com/elastic/fleet-server/assets/77374876/14d13bb0-24e0-48ef-a53a-699d0ffc53fd)

![image](https://github.com/elastic/fleet-server/assets/77374876/8c54915e-8109-4e1b-bfe3-6030a5f18591)


**Build details:**
VERSION: 8.12.0 SNAPSHOT
BUILD: 69787
COMMIT: ff04f68ab0e6d82b91b30dea13810225efc6c606

Hence we are marking this as **QA:Validated**, further we will create the testcases for these changes under https://github.com/elastic/kibana/issues/104986

Thanks!
