### ISSUE TITLE
Fleet Server 8.11.1 Not Showing v8.11.1 For Agent Upgrade in List in Kibana Fleet UI

### ISSUE THREAD

**Issue by ChestoOfGlen** [elastic/fleet-server#3119]
On version 8.11.1 of the Elastic stack, we have noticed that we cannot select v8.11.1 to upgrade an agent to, the latest option is only v8.11.0.

This is an example where you can see our Fleet Server and an Elastic Agent (deployed on Kubernetes and managed by ECK) are both on v8.11.1, however when selecting one of our machines to upgrade from v8.8.1 you can see that the latest version available is v8.11.0.

![image](https://github.com/elastic/fleet-server/assets/37160206/48219aa4-7e1f-4e89-bf7a-958fac30d337)

I note that the release notes for v8.11.0 mention a known issue that v8.11.0 is not in the list, however as can be seen in my screenshot that is not quite the case.
![image](https://github.com/elastic/fleet-server/assets/37160206/2e68e14a-ec02-4bbc-9c48-b68ce19c11f8)

I also note that there is an existing post in the Elastic Discuss Forum for this same issue. I am not that original poster, however I am encountering that same issue: https://discuss.elastic.co/t/elastic-agents-dont-see-upgrade-available-in-kibana/347271

**Comment by jlind23** [comment]
@ChestoOfGlen thanks for raising this, according to https://github.com/elastic/kibana/issues/169825#issuecomment-1810198567 it looks like this affected both `8.11.0` and `8.11.1`. @kilfoyle could you help us update the release note please?
cc @kpollich

**Comment by kpollich** [comment]
Yes the same issue is present in 8.11.1, but one version increased. e.g. 8.11.1 is not available in the agent dropdown on stack version 8.11.1.

This is fixed by https://github.com/elastic/kibana/pull/170974, and the workaround documented in the release notes is still applicable with the versions incremented.

**Comment by kilfoyle** [comment]
Here's a PR to update the docs: https://github.com/elastic/ingest-docs/pull/711
@kpollich Can you please take a look when you have a minute?

**Comment by michel-laterman** [comment]
Looks like this was a known issue that effected 8.11.1 as well
