### ISSUE TITLE
Error: fail to enroll: fail to execute request to fleet-server: http: server gave HTTP response to HTTPS client

### ISSUE THREAD

**Issue by saniray** [elastic/fleet-server#3149]
Hey there!
I've installed Elasticsearch 8.11 version. And everything is good, however I matched a problem while installing elastic-agent for connecting with fleet-server. I have a next error message:
`..{"log.level":"info","@timestamp":"2023-12-06T23:51:40.285Z","log.origin":{"file.name":"cmd/enroll_cmd.go","file.line":479},"message":"Starting enrollment to URL: https://1x.x.x.x:8220/","ecs.version":"1.6.0"}
................................................................................................................................................................................................................................Error: fail to enroll: fail to execute request to fleet-server: http: server gave HTTP response to HTTPS client
For help, please see our troubleshooting guide at https://www.elastic.co/guide/en/fleet/8.11/fleet-troubleshooting.html
 FAILED
Error: enroll command failed for unknown reason: exit status 1
For help, please see our troubleshooting guide at https://www.elastic.co/guide/en/fleet/8.11/fleet-troubleshooting.html
`

I've tried to find a lot of ways to solve this problem and I failed.
Please, If someone know how to fix it please help me!

This is my initial commands
`curl -L -O https://artifacts.elastic.co/downloads/beats/elastic-agent/elastic-agent-8.11.0-linux-x86_64.tar.gz
tar xzvf elastic-agent-8.11.0-linux-x86_64.tar.gz
cd elastic-agent-8.11.0-linux-x86_64
sudo ./elastic-agent install --url=https://x.x.x.x:8220 --enrollment-token=R0VaeE9vd0JvVnRmeTI5eFYtZFc6LUJaU1p4blJRbk91NW5DWncwdEYyQQ== --insecure`

Thanks a lot!

**Comment by michel-laterman** [comment]
Just to understand, you are having an issue enrolling another agent into fleet, correct?

The agent is using:
```sh
sudo ./elastic-agent install --url=https://x.x.x.x:8220 --enrollment-token=R0VaeE9vd0JvVnRmeTI5eFYtZFc6LUJaU1p4blJRbk91NW5DWncwdEYyQQ== --insecure
```

How was fleet-server provisioned?
I think you used an `http` address instead of `https`

**Comment by saniray** [comment]
@michel-laterman Thank you for answering my question. I used https. However, I have already solved the problem. The problem was with the proxy server :)
