### ISSUE TITLE
successfully connect to Fleet Server but did not receive data

### ISSUE THREAD

**Issue by cloud-chang** [elastic/fleet-server#3190]
## OS
```
lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 22.04 LTS
Release:        22.04
Codename:       jammy
```
## install Elastic
```
wget -qO - https://artifacts.elastic.co/GPG-KEY-elasticsearch | sudo gpg --dearmor -o /usr/share/keyrings/elasticsearch-keyring.gpg
sudo apt-get install apt-transport-https
echo "deb [signed-by=/usr/share/keyrings/elasticsearch-keyring.gpg] https://artifacts.elastic.co/packages/8.x/apt stable main" | sudo tee /etc/apt/sources.list.d/elastic-8.x.list

sudo apt-get update && sudo apt-get install elasticsearch
```
### elasticsearch.yml
```
network.host: 0.0.0.0
xpack.security.authc.api_key.enabled: true
```
systemctl restart elasticsearch
![image](https://github.com/elastic/elastic-agent/assets/147620110/00731285-9f23-4880-8458-92af06002a91)

## install Kibana
```
sudo apt-get update && sudo apt-get install kibana
```

### kibana.yml
```
server.host: "0.0.0.0"
```
sudo systemctl start kibana
![image](https://github.com/elastic/elastic-agent/assets/147620110/de20fde8-6a8d-448b-b1a8-d3cd9f5b04d3)
![image](https://github.com/elastic/elastic-agent/assets/147620110/2914cff8-3e6f-48fd-ad27-f7d5787b288b)

## Fleet Server
![image](https://github.com/elastic/elastic-agent/assets/147620110/beaf860b-c7e0-4fc9-a58f-06df423a69da)
![image](https://github.com/elastic/elastic-agent/assets/147620110/50e49140-37e4-4805-8113-2d608b938feb)

### install server on this host (124.222.18.X)
```
sudo ./elastic-agent install \
  --fleet-server-es=https://10.0.12.12:9200 \
  --fleet-server-service-token=AAEAAWVsYXN0aWMvZmxlZXQtc2VydmVyL3Rva2VuLTE3MDMzMjUzOTMyNjE6b05TMFBjYTVTRTZ3UjZpN1FiN2N2UQ \
  --fleet-server-policy=fleet-server-policy \
  --fleet-server-es-ca-trusted-fingerprint=00c7a760b4ed7747ca7b64e122b2f6ffd230118ccb6981c26121edd3337af0eb \
  --fleet-server-port=8220

---> Elastic Agent has been successfully installed.
```
![image](https://github.com/elastic/elastic-agent/assets/147620110/4e726dbf-2f38-4f02-a371-ef8d7af5adb2)

![image](https://github.com/elastic/elastic-agent/assets/147620110/528e3cf5-fb17-4f9f-ba33-3afe862743ec)

## Install the agent on my own personal computer(Mac)
![image](https://github.com/elastic/elastic-agent/assets/147620110/7802816b-7793-420d-abf6-f9344f99b61d)
![image](https://github.com/elastic/elastic-agent/assets/147620110/bac55ae4-dbaf-44d0-a58c-084a3d3fed18)

```
sudo ./elastic-agent install --url=https://124.222.18.X:8220 --enrollment-token=aXBraWxvd0JXbk5WVXlibi1DQXM6R1dRWTlUazZSclNybGQ2S0RWdF9qUQ== --insecure

--> Elastic Agent has been successfully installed.
```
Elasticsearch did not receive data： 
![image](https://github.com/elastic/elastic-agent/assets/147620110/851d75c3-a146-44a7-baf1-48b6b27d91ec)
![image](https://github.com/elastic/elastic-agent/assets/147620110/1c1befad-b6bf-40f2-aea3-141311d006b1)
![image](https://github.com/elastic/elastic-agent/assets/147620110/89e6eb73-3a86-429b-80f0-a2a03ff70b70)
![image](https://github.com/elastic/elastic-agent/assets/147620110/58aed303-21ce-4d8d-a71e-6ace82320bae)
![image](https://github.com/elastic/elastic-agent/assets/147620110/aa5aeee6-e53a-43bb-9031-11cab3eaee83)
![image](https://github.com/elastic/elastic-agent/assets/147620110/51284a5f-3164-43e0-a856-0478e2fc300d)
![image](https://github.com/elastic/elastic-agent/assets/147620110/ba635429-803c-4166-b8b9-628282e12ee0)

still not work:
![image](https://github.com/elastic/elastic-agent/assets/147620110/7dde1cbc-04e1-49ab-afa9-2a5c7722d2b9)

**Comment by michel-laterman** [comment]
Hi, let's keep the issue to the [discuss thread](https://discuss.elastic.co/t/elastic-agent-successfully-connect-to-fleet-server-but-elasticsearch-did-not-receive-data-bug/349887) for now

**Comment by cloud-chang** [comment]
[elastic-agent-diagnostics-2023-12-27T06-09-10Z-00.zip](https://github.com/elastic/fleet-server/files/13776032/elastic-agent-diagnostics-2023-12-27T06-09-10Z-00.zip)


@michel-laterman  discuss thread can not upload log files

**Comment by cloud-chang** [comment]
![91703435828_ pic](https://github.com/elastic/fleet-server/assets/147620110/fca7c393-3004-4464-acb6-567c483cdf17)

**Comment by cloud-chang** [comment]
If Fleet Server and Agent are installed on the same machine without any issues，it won't work if it's on different machines

**Comment by michel-laterman** [comment]
This slipped my notice, i'll take a look today

**Comment by dharick04** [comment]
even I'm also facing this error , how to resolve issues,  I'm trying to get log in different network.

![Uploading image.png…]()
<img width="269" alt="ELK" src="https://github.com/elastic/fleet-server/assets/58396545/2189cc86-556f-4fb4-ac66-0b69e2c02a59">

**Comment by dharick04** [comment]
> This slipped my notice, i'll take a look today.
> 
> EDIT: It looks like there is a network restriction/firewall/proxy that is interfering with the agent->Elasticsearch communications. The *beat processes on the elastic-agent instance are unable to connect to ES, there are timeout errors:
> 
> ```json
> {"log.level":"error","@timestamp":"2023-12-27T05:48:16.034Z","message":"Failed to connect to backoff(elasticsearch(https://10.0.12.12:9200)): Get \"https://10.0.12.12:9200\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)","component":{"binary":"metricbeat","dataset":"elastic_agent.metricbeat","id":"system/metrics-default","type":"system/metrics"},"log":{"source":"system/metrics-default"},"log.logger":"publisher_pipeline_output","log.origin":{"file.line":148,"file.name":"pipeline/client_worker.go"},"service.name":"metricbeat","ecs.version":"1.6.0","ecs.version":"1.6.0"}
> ```
> 
> It looks like the instance where fleet-server is installed does not have the same restriction (it is able to connect to ES).

Hi @michel-laterman  sir,
I also facing same issue , i have change elastic-agent.yml (outputs:
  default:
    type: elasticsearch
    hosts: [publicIP:9200]) , i want to monitor outside of the network.
    
 still  I'm unable to get log sir

**Comment by jlind23** [comment]
Closing this as outdated, if the problem occurs again please open a topic in [discuss](https://discuss.elastic.co/)
