### ISSUE TITLE
logs consistency

### ISSUE THREAD

**Issue by michel-laterman** [elastic/fleet-server#3239]
fleet-server has log lines with inconsistent attributes.

For example:

https://github.com/elastic/fleet-server/blob/5e8a1e9f9f3cf9d7b97e8c41a7c6611b414eca55/internal/pkg/policy/policy_output.go#L54

https://github.com/elastic/fleet-server/blob/5e8a1e9f9f3cf9d7b97e8c41a7c6611b414eca55/internal/pkg/policy/self.go#L265

Both refer to policy outputs but are named different things. 
We should go through the codebase and try to make these more consistent (following ecs)

**Comment by juliaElastic** [comment]
Few more places to make consistent:
The action type is logged under different fields:
```
ack event
actionId

Action delivered to agent on checkin
id
```

Found that the policy id is also logged under different names:
```
New revision of policy received and added to the queue
fleet.policy.id

Policy coordinator added a new policy revision
policy_id
```

**Comment by juliaElastic** [comment]
Revision_idx fields are changed in this pr https://github.com/elastic/fleet-server/pull/3234

**Comment by juliaElastic** [comment]
Found one more place where revision and coordinator idx is logged under a different name:
https://github.com/elastic/fleet-server/blob/618952027110aae6fe4369ff625f178fcf17f836/internal/pkg/api/handleCheckin.go#L768-L769
