### ISSUE TITLE
Migrate from fleet-ci bucket to Ingest bucket

### ISSUE THREAD

**Issue by jlind23** [elastic/fleet-server#3240]
In our Buildkite pipelines we are still relying on the fleet-ci buckets for DRA stage.
We need to stop using this one and rather start pushing artifacts to the ingest specific pipelines.
This change should be then back ported to the following branches:

- [x] 7.17
- [x] 8.12

https://github.com/elastic/fleet-server/blob/5e8a1e9f9f3cf9d7b97e8c41a7c6611b414eca55/.buildkite/hooks/pre-command#L11C1-L11C27

**Comment by jlind23** [comment]
@mrodm Looking at this it should be as easy as updating the vault value used to retrieved the gcs bucket name right?

Bucket name is retrieved here: https://github.com/elastic/fleet-server/blob/5e8a1e9f9f3cf9d7b97e8c41a7c6611b414eca55/.buildkite/hooks/pre-command#L65

And bucket is used here: https://github.com/elastic/fleet-server/blob/5e8a1e9f9f3cf9d7b97e8c41a7c6611b414eca55/.buildkite/scripts/common.sh#L105

**Comment by mrodm** [comment]
It's also used in `get_bucket_uri()`:
https://github.com/elastic/fleet-server/blob/5e8a1e9f9f3cf9d7b97e8c41a7c6611b414eca55/.buildkite/scripts/common.sh#L121

The problem of updating the value directly in that vault path is that it could not be tested if that works or not in advance, and other builds (of any branch or PR) could fail. 

It is needed to ensure that the current service account has the required permissions to upload/write files into the new bucket. The service account used here is retrieved from this vault path:
https://github.com/elastic/fleet-server/blob/5e8a1e9f9f3cf9d7b97e8c41a7c6611b414eca55/.buildkite/hooks/pre-command#L9

NOTE: Just realized that `get_bucket_uri()` function is duplicated in `buildkite/scripts/common.sh`, and it could be removed one of them:
https://github.com/elastic/fleet-server/blob/5e8a1e9f9f3cf9d7b97e8c41a7c6611b414eca55/.buildkite/scripts/common.sh#L119-L139
