### ISSUE TITLE
[Fleet] provide way to automatically unenroll inactive agents.

### ISSUE THREAD

**Issue by n0othing** [elastic/fleet-server#3321]
Relates to https://github.com/elastic/kibana/issues/143455 + https://github.com/elastic/fleet-server/issues/2063

Today we require users to manually unenroll inactive agents. This can be problematic for environments that spin up thousands of ephemeral agents, creating a massive backlog of inactive agents that need to be unenrolled. While this can be tackled with an external script, it'd be better to provide a way to automate this directly in the application.

**Comment by michel-laterman** [comment]
I don't think we should implement this; we previously had this as a feature (with the `unenroll_timeout` setting), but it caused a lot of SDHs from the customers.

See https://github.com/elastic/fleet-server/issues/2063
cc @kpollich

**Comment by juliaElastic** [comment]
more recent issue to address this: https://github.com/elastic/kibana/issues/179399
