### ISSUE TITLE
Fleet-Server not starting up on 8.14-SNAPSHOT on cloud (intermittent)

### ISSUE THREAD

**Issue by juliaElastic** [elastic/fleet-server#3328]
Reported on cloud deployments in 8.14-SNAPSHOT version, that Fleet-Server not starting up with the following error:
```
Waiting on default policy with Fleet Server integration
```

When looking at the `.fleet-policies` index, it seems that the coordinator is not picking up the policy changes.
```
GET .fleet-policies/_search?q=policy_id:policy-elastic-agent-on-cloud
{
  "size": 10, 
  "_source": ["revision_idx", "coordinator_idx"],
  "sort": [
    {
      "revision_idx": {
        "order": "desc"
      }
    }
  ]
}

  "hits": [
      {
        "_index": ".fleet-policies-7",
        "_id": "413fe8ef-8abf-5a6b-bce7-6a530f665c65",
        "_score": null,
        "_source": {
          "revision_idx": 5,
          "coordinator_idx": 0
        },
        "sort": [
          5
        ]
      },
```

In fleet-server logs, there are no errors, but it seems the coordinator doesn't pick up the change.

![image](https://github.com/elastic/kibana/assets/90178898/04db6a2a-6faf-4f9e-a1b3-ffa50bc104bf)

Deployment where the issue is reproduced: https://admin.found.no/deployments/19ed6657cf3dccbba39c8b6faacb67f9

**Comment by michel-laterman** [comment]
I've been unable to recreate this with a self managed cluster using the latest snapshots locally

**Comment by juliaElastic** [comment]
Were you able to reproduce on cloud? I'm wondering if the issue is specific to cloud preconfiguration or some other cloud specific config.

**Comment by juliaElastic** [comment]
I found this warning in the logs, which is interesting because the fleet-server host points to a https host url. Not sure if it has anything to do with the coordinator. Comes from this code: https://github.com/elastic/fleet-server/blob/main/internal/pkg/api/server.go#L113
Admin url: https://admin.found.no/deployments/19ed6657cf3dccbba39c8b6faacb67f9/elasticsearch/console
```
Exposed over insecure HTTP; enablement of TLS is strongly recommended
```

**Comment by juliaElastic** [comment]
It seems that the issue is only reproducible with terraform, for some reason the hardware template `gcp-io-optimized-v3` has this issue, changing the hardware template to `gcp-storage-optimized` works.

**Comment by kuisathaverat** [comment]
@juliaElastic it started happening with `gcp-storage-optimized` template too

**Comment by juliaElastic** [comment]
In the latest cluster, I'm seeing that the coordinator was not started, and not picking up the policy changes.

This is how the logs should look like (took from a healthy cluster):
<img width="1474" alt="image" src="https://github.com/elastic/fleet-server/assets/90178898/43e6aa51-2aca-49a6-bf86-69b08a07f1bf">

In the unhealthy cluster it looks like this:
<img width="1496" alt="image" src="https://github.com/elastic/fleet-server/assets/90178898/2f8cf18a-8eba-42dd-98bd-81e6e119e8c1">

**Comment by juliaElastic** [comment]
I'm missing this from ES logs (other `.fleet-` indices are created):
```
[instance-0000000000] [.fleet-agents-7] creating index, cause [auto(bulk api)], templates [], shards [1]/[1]
```

**Comment by juliaElastic** [comment]
Seeing this error in the logs, not sure if it is related:
<img width="1450" alt="image" src="https://github.com/elastic/kibana/assets/90178898/1e496c79-ca12-41c4-b467-08ba97d353a9">

**Comment by cmacknz** [comment]
That [error](https://github.com/elastic/fleet-server/blob/28f84331f907ba69c214b074c50eb3456c883870/internal/pkg/monitor/monitor.go#L293-L296) comes from the index monitor used to watch for [fleet actions](https://github.com/elastic/fleet-server/blob/28f84331f907ba69c214b074c50eb3456c883870/internal/pkg/server/fleet.go#L501-L509) and [policy updates](https://github.com/elastic/fleet-server/blob/28f84331f907ba69c214b074c50eb3456c883870/internal/pkg/server/fleet.go#L469-L477).

Getting regular i/o timeouts from those index monitors seems like it could cause this.

**Comment by kuisathaverat** [comment]
it still happens in 8.14.0-BC1

**Comment by kpollich** [comment]
@kuisathaverat - Hey Ivan, this should be fixed by https://github.com/elastic/kibana/pull/181624. Are you still seeing this behavior on the latest snapshot build?

**Comment by kuisathaverat** [comment]
We have tested these Docker images that contain the fix, the issue persists

https://artifacts-api.elastic.co/v1/versions/8.15.0-SNAPSHOT/builds/8.15.0-00251ce4
https://artifacts-api.elastic.co/v1/versions/8.15.0-SNAPSHOT/builds/8.15.0-81021969

```

{"log.level":"info","@timestamp":"2024-04-29T06:41:29.462Z","message":"Waiting on default policy with Fleet Server integration","component":{"binary":"fleet-server","dataset":"elastic_agent.fleet_server","id":"fleet-server-default","type":"fleet-server"},"log":{"source":"fleet-server-default"},"ecs.version":"1.6.0","service.name":"fleet-server","service.type":"fleet-server","state":"STARTING","ecs.version":"1.6.0"}
```

**Comment by juliaElastic** [comment]
Looking at the latest instance logs, I'm seeing something strange, it says `"HTTP":{"Enabled":false`, while I don't see any ssl or certificates in the config. @michel-laterman Do you think this could be the issue?

Admin link: https://admin.found.no/deployments/15e5bafefa50a01b902fb82c919495fa/integrations_server
Fleet server logs: https://platform-logging.kb.us-west2.gcp.elastic-cloud.com/app/r/s/4OkCu
```
{"log.level":"info","@timestamp":"2024-04-29T07:45:26.834Z","message":"initial server configuration","component":{"binary":"fleet-server","dataset":"elastic_agent.fleet_server","id":"fleet-server-default","type":"fleet-server"},"log":{"source":"fleet-server-default"},"new":{"Fleet":{"Agent":{"ID":"","Logging":{"Level":""},"Version":"8.14.0"},"Host":{"ID":"","Name":""}},"HTTP":{"Enabled":false,"Host":"localhost","Port":5066,"SecurityDescriptor":"","User":""},"Inputs":[{"Cache":{"APIKeyJitter":0,"APIKeyTTL":0,"ActionTTL":0,"ArtifactTTL":0,"EnrollKeyTTL":0,"MaxCost":0,"NumCounters":0},"Monitor":{"FetchSize":0,"PolicyDebounceTime":0,"PollTimeout":0},"Policy":{"ID":""},"Server":{"Bulk":{"FlushInterval":250000000,"FlushMaxPending":8,"FlushThresholdCount":2048,"FlushThresholdSize":1048576},"CompressionLevel":1,"CompressionThresh":1024,"GC":{"CleanupAfterExpiredInterval":"30d","ScheduleInterval":3600000000000},"Host":"0.0.0.0","Instrumentation":{"APIKey":"","APIKeyPath":"","Enabled":true,"Environment":"","GlobalLabels":"deploymentId=15e5bafefa50a01b902fb82c919495fa,deploymentName=test-images-ess-gttya,organizationId=2870499056","Hosts":["https://7831d021b36b4d53b849aae988d3b6db.apm.us-west2.gcp.elastic-cloud.com:443"],"SecretToken":"m4KjsiPiBAz0w7wW81","SecretTokenPath":"","TLS":{"ServerCA":"","ServerCertificate":"","SkipVerify":false},"TransactionSampleRate":""},"InternalPort":8221,"Limits":{"AckLimit":{"Burst":8000,"Interval":250000,"Max":16000,"MaxBody":2097152},"ActionLimit":{"Burst":100,"Interval":250000,"Max":0,"MaxBody":0},"ArtifactLimit":{"Burst":8000,"Interval":250000,"Max":16000,"MaxBody":0},"CheckinLimit":{"Burst":8000,"Interval":250000,"Max":80000,"MaxBody":1048576},"DeliverFileLimit":{"Burst":40,"Interval":100000000,"Max":80,"MaxBody":0},"EnrollLimit":{"Burst":200,"Interval":10000000,"Max":400,"MaxBody":524288},"GetPGPKey":{"Burst":25,"Interval":5000000,"Max":50,"MaxBody":0},"MaxAgents":0,"MaxConnections":0,"MaxHeaderByteSize":8192,"PolicyLimit":{"Burst":1,"Interval":250000,"Max":0,"MaxBody":0},"PolicyThrottle":0,"StatusLimit":{"Burst":200,"Interval":5000000,"Max":400,"MaxBody":0},"UploadChunkLimit":{"Burst":40,"Interval":3000000,"Max":80,"MaxBody":4194304},"UploadEndLimit":{"Burst":40,"Interval":2000000000,"Max":80,"MaxBody":1024},"UploadStartLimit":{"Burst":40,"Interval":2000000000,"Max":80,"MaxBody":5242880}},"PGP":{"Dir":"/usr/share/elastic-agent/data/elastic-agent-372976/components/elastic-agent-upgrade-keys","UpstreamURL":"https://artifacts.elastic.co/GPG-KEY-elastic-agent"},"Port":8220,"Profiler":{"Bind":"localhost:6060","Enabled":false},"Runtime":{"GCPercent":0,"MemoryLimit":0},"StaticPolicyTokens":{"Enabled":false,"PolicyTokens":null},"TLS":null,"Timeouts":{"CheckinJitter":30000000000,"CheckinLongPoll":300000000000,"CheckinMaxPoll":3600000000000,"CheckinTimestamp":30000000000,"Drain":10000000000,"Idle":30000000000,"Read":60000000000,"ReadHeader":5000000000,"Write":600000000000}},"Type":""}],"Logging":{"Files":null,"Level":"info","Pretty":false,"ToFiles":true,"ToStderr":true},"Output":{"Elasticsearch":{"Headers":{"X-Elastic-App-Auth":"eyJhbGciOiJSUzI1NiJ9.eyJpc3MiOiIyNzY3MzQ0NTg5MjA0Mzc0ODk4OTEzZTIwOGU5M2E4NyIsInN1YiI6IjcxNGQ5NWQ4ZWY3OTQ0ZjZiYmI5NmY1YzIwOTg1ODc5IiwiYXVkIjoiMjc2NzM0NDU4OTIwNDM3NDg5ODkxM2UyMDhlOTNhODciLCJpYXQiOjE3MTQzNzY3MTIsImtpbmQiOiJhcG0ifQ.lMGUgcKsyTVGcc6iC9AL_E0xaTnqyPgztxcK7DqArAsm8kYuYRsb5rXheGY7o6Uli9s03FsGYj4_4r8h3KUMXditUZQyk0ADmr7BiNnDDAdBfIwI6uElG0Mwn3pV4BWkb4vpJHjRb0qwz-sP1T3LXlhI18GREwCZ4-a-psgAVSu2_Kp8V8V_m0MdXn0-gfbB0sApCq4-iJAZeiLsaUvxr24PtZ2gf6xdZx9hXvIPGwMTK9VpYTYtGkwotYnVkNTVkhT8lJA4So-A5GlxD9UD4gdBBqxNAcjdFSd3v-TLO7wCsJhSxOjAEyJQeIp89zoUbSuSv8NC4eKGOzoZ1w-Rew"},"Hosts":["2767344589204374898913e208e93a87.containerhost:9244"],"MaxConnPerHost":128,"MaxContentLength":104857600,"MaxRetries":3,"Path":"","Protocol":"http","ProxyDisable":false,"ProxyHeaders":{},"ProxyURL":"","ServiceToken":"[redacted]","ServiceTokenPath":"","TLS":{"CASha256":null,"CATrustedFingerprint":"","CAs":["/app/config/certs/internal_tls_ca.crt"],"Certificate":{"Certificate":"","Key":"","Passphrase":"","PassphrasePath":""},"CipherSuites":null,"CurveTypes":null,"Enabled":null,"Renegotiation":"never","VerificationMode":"full","Versions":null},"Timeout":90000000000},"Extra":null}},"ecs.version":"1.6.0","service.name":"fleet-server","service.type":"fleet-server","ecs.version":"1.6.0"}
```

**Comment by michel-laterman** [comment]
The top level `http.*` attributes are for the http metrics listener that fleet-server starts. 
The TLS info (if passed by elastic-agent) should be in `Inputs.Server.TLS`

**Comment by juliaElastic** [comment]
One more thing I noticed, on the deployment where we have the issue it says `APM instrumentation enabled`, while on the healthy one it is `APM instrumentation disabled`, both are using the same oblt-cli `ess` template.

**Comment by juliaElastic** [comment]
My theory is that fleet-server is stuck [here](https://github.com/elastic/fleet-server/blob/main/internal/pkg/api/server.go#L113) and waits for `Inputs.Server.TLS` to be set in the config to continue. For the healthy clusters I'm seeing `Inputs.Server.TLS` set. I'm not sure which component sets this config, but it doesn't seem to always happen.

**Comment by nchaulet** [comment]
Looking at fleet server code there we should never log `Waiting on default policy with Fleet Server integration` unless fleet server we start fleet server without a policyID configured, it looks like the healthy deployments never have that log line.

@michel-laterman how can we get an empty policy ID here https://github.com/elastic/fleet-server/blob/382222f60da77b4b263a37b0a10110f876f09c66/internal/pkg/server/fleet.go#L492 ? Do we have anything in Fleet-server that could mutate the config?  or any ideas why this is not configured?

Also it seems it's something we introduced in 8.14 as if you search for `Waiting on default policy with Fleet Server integration` in all cloud logs excluding 8.14+ version we do not have results

**Comment by juliaElastic** [comment]
I think this log message comes because there is no fleet server policy with `coordinator_idx:1` that fleet-server waits for.

**Comment by nchaulet** [comment]
> I think this log message comes because there is no fleet server policy with coordinator_idx:1 that fleet-server waits for.
Good idea to hardcode some delay, though I'm not sure where to put that in the code.
Added sleep in a few places but still can't reproduce the issue: https://github.com/elastic/fleet-server/pull/3507/files


I think the log message is because Fleet server is not correctly configured (without policy ID)  if the policy ID was correct it should log `Waiting on policy with Fleet Server integration: %s` not `Waiting on default...` https://github.com/elastic/fleet-server/blob/382222f60da77b4b263a37b0a10110f876f09c66/internal/pkg/policy/self.go#L200

Looking at the timeline you provided it could be related to that PR https://github.com/elastic/fleet-server/pull/3277 I added some test here and it seems we are loosing the policy ID https://github.com/elastic/fleet-server/pull/3508

**Comment by juliaElastic** [comment]
good catch, I think the merge config overrides the `new.Inputs.Policy.ID` field:
https://github.com/elastic/fleet-server/blob/528e4ae06e2d67be9771eca1f8625cfa3232a494/internal/pkg/server/agent.go#L429-L436

**Comment by nchaulet** [comment]
> @nchaulet tested locally with your agent_test and adding policy to the instrumenation config works. I'm not sure if there is a way to add all keys from input (like spread operator in ts ...input)
cc @michel-laterman

if we merge with different option than `config.DefaultOptions` we could maybe have a proper merge.

**Comment by juliaElastic** [comment]
> if we merge with different option than `config.DefaultOptions` we could maybe have a proper merge.

You are right, the default options have this: `ucfg.FieldReplaceValues("inputs"),` so I guess this is why `inputs` was replaced, and not merged.

**Comment by kpollich** [comment]
@juliaElastic - Can this issue be closed as the fix has been verified?

**Comment by juliaElastic** [comment]
We can close it, will verify again in cloud when BC3 is built.

**Comment by kpollich** [comment]
Added test issue here: https://github.com/elastic/fleet-server/issues/3516. Let me know if I've captured this issue accurately, and feel free to comment on that issue to clarify further.

**Comment by juliaElastic** [comment]
While trying to verify the fix in BC3 build, I'm noticing something strange.
[This deployment](https://admin.found.no/deployments/3abb33f6b6a2fb5683d4ea73abf81e15/integrations_server) has a healthy fleet-server, but APM instrumentation is not enabled, even though the monitoring config is added to the agent config.
The cloud `elastic-agent.yml` has this config:
```
agent.monitoring.traces: true
agent.monitoring.apm.hosts:
- "[https://7831d021b36b4d53b849aae988d3b6db.apm.us-west2.gcp.elastic-cloud.com:443](https://7831d021b36b4d53b849aae988d3b6db.apm.us-west2.gcp.elastic-cloud.com/)"
agent.monitoring.apm.secret_token: "XXX"
agent.monitoring.apm.global_labels.deploymentId: "3abb33f6b6a2fb5683d4ea73abf81e15"
agent.monitoring.apm.global_labels.deploymentName: "ess-igkfx"
agent.monitoring.apm.global_labels.organizationId: "2870499056"
```
But still in fleet-server logs tracing is not enabled.
I think there might still be a bug in merging the APM Config. Investigating.

**Comment by michel-laterman** [comment]
@juliaElastic, How are you enabling instrumentation?

I've tried to use the terraform in `dev-tools/cloud/terraform` to deploy + update a cluster to include APM config.
I deploy a test cluster, then alter the deployment resource in `main.tf` to include
```
observability = {
  deployment_id = "self"
}

integrations_server = {
  config = {
    docker_image = local.docker_image_ea
    user_settings_yaml =  "agent.monitoring.enabled: true\nagent.monitoring.traces: true\nagent.monitoring.apm.hosts: [\"https://f3bdc01d3e5b44c093ce34ad3f4ad006.apm.us-west2.gcp.elastic-cloud.com:443\"]\nagent.monitoring.apm.secret_token: REDACTED"
  }
 }
```
Where the host in the list is the cluster's own address; then update the deployment.

The logs you posted had one entry where tracing (in fleet-server) was enabled; however i don't see that in my deployment.
I'm trying to use a custom image that has additional logging around loading APM instrumentation: https://github.com/elastic/fleet-server/pull/3523
[link to deployment](https://admin.found.no/deployments/f3fe569ae5b7d020861c428265e20c17/integrations_server)
[link to logs](https://platform-logging.kb.us-west2.gcp.elastic-cloud.com/app/r?l=DISCOVER_APP_LOCATOR&v=8.13.2&lz=N4IgjgrgpgTgniAXKANgQwHYHMJq1JEFCAYygwIBpxp5CoyA6E4gZwBdZEAzAZgCMAJiQAMARkG8oAVn4AWOaICcvMrzlpJ3DYJEiAbCAC%2B1VgHsY7JAG1rIAALsAlgFsoHNC4AOIamlYkIAC6QdQkZsQuGKw2IKywAG5OTBieVCAAFuzsXoww7l5m0VCMHuwQrAD64YLpbqyseOkMJU7R7JhkviAUAO6MAJIYXhDsrIwAyomwg%2B0wEG4YHc5FjACiqfwoUILB1G21AB6ELBWcMAC0TUsXAFTdbecJaCiEaKNm3dxOKOcxiNZQG4OkhQAcoMdECBThxYFd8Dd7n4UE5%2FEgMBAUChqBQsGhOEhuC94tRBE5GlsdoTiVBqOw4F4CFCvBkYP50gBrKAIKHxGBJFJpbpeNBslz%2FUCQWA8kDcbZQdgXPkJWDGEw0aWgkAufEkDKVFls%2BJa5XJEqpNyEOVQBVK6YwNXUAAkZSZoA4FiZIDQXi8E2WBCMJiBCrQWvBkOhbHO8PIiqR3pRaMQGKxOKgeIJiHY81pIDJFO2ux4NLpDK9hvZ3S5MvqjXwwtFnglGroUIAShAMBg2lgAARFPuFFEkOB93pOdgZPsAMXl7D7U35sD7jwzbJWGEQQ4iyTgFyg6A4yVjNyKFxYZgguyD1ClbaBuv1leNyG17nrXs73d7A4wO5HMcJynWd50Xe1VyWdd8ScIpt2HPcDyPZwSFPRVz0va9HRAF0AxNdhPTeX1%2FXxQMjFCfN8TQAA1JwoF6AZiyjM44WueNumcNx20wBs324GAzBcQgACYRGEuQLhEaRJP0AAVUTEDEMRED0Rg9BEAAtDjPihUTxMk6SDHkkRFOkFSRDUvQtPVfJ%2BPcDIhieF4tWeYgmX0dSRGoEUKiZHNoCDIA%3D%3D)

**Comment by juliaElastic** [comment]
There is a default APM config added to non-snapshot version deployments (documented [here](https://github.com/juliaElastic/kibana/blob/4bba3cdafb48f49daecbda38940facab7ccb39fd/x-pack/plugins/fleet/dev_docs/apm_tracing.md#cloud-configuration)), Alex Piggott confirmed that the apm config is there in the elastic-agent.yml, but somehow not reaching the agent. I don't know if this is a new or existing bug, but previously when we reproduced the bug in this issue, I've seen `APM instrumentation enabled` in the agent logs.

**Comment by kuisathaverat** [comment]
>Also looked at monitoring-oblt and not seeing any fleet-server traces from the past 5 months 

IIRC we have only 30 days of APM retention

I enable it on edge-oblt and it seems to work

```
agent.monitoring.enabled: true
agent.monitoring.traces: true
agent.monitoring.apm.hosts: ["https://redacted.apm.us-west2.gcp.elastic-cloud.com:443"]
agent.monitoring.apm.secret_token: REDACTED
```

**Comment by juliaElastic** [comment]
Okay, I was able to enable fleet-server traces with a config added to user settings here: https://admin.found.no/deployments/6bd9a5eb5220c666921a8f44501d938e/integrations_server

```
"user_settings_yaml": "agent.monitoring.enabled: true\nagent.monitoring.traces: true\nagent.monitoring.apm.hosts: [\"https://monitoring-oblt.apm.us-west2.gcp.elastic-cloud.com:443\"]\nagent.monitoring.apm.secret_token: VwTJMFNGvRaiwVdxnW\n"
```

https://monitoring-oblt.kb.us-west2.gcp.elastic-cloud.com/app/apm/traces/explorer/waterfall?comparisonEnabled=false&detailTab=timeline&environment=ENVIRONMENT_ALL&kuery=&query=labels.deploymentId:6bd9a5eb5220c666921a8f44501d938e%20AND%20service.name:%22fleet-server%22&rangeFrom=now-1M&rangeTo=now&showCriticalPath=false&traceId=0795f17f69b1236e0bc451d69cfa1a53&transactionId=0795f17f69b1236e&type=kql&waterfallItemId=&searchTerm=service.name

**Comment by juliaElastic** [comment]
Created a follow up issue for the missing traces. Closing this as the original issue is resolved.
