### ISSUE TITLE
[Deployment]: Hosted fleet server is not available under Agents tab for 7.17.20

### ISSUE THREAD

**Issue by amolnater-qasource** [elastic/fleet-server#3440]
**Deployment Links:**
- https://cloud.elastic.co/
- Los Angeles (us-west2)

**Description:**
- Hosted fleet server is not available under Agents tab.

**Note:**
The issue is consistently reproducible on all 7.17.20 deployments.

**Screenshots:**
![image](https://github.com/elastic/fleet-server/assets/77374876/3b119d04-ddb8-4fd0-a1c3-433ba28af85e)

![image](https://github.com/elastic/fleet-server/assets/77374876/01689212-6575-48e1-b8ae-1bb8b7d9d5ef)

**Comment by amolnater-qasource** [comment]
@manishgupta-qasource Please review.

**Comment by manishgupta-qasource** [comment]
Secondary review for this ticket is Done

**Comment by jlind23** [comment]
@amolnater-qasource looking now.

**Comment by amolnater-qasource** [comment]
Hi @jlind23 

Thank you for looking into this issue.

We are not able to access logs for kibana instance due to lack of admin access.

Further we have observed that this issue is also reproducible while upgrading from 7.17.19>7.17.20.
- Latest version hosted agent is not installed on 7.17.20 after upgrade.

**Screenshot:**
![image](https://github.com/elastic/fleet-server/assets/77374876/1e2f2978-f0a3-46e1-ad55-fe4baa23bda5)

Please let us know if anything else is required from our end.
Thanks!

**Comment by jlind23** [comment]
@amolnater-qasource After checking it looks like the asc file does exist on other environment, hence it is probably due to the file not being officially published. Closing this issue as it is not a real one for now.
