### ISSUE TITLE
[8.14.0]: Hosted fleet server gets offline under Agents tab.

### ISSUE THREAD

**Issue by amolnater-qasource** [elastic/fleet-server#3465]
**Deployment Links:**
- https://cloud.elastic.co/
- Los Angeles (us-west2)

**Description:**
- Hosted fleet server gets offline on 8.14.0-SNAPSHOT under Agents tab.

**Build details:**
VERSION: 8.14.0
BUILD: 73341
COMMIT: 3670d5eafc018d87748265279507e4778f790006

**Note:**
The issue is consistently reproducible on all 8.14.0-SNAPSHOT deployments.

**Screenshots:**
![image](https://github.com/elastic/fleet-server/assets/77374876/60e1e512-b07c-439b-b0a8-dc93ab328518)
![image](https://github.com/elastic/fleet-server/assets/77374876/2e57ea63-9025-4872-a931-f2df03fb7ab0)

**Comment by amolnater-qasource** [comment]
@manishgupta-qasource Please review.

**Comment by manishgupta-qasource** [comment]
Secondary review for this ticket is Done

**Comment by jlind23** [comment]
@amolnater-qasource @manishgupta-qasource there is an ongoing investigation on this.
cc @pchila @pierrehilbert

**Comment by michel-laterman** [comment]
https://github.com/elastic/fleet-server/pull/3469 is an update to the fleet-server to update the elastic-agent-libs so we don't have an unpack error that we've seen in our snapshots.

the agent may have also contributed to this issue: https://github.com/elastic/elastic-agent/pull/4583

**Comment by amolnater-qasource** [comment]
Hi Team,

We have revalidated this issue on latest 8.14.0 SNAPSHOT and found this issue as **fixed now**.

**Observations:**
- Hosted fleet server remains Healthy under Agents tab.

**Screenshot:**
![image](https://github.com/elastic/fleet-server/assets/77374876/ff7cfe8d-46e8-4059-8aab-92301b3b47b2)


**Build details:**
VERSION: 8.14.0 SNAPSHOT
BUILD: 73512
COMMIT: 9369f3a4df8a10ccf5e293ff7410e3688cb567d0


Hence, we are closing and marking this issue as **QA:Validated**.
Thanks!
