### ISSUE TITLE
How to handle simultaneous mismatched Fleet Server

### ISSUE THREAD

**Issue by blakerouse** [elastic/fleet-server#347]
### Overview

This is to just start a discuss on if Fleet Server should do anything in the case that there are multiple Fleet Servers and they are not the same version.

### What constitutes not a same version?

I think that is clear. Any major.minor difference is a version difference that matters. Patch version differences should not affect operation, but you still want to get every Fleet Server to the latest patched version.

### What could Fleet Server do?

Fleet Server could notice a version mismatch with its other versions and stop accepting connects on the ones that are older versions. While this does force Elastic Agent's to always connect to the newer Fleet Servers, in a rolling upgrade scenario this would be bad behavior. As soon as the one of the Fleet Servers upgraded all the others would turn off, forcing all clients to reconnect to the new Fleet Server and it might not handle the load.

I think overall it would be best if Fleet Server does nothing, maybe possible log a message, but otherwise this mismatch should be show to the user in Kibana and allow the users to fix the issue. Just allow the Fleet Server to stay on and working until the user takes an action.

**Comment by ruflin** [comment]
Maybe we could specify the acceptable mismatch to be 1 minor version? As you described, there will be a mismatch during rolling upgrades.

An other issue here is that in case one fleet-server was updated but an other one not, the Elastic Agent connected to the newer server could upgrade. That case I think we should handle in Kibana and not allow Elastic Agents to upgrade to a newer version then the oldest Fleet-Server.

How do we handle the upgrade during majors? I expect we will also support a rolling upgrade?

**Comment by blakerouse** [comment]
Fleet Server version does not dictate the upgrading of Elastic Agent's only Kibana does that. So even if one Fleet Server is newer that doesn't mean that the other Elastic Agent's can upgrade.

Kibana will have to add guards here I believe to ensure that no Elastic Agent's are upgraded until all the Fleet Server's are upgraded. Otherwise the case is that Elastic Agent could actually upgrade before Fleet Server, which would prevent it from even communicating.

I feel majors are the same as minors when it comes to upgrades.

**Comment by jlind23** [comment]
Closing this one as outdated, we will reopen it later if required.
cc @ycombinator
