### ISSUE TITLE
Implement/fix e2e bootstrap tests

### ISSUE THREAD

**Issue by michel-laterman** [elastic/fleet-server#3552]
Our e2e tests have a couple of test suites which are currently disabled:
- https://github.com/elastic/fleet-server/blob/main/testing/e2e/agent_container_test.go
- https://github.com/elastic/fleet-server/blob/main/testing/e2e/agent_install_test.go

We should fix or reimplement these tests to ensure that the fleet-server repo has an automated test to verify that the bootstrap behaviour works as expected when running under the elastic-agent.

**Comment by cmacknz** [comment]
I moved this issue into the current sprint, assuming it is the simpler of https://github.com/elastic/elastic-agent/issues/4769 to get working given the test already exists. Feel free to swap the order with https://github.com/elastic/elastic-agent/issues/4769 if that isn't true.

**Comment by cmacknz** [comment]
Actually since https://github.com/elastic/elastic-agent/pull/4643 isn't merged yet it would be nice to do https://github.com/elastic/elastic-agent/issues/4769 as part of that work. Swapping now.
