### ISSUE TITLE
[Windows vSphere host specific]: Unable to successfully install secondary agent on Windows

### ISSUE THREAD

**Issue by amolnater-qasource** [elastic/fleet-server#356]
**Kibana version:** 7.13.0 Snapshot Kibana cloud environment

**Host OS and Browser version:** Windows 10 x64, All

**Build Details:**
```
  Artifact link used: https://snapshots.elastic.co/7.13.0-7457d36a/downloads/beats/elastic-agent/elastic-agent-7.13.0-SNAPSHOT-windows-x86_64.zip
  Build: 40856
  Commit: 7f416a18f500794f9705085cf02f9299dcccc38d
```

**Preconditions:**
1. 7.13.0 Snapshot Kibana cloud environment should be available.
2. Windows 10 x64 Fleet Server must be installed on 7.13.0 snapshot. 

**Steps to reproduce:**
1. Login to Kibana environment.
2. Add Fleet Server host url under Fleet Settings: https://fleet-server-machine-ip:8220
2. Run agent install command for secondary Agent installation.
3. Observe following errors:
```
2021-05-17T02:03:36.935-0400    WARN    cmd/enroll_cmd.go:370   Remote server is not ready to accept connections, will retry in a moment.
2021-05-17T02:04:36.950-0400    INFO    cmd/enroll_cmd.go:377   Retrying to enroll...
```

**Expected Result:**
User should be able to install secondary agent with self created Windows 10 x64 fleet server.

**Fleet-Server Logs:**
[logs.zip](https://github.com/elastic/fleet-server/files/6491524/logs.zip)

**Note:**
- This issue is not observed for Fleet Servers installed on Linux (.tar), linux (.rpm) and MAC (.darwin).
- Network on both the Windows 10 x64 endpoints is working fine.

**Screenshot:**
![1](https://user-images.githubusercontent.com/77374876/118441309-a15f5b80-b706-11eb-94eb-10e317553e56.JPG)

**Comment by amolnater-qasource** [comment]
@manishgupta-qasource Please review.

**Comment by manishgupta-qasource** [comment]
Reviewed & Assigned to @EricDavisX

**Comment by EricDavisX** [comment]
Can you give stats for the Windows 10 host you are using for Fleet Server?  Memory + CPU and if it is a VM what are the stats of the host?  Is it in the Endgame vSphere cluster? I'd like to have the vm name and I'll check it out off line.  I have seen Windows working but will put it to my list to do an explicit test asap.

**Comment by amolnater-qasource** [comment]
Hi @EricDavisX 
Thanks for feedback, please find details of host VM below:
```
Windows 10 x64 v10272
CPU: 4
Memory: 8 GB
```
>Is it in the Endgame vSphere cluster?

Yes, from endgame vSphere cluster. Further, we will share the VM details separately.

Thanks 
QAS

**Comment by EricDavisX** [comment]
I'm seeing in the logs (in the Kibana UI even) that the Fleet server is in a bad state - that is what we need to research first, I think:
[elastic_agent][error] 2021-05-18T08:07:43-04:00 - message: Application: fleet-server--7.13.0[63313270-f619-4662-a7f2-2f864002a384]: State changed to FAILED: Error - could not start the HTTP server for the API: failed to listen on the named pipe \\.\pipe\default-fleet-server: open \\.\pipe\default-fleet-server: Access is denied. - type: 'ERROR' - sub_type: 'FAILED'

Maybe it recovers from there... hard to tell.

I'll post the whole log collected (via the UI) for Agent and Fleet Server interleaved:
[logs.log](https://github.com/elastic/fleet-server/files/6501942/logs.log)
`

**Comment by EricDavisX** [comment]
I'm also realizing this is intended as a proper test-signing (turned off) test vm, perhaps we have a signing problem.  I'll research this as well - could end up as a bug.

**Comment by EricDavisX** [comment]
I compared the testsigning status on my win 10 host and on Amols and it looks the same:
![Screen Shot 2021-05-18 at 11 06 14 AM](https://user-images.githubusercontent.com/12970373/118678749-45aad600-b7cb-11eb-834f-b62e8963ba17.png)

And I got the same error I was concerned about above, on my server that I stood up and was able to connect an Agent to this FS with a common command:
sudo ./elastic-agent install -f --url=https://10.0.6.208:8220 --enrollment-token=dTkasdfasdf==  --insecure

and it installed and came on line and healthy, though it is not sending data so I could research that, but it seems it is working better than Amol's existing host.  nothing determinate found, except that Win 10 is confirmed again that it should work / can work.

**Comment by EricDavisX** [comment]
I found in the logs that my agent was trying to connect to Amol's problematic fleet server, so I deleted the FS address in Kibana and installed and it worked.  we are still debugging what is specific about this VM or usage, but we proved SOME win 10 hosts can work, even if not all of them will / can.  

I'd like to pull in @blakerouse or @michalpristas to review the logs.zip Amol has attached to see if they show you anything helpful.  @ph @ruflin fyi.

**Comment by amolnater-qasource** [comment]
Hi @EricDavisX 
Thanks for the feedback. We have tried the same on various Windows 10 x64 VMs we have, however we are getting same issues.
We can share the IPs for those VMs if required. 

Thanks
QAS

**Comment by ruflin** [comment]
Can you check if you can reach the fleet-server status page from the Elastic Agent host machine through curl or similar? Maybe a firewall or something in between?

**Comment by amolnater-qasource** [comment]
Hi @ruflin 
Can you please share any specific commands required to get that?
As far as we have checked, Firewall status is "ON". 

Thanks

**Comment by blakerouse** [comment]
The following should do the trick or checking that it can communicate.

```
PS> Invoke-WebRequest -Uri https://10.0.6.208:8220/api/status
```

**Comment by amolnater-qasource** [comment]
Hi @blakerouse 
Thanks for sharing the command. Please find below screenshot for the same:
![1](https://user-images.githubusercontent.com/77374876/118930823-d9afa580-b963-11eb-96a3-609421724ec2.JPG)

cc: @ruflin 
Thanks
QAS

**Comment by amolnater-qasource** [comment]
Hi @EricDavisX 
We have revalidated this issue on Fleet Server installed on various other Window OS's other than Windows 10 x64 and observed similar Kibana connectivity issue while installing secondary agents to those fleet servers.

Please find logs for all the fleet servers attached below:
**Windows 7 x64 (version:10305) Fleet Server Logs:**
[Win 7 logs.zip](https://github.com/elastic/fleet-server/files/6513993/Win.7.logs.zip)

**Windows 8.1 x64 (version:10346) Fleet Server Logs:**
[Win 8.1 logs.zip](https://github.com/elastic/fleet-server/files/6513999/Win.8.1.logs.zip)

**Windows 2012 x64 (version:10305) Fleet Server Logs:**
[Win 2012 server logs.zip](https://github.com/elastic/fleet-server/files/6514004/Win.2012.server.logs.zip)

Please let us know if are missing anything.
Thanks
QAS

**Comment by ruflin** [comment]
It seems like something is blocking the request. If you run the same command on the machine that fleet-server is running but with the local IP / localhost instead, do you get a response?

You mentioned Kibana above, did you mean fleet-server?

**Comment by blakerouse** [comment]
@amolnater-qasource The first 2 in your latest screenshot shows that it can communicate. But because of self-signed certificates it fails (this is expected and okay). This means that those 2 can communicate.

The third one cannot communicate because it is missing the `:8220` port number.

Based on all the information here, it seems that the other host cannot communicate with that host over the provided IP:PORT number. I would expect this is the firewall. Try disabling the firewall on the host running the Fleet Server and see if it can then communicate.

**Comment by EricDavisX** [comment]
Thanks all.  I've spoken with Charlie who helps maintain our test vm (templates) and their configuration and who knows whats set up.  We can confirmed that:

Currently [the configuration on these templates in use by the test team are setup such that] the firewall configuration allows ingress for ssh, rdp, wman and leia.  [Note,] there may be one or two other ingress openings depending on what is needed for in band sensor deployment.  Egress should be wide open.

This would explain the behavior seen and we can take action further on 2 fronts:
 - change the manual test process to use templates that are set up with known required port ingress rules for 8220
 - update documentation on Fleet Server side to explicitly call out the need to open the desired port.

I'll reply back with ticket #s for these 2 when I get them into the system

**Comment by EricDavisX** [comment]
issue is crested for Sec Engg Prod team

**Comment by EricDavisX** [comment]
And I put a small 'suggestion' in to an open PR that the Docs team had for the FS settings, to alleviate this need - it is a small start at least.  docs can always be bettered! 
https://github.com/elastic/observability-docs/pull/673/files#r636286308

**Comment by amolnater-qasource** [comment]
Hi @EricDavisX 
Thanks for the feedback, we are successfully able to install secondary agent with Windows Fleet Server after opening ports.

**Steps followed:**
1. Setup windows fleet-server on 7.13.0 Kibana cloud environment.
2. Navigate to Firewall Advanced settings.
3. Add inbound rules> Port number> Add port: 8220.
4. Save the rule.
5. Run install command for secondary agent.
6. Observe secondary agent installed with Windows Fleet-Server.

Hence closing this out.

Thanks
QAS
