### ISSUE TITLE
[Deployment]: Hosted fleet server is not available under Agents tab for 7.17.22

### ISSUE THREAD

**Issue by amolnater-qasource** [elastic/fleet-server#3592]
**Deployment Links:**
- https://cloud.elastic.co/
- Los Angeles (us-west2)

**Description:**
- Hosted fleet server is not available under Agents tab.

**Note:**
The issue is consistently reproducible on all 7.17.22 deployments.

**Screenshots:**
![image](https://github.com/elastic/fleet-server/assets/77374876/9b06ebdd-da14-4175-afc5-d3d4d83815ac)
![image](https://github.com/elastic/fleet-server/assets/77374876/d9a6fd98-b5df-4b11-9f8b-d0a0c694558d)

**Comment by amolnater-qasource** [comment]
@manishgupta-qasource Please review.

**Comment by manishgupta-qasource** [comment]
Secondary review for this ticket is Done

**Comment by cmacknz** [comment]
Creating deployments shows:

```json
   "event": {
      "original": "2024-05-30T12:47:04.130Z\tERROR\temitter/controller.go:126\tFailed to render configuration with latest context from composable controller: fail to extract program configuration: invalid configuration missing outputs configuration"
    },
```

This isn’t even getting to Fleet server, it failing early in agent: https://github.com/elastic/beats/blob/0162f4546eb4c50fc24743de3f9b0b05a6a95570/x-pack/elastic-agent/pkg/agent/program/program.go#L134-L144

```go
func groupByOutputs(single *transpiler.AST) (map[string]*transpiler.AST, error) {
    const (
        outputsKey = "outputs"
        outputKey  = "output"
        inputsKey  = "inputs
```

**Comment by ycombinator** [comment]
Looking at recent commits to `beats` in `7.17`, [this PR](https://github.com/elastic/beats/pull/39586) is the only one that touches code, although the changes don't seem be directly related to this error.

**Comment by jlind23** [comment]
@ycombinator @cmacknz reverting the mentioned change worked as I have been able to spin up a 7.17.22 snapshot this morning.
<img width="1382" alt="Screenshot 2024-05-31 at 07 33 52" src="https://github.com/elastic/fleet-server/assets/43535167/393d6f5b-65d6-41b3-ade7-0586b02603cf">

**Comment by cmacknz** [comment]
Yes there has not been a new 7.17.22 BC, the next one is scheduled for June 6th.

Reverting https://github.com/elastic/beats/pull/39586 has downgraded several dependencies we bumped for security reasons, we should determine why that change has caused problems and fix it before the 7.17.22 release.

**Comment by jlind23** [comment]
@ycombinator could you please triage this and make this it gets the right assignee?

**Comment by jlind23** [comment]
Closing as fixed as Michel's PR was merged,
