### ISSUE TITLE
cloude2e tests skipped

### ISSUE THREAD

**Issue by michel-laterman** [elastic/fleet-server#3920]
The cloude2e tests are being skipped to allow work on main.

An ongoing issue with Kibana results in 9.x cloud deployments failing ([see issue](https://elasticco.atlassian.net/browse/CP-8540?focusedCommentId=168762).

Additionally previous runs of the step have been failing because the fleet-server endpoint is not a part of the terrafrom output once terraform has created a deployment, [issue here](https://elasticco.atlassian.net/browse/SRE-899?atlOrigin=eyJpIjoiMWZlN2I5ZDRmYTYxNDJiMjk1ZWM5Njg2OGExMDRlNzciLCJwIjoiamlyYS1zbGFjay1pbnQifQ).

The test step should be re-enabled once the Kibana issue is resolved, and we should verify that the test runs successfully once the cloud issue is resolved.

**Comment by ycombinator** [comment]
> The test step should be re-enabled once the Kibana issue is resolved, 

I'm tracking the resolution of the Kibana issue (or rather the deployment of the fix to ESS prod CFT region).  So I've assigned this issue here to me for now.
