### ISSUE TITLE
Return 503 Service Unavailable when unable to authenticate with Elasticsearch instead of 401

### ISSUE THREAD

**Issue by cmacknz** [elastic/fleet-server#3929]
- Relates https://github.com/elastic/elastic-agent/issues/5428

When we attempt to validate an agent's API key and cannot communicate with ES because Fleet Server's API key/service token is temporarily unavailable we return a 401 to Elastic Agents. This seems correct, but if it happens for 7 check ins in a row will cause the agent to automatically unenroll.

We should evaluate handling "cannot auth with ES" from "explicitly told API key was invalid" separately and returning a 503 when Fleet Server itself cannot auth with ES to avoid unintentional mass unenrollments.

The relevant code block is below: https://github.com/elastic/fleet-server/blob/6c144499dfacc53c45f2df1173345b8723e1db05/internal/pkg/apikey/auth.go#L34-L61

**Comment by blakerouse** [comment]
The actual lines in that block that are wrong are here:

https://github.com/elastic/fleet-server/blob/main/internal/pkg/apikey/auth.go#L54-L60
