### ISSUE TITLE
Introduce "max agents" config options

### ISSUE THREAD

**Issue by ruflin** [elastic/fleet-server#466]
fleet-server provides quite a list of config options to be tweaked: https://github.com/elastic/fleet-server/blob/master/fleet-server.yml#L24 For most standard users I would assume this is overwhelming. One of the factors driving all these config options is max number of agents that should connect to a fleet-server. This is likely a number that users might know. 

Can we provide good defaults for certain numbers / ranges of "max agents"? If a user sets "100" or "1000" internally the other values are automatically adjusted and optimised.

Of course there is much more variation and optimisation that needs to be done for expert users and these could use the existing config options. The above is to simplify it for most users.

**Comment by jlind23** [comment]
Rescoping it to 8.2 as discussed with @lykkin
