### ISSUE TITLE
Set up Fleet-Server automation in support of routine scale performance assessments

### ISSUE THREAD

**Issue by EricDavisX** [elastic/fleet-server#486]
This ticket is in support of regular assessment for scale guidance:
https://github.com/elastic/fleet-server/issues/134
 wherein we are citing to provide guidance to the team / documentation about scaling Fleet Server on Cloud. A separate issue exists for self-managed scale guidance.  

For this we'd ideally like to have confirmation and documentation on how to run and review the data as follows:

- [ ] Check with @elastic/observablt-robots if we do already have a framework for performance testing
- [ ] create automation framework to create scale test data that can be compared across builds / releaess
- [ ] confirm automation can be run as part of CI or with a specific PR trigger 'Jenkins run scale tests'
- [ ] document some best processes on how to assess the data generated in the test
- [ ] stretch goal - ideally we'd have additional automation to do the assessment and create a report

**Comment by EricDavisX** [comment]
Note we started investigating testing + automation for routine 'soak' tests of cloud based Fleet-Server container, that issue is here: https://github.com/elastic/obs-dc-team/issues/596 - noting it for the possible overlap, though the tests are very different.

**Comment by jlind23** [comment]
@ph should probably be included in your current proposal around testing.

**Comment by cachedout** [comment]
@jlind23 Not sure if you want to keep this issue open or not. We'll be building all of this as a part of https://github.com/elastic/observability-robots/issues/989 so this might be redundant.

**Comment by jlind23** [comment]
@cachedout thanks for the heads up. It is redundant indeed let me close this one.
