### ISSUE TITLE
Fleet Server policy may not be delivered under load

### ISSUE THREAD

**Issue by scunningham** [elastic/fleet-server#524]
fleet-server 7.14 

When the Fleet Server is under load, or misconfigured, it is often the case that the Agent supervising the Fleet Server cannot check in.  This is on account of the various throttles that were added to limit the number of connections and transactions on the server.  This is particularly problematic if we need to reconfigure the Fleet Server to fix these issues in the field.  With other Agents hammering the server, the new policies cannot roll out.

**Comment by jlind23** [comment]
Closing at it is fixed, related to: https://github.com/elastic/fleet-server/issues/741
