### ISSUE TITLE
Improve actions in the Elastic Agent

### ISSUE THREAD

**Issue by ruflin** [elastic/fleet-server#54]
The way actions work in Elastic Agent should be improved. Most of the work here probably must happen in the Elastic Agent itself. Filing it here for now as the new action implementation is driven by fleet server.

High level notes (needs more details):

* The agent side changes (as far as I understand):
    * action token exchange on checkin
    * agent actions routing (specifically for osquery in short term)
    * agent actions result/status/error forwarding from the "app" to the fleet server
    * the agent managing the Fleet Server launch

**Comment by james-elastic** [comment]
Another action routing in the short term would be for endpoint for the host isolation action

**Comment by james-elastic** [comment]
cc  @kevinlog

**Comment by aleksmaus** [comment]
> Another action routing in the short term would be for endpoint for the host isolation action

Yep. That's the idea. the action input id will correspond to the integration uuid and will be routed by the agent and is expected to receive the the action completion with possible errors


An example of action document
```
POST .fleet-actions/_doc/
{
  "action_id": "bc4cc421-32c5-494c-9868-1b2249cc8eac",
  "@timestamp": "2020-01-05T00:36:30Z",
  "expiration": "2021-01-25T00:36:30Z",
  "type" : "APP_ACTION",
  "input_id": "osquery",
  "agents": [
    "81d8f5f7-35fc-4ce1-892c-10a06f3cd9e8"
  ],
  "data" : {
    "commands" : [
      {
        "id": "93b576c6-d04b-4b0f-b9cb-faacd457a71e",
        "query" : "select * from temperature_sensors"
      }
    ]    
  }
}
```
where the ```data``` property is opaque to the agent is can be specific anything for the beat/app

And the example result document would something along these lines, example of osquery action
```
      {
        "_index" : ".ds-.fleet-actions-results-2021.01.05-000001",
        "_id" : "pnQd1HYBWwciv9s6j2u5",
        "_score" : 1.0,
        "_source" : {
          "action_id" : "bc4cc421-32c5-494c-9868-1b2249cc8eac",
          "agent_id" : "9a801b1b-c2a1-4215-8c70-f90e5f58ca21",
          "data" : {
            "commands" : [
              {
                "command_id" : "93b576c6-d04b-4b0f-b9cb-faacd457a710",
                "started_at" : "2021-01-05T19:54:33.179786Z",
                "completed_at" : "2021-01-05T19:54:34.151249Z"
              },
              {
                "command_id" : "b3b576c6-d04b-4b0f-b9cb-faacd457a71a",
                "started_at" : "2021-01-05T19:54:34.151252Z",
                "completed_at" : "2021-01-05T19:54:34.151429Z",
                "error" : "no such table: foo"
              }
            ]
          },
          "error" : "no such table: foo",
          "@timestamp" : "2021-01-05T19:54:35Z"
        }
      },
      ```

**Comment by ph** [comment]
This is all done in the current iteration of the Elastic Agent.
