### ISSUE TITLE
Support multiple output types

### ISSUE THREAD

**Issue by andresrc** [elastic/fleet-server#550]
**Describe the enhancement:**

Currently Fleet Server only supports policies that use ES as the output. It needs to support other kinds of outputs, such as Logstash and Kafka.

**Describe a specific use case for the enhancement or feature:**

Shipping data indirectly through logstash or kafka is a very common scenario.

**Comment by nimarezainia** [comment]
**API Key Management in Fleet Server**
For better security on the Elastic Agent endpoints each agent should have a uniquely scoped API key for remote Elasticsearch clusters (the same as the main Elasticsearch endpoint that Fleet Server already uses). The difference is that multiple Fleet Server’s will share a service token when the Elasticsearch output is a remote cluster versus the main cluster where each Fleet Server will have a unique service token.

The shared service token for the Fleet Server should be scoped to only provide the functionality that the Fleet Server needs to create API keys (access to other indexes is not needed and should not be given).

Fleet Server would store the created API Key for remote Elasticsearch clusters in its main Elasticsearch cluster indexes.



**Implementation Stages**
- Modify Fleet Server to use a service token that is passed down from an output defined in a policy.
- Modify Fleet Server to store multiple API keys for an Elastic Agent (at the moment it can only store one)
- Add a limited scoped service token to Elasticsearch (elastic/fleet-remote) that only gives the ability to create/delete API keys.
-

**Comment by blakerouse** [comment]
## Implementation Plan

Below documents how this will be implemented in Fleet Server.

### Index Changes

Idea is that only the `.fleet-agents` index will be modified. The `default_api_key`, `default_api_key_id`, and `policy_output_permissions_hash` will be migrated to a new `api_keys` field inside the `.fleet-agents` index.

Each document in the `.fleet-agents` index will have a list of API keys that have been generated for that agent. The following inner document will be inside the `api_keys` field.

```
  "agent-api-key": {
      "title": "Agent API Key Metadata",
      "description": "A generate API key for an Agent",
      "type": "object",
      "properties": {
        "output_type": {
          "description": "The output type for this API key.",
          "type": "string",
        },
        "output_id": {
          "description": "A unique ID of the output.",
          "type": "string",
        },
        "output_key": {
          "description": "The unique key of the output from the policy.",
          "type": "string",
        },
        "api_key_id": {
          "description": "The unique ID of the created API key.",
          "type": "string",
        },
        "api_key": {
          "description": "The actual API key passed to the agent.",
          "type": "string",
        },
        "permission_hash": {
          "description": "The hash of the permissions used to create the API key passed to the agent.",
          "type": "string",
        },
        "created_at": {
          "description": "The creation time of the API key.",
          "type": "string"
          "format": "date-time"
        }
      },
    },
```

### Coordinator v1

Currently there is coordinator v0 that does nothing. This will add the first version of the coordinator that will monitor each output defined in a policy and will inject the ID of the cluster into the policy `output_id` for those with `type: elasticsearch`. This will ensure that if the ID of the cluster changes (aka. IP address changes to point to new cluster) then a new policy revision by trigger, requiring all existing Elastic Agent's on that policy to regenerate the API key.

**Comment by andresrc** [comment]
@blakerouse is #713 related to this? Is there anything missing here for 7.16?

**Comment by blakerouse** [comment]
@andresrc Everything is here for 7.16.

**Comment by andresrc** [comment]
shall we close this issue then?

**Comment by blakerouse** [comment]
This issue is more about support other output types, like Logstash and Kafka. We still do not support that, we also still do not support a remote Elasticsearch cluster.

I think we should keep it open.

**Comment by blakerouse** [comment]
@jlind23 Set it to 8.0-candidate.

**Comment by jlind23** [comment]
@lykkin i know you have been a bit busy on fleet server bugfix but is there any progress here? What is our confidence level to make it happened in 8..0.0?

**Comment by jlind23** [comment]
@ruflin @nimarezainia what should we do with this? Policies can already support multiple output right?
We should rather focus on supporting other output rather than multiple output am I wrong?

**Comment by ruflin** [comment]
I suggest to close this issue as it is too generic. I rather have a vey specific one to for example support Logstash are a second Elasticsearch output to a remote cluster. This will make sure we have more focused discussions.

**Comment by joshdover** [comment]
@blakerouse I'm tracking down dependencies for supporting the Logstash output. Is there anything remaining on the control plane team for this? If so, I'm happy to open a placeholder for us to track this now.

**Comment by blakerouse** [comment]
@joshdover The only missing piece is that the output needs to be added to the Elastic Agent.

**Comment by joshdover** [comment]
@blakerouse is that separate from [what's supported in standalone](https://www.elastic.co/guide/en/fleet/current/logstash-output.html)? Is there an existing issue to track, I can't find one.

**Comment by blakerouse** [comment]
@joshdover Sorry, seems it's already supported. So it should work.
