### ISSUE TITLE
Make 'EnrollKeyTTL' configurable in tests

### ISSUE THREAD

**Issue by mdelapenya** [elastic/fleet-server#568]
Hi team! Our e2e tests are suffering because of the [EnrollKeyTTL](https://github.com/elastic/fleet-server/blob/master/internal/pkg/config/cache.go#L35), which is set to 60s by default, and we are forced to wait a minute on each tests checking for invalid enrolment tokens.

@adam-stokes originally opened an issue on Kibana but @scunningham pointed out to [that fleet-server setting](https://github.com/elastic/kibana/issues/105078#issuecomment-878407168) to be a constant.

We wonder if it’d be possible to make it configurable in any manner, so that the tests can define a different value not waiting a minute for each test.

**Comment by scunningham** [comment]
There is a bit of a misunderstanding.  The value linked to above is the default.  The enroll timeout is configurable in the fleet-server policy section as 'cache.ttl_enroll_key'.

**Comment by mdelapenya** [comment]
> There is a bit of a misunderstanding. The value linked to above is the default. The enroll timeout is configurable in the fleet-server policy section as 'cache.ttl_enroll_key'.

Thanks for the clarification @scunningham, we will try to set that config up in our test environment. Thanks! Closing.
