### ISSUE TITLE
[Fleet] Fleet Server max connections setting is misleading

### ISSUE THREAD

**Issue by mostlyjason** [elastic/fleet-server#571]
A user filed a discuss issue that highlighted how confusing our settings page is for fleet server scaling https://discuss.elastic.co/t/elastic-agents-error-after-installation-fleet-server-returned-an-error-maxlimit/278716. Changing the max connection setting will not allow more agents to enroll. Since its such a low limit, its very likely that users will run into this problem. The longer term solution is to more gracefully limit connections https://github.com/elastic/fleet-server/issues/153

Can we consider a quick update to the package to make the limits more clear? Users also need to set `server.limits.checkin_limit.max`. We could add an input box for this setting to make it more visible and intuitive. Ideally, the "Max connections" setting should not be set directly by users. It should be calculated as the sum of the max limits for `server.limits.*.max`. If we cannot easily do that in the short term, we could provide input boxes for both of these settings and document how to set them. That will at least make them more visible and help users learn about the difference.

![image](https://user-images.githubusercontent.com/6370704/126210202-a746b192-e0ce-408f-a109-5fecbada2208.png)
![image](https://user-images.githubusercontent.com/6370704/126210229-0f03b1e4-a9c1-4542-bd8b-1ad68cd2c957.png)

CC @nimarezainia @ruflin @scunningham

**Comment by scunningham** [comment]
Thanks @mostlyjason .  This is accurate.

**Comment by EricDavisX** [comment]
linking this to the original 'max settings' ticket which is still open:
https://github.com/elastic/fleet-server/issues/466

**Comment by nimarezainia** [comment]
@mostlyjason I agree with your statement but I wonder if this absolutely needs to be configurable or just clearly stated for the user to know. 

The main variable here the user would need to know about is the number of agents that can enroll into the fleet-server - given resources (cpu/mem) they have made available to it. Number of connections and other artifacts should be calculated or looked up in a table that we have statically created based on our testing numbers.

**Options:**
1) As the user adjusts the slider (allocating more/less resources) this "_number of agents_" also automatically adjusts accordingly.
        - the user workflow for this is: "I have this much resources, how many agents can I get?"
        - it may facilitate more of a trial and error, the user keeps adjusting the slider to see what they get
        - of course the user can look at our documentation, pick the compute resourcing they need for a certain fleet size and then move the slider to that resourcing combination.
        - with metrics based auto-scaling: once we scale horizontally (or vertically even) we are essentially moving the slider which should result in "_number of agents_" changing
 
2) Alternatively if the user needs a system that can support a certain "_number of agents_". They input that in this dialogue box. We calculate what the fleet-server resourcing needs to be and adjust the slider. (we set a default value for this)  
        - the user workflow for this is: "I need X agents to be online, give me an environment that can manage that"
        - **Benefit**: Operator would generally know how many agents they need.

I feel that we may need to provide both options above. There's no doubt that the number of connections is a by-product and shouldn't be some that gets set.

_**Short-Term solution:**_ (this would be tough for 7.14 but let me discuss with @andresrc )
1. Rename the "Max Connections" box to "Max Number of Agents"
2. Have that parameter modify the server.limits.checkin_limit.max
3. Notify the user that they need to check the docs and ensure fleet-server has enough resources.

[What ever logic we build here will also help with the future work towards auto scaling of the hosted agent] 

@ruflin  thoughts on this? 

@andresrc

**Comment by mostlyjason** [comment]
@nimarezainia ++ on what you described as the longer term solution. For the short term, I believe we need a way to modify both `server.limits.checkin_limit.max` and `server.limits.max_connections`. The latter would ideally be calculated, but I assume its too late to make any change for that in 7.14 so we could leave it as is, and `server.limits.checkin_limit.max` could be set via a second input box?

**Comment by ruflin** [comment]
Option 1 I think is the short term solution we should have for the next minor by hardcoding the values like apm-server does. Option 2 is where I would like to see us heading long term but it means Fleet becomes directly or indirectly in control of the deployed Elastic Agents.

For the short term solution, I'm worried that we might break something here. I agree it is not ideal but I would rather focus on Option 1 for the next release.

**Comment by nimarezainia** [comment]
@ruflin @mostlyjason   We know what the max_connection count needs to be (along with ES size etc) to hit a certain scale. I propose that for 7.14 we leave the code as is and add max_connections to be configured in the scale table for documentation and clearly state where it can be found (to be configured). We can change the docs at anytime when this config is no longer required.

lmk
