### ISSUE TITLE
[Fleet] Hosted Fleet Server agent not available on deploying 8.0.0-alpha1 from cloud (can't be started on self-managed either) due to Semver check

### ISSUE THREAD

**Issue by amolnater-qasource** [elastic/fleet-server#608]
**stack version:** 8.0-alpha1-qa cloud environment

**Kibana commit details from /status api:**
```
Build: 44759
Commit: fa7fd32e249a095dede8cd0ef676b21e7d4707bc
```

**Preconditions:**
1. 8.0-alpha1 cloud-qa environment should be available.

**Steps to reproduce:**
1. Login to Kibana.
2. Navigate to Agents tab and observe No Hosted Fleet Server agent.

**Note:**
- Build is deployed with warnings and "Latest change to APM & Fleet configuration failed" errors.

**Expected Result:**
Hosted Fleet Server agent should be available on deploying 8.0-alpha1 from cloud-qa.

**Screenshot:**
![13](https://user-images.githubusercontent.com/77374876/127865022-5fa54289-bf0a-4542-806f-05286d36f286.JPG)

Activity page:
![14](https://user-images.githubusercontent.com/77374876/127865855-de51496f-4d7a-4bf4-b5f9-ca779d3fb2c0.JPG)

**Comment by manishgupta-qasource** [comment]
Reviewed & Assigned to @EricDavisX

**Comment by EricDavisX** [comment]
@blakerouse mentions in the x-team meeting that this is from our Semver usage / restraint and that it isn’t compatible with the string that is in place for the release:
8.0.0-alpha1

It should be adjusted in Fleet Server and also checked in Beats/Agent side, as well, for a likely adjustment needed.

And he notes that both the recent issues logged by test team are likely the same.  I’ll link them:
https://github.com/elastic/beats/issues/27191

**Comment by EricDavisX** [comment]
From the Beats issue logged in parallel (I've closed it now) - the cli output fails as such if you try to run the Fleet Server start up (bootstrap) sequence:

Extract and run Agent install command.
```
.\elastic-agent.exe install  -f `
 --fleet-server-es=https://5f83e162928e49xxxx3eff62b512c8fe.us-central1.gcp.qa.cld.elstc.co:443 `
--fleet-server-service-token=AAEAAWVsYXN0aWMvZmxlZXQtc2VydmVyL3Rva2VuLTE2Mjc5MDI3OTg1MTQ6VDRvWE5PZURSUkNlRE5JdjdpQxxxxx`
--fleet-server-policy=59d4afe0-f356-11eb-92df-f3671xxxxxx
```

Observe errors: Error - failed version compatibility check with elasticsearch on running install command.

**Comment by EricDavisX** [comment]
the next BC (BC3 or later) of 8.0 will / would have this, if it gets built!

**Comment by amolnater-qasource** [comment]
Hi @EricDavisX 
Thanks for the feedback, we will initiate our tests on 8.0-alpha1, as soon as new BC will be available.

**Comment by EricDavisX** [comment]
BC3 is out and the team reported they got past this error and are testing deeper.

**Comment by amolnater-qasource** [comment]
Hi @EricDavisX

We have created a testcase for above reported issue under bug conversion task .

Testcase link is : [C149907](https://elastic.testrail.io/index.php?/cases/view/149907)

Thanks
