### ISSUE TITLE
More human/user friendly error handling

### ISSUE THREAD

**Issue by ppf2** [elastic/fleet-server#633]
https://github.com/elastic/fleet-server/blob/fdb97bcf4c1a5e88eec4f142bda4df2d9c1292c4/internal/pkg/dl/enrollment_api_key.go#L57

Error messages like above doesn't mean much to the end user of Fleet.  It will be helpful to have more human/user friendly error handling :)

![image](https://user-images.githubusercontent.com/7216393/129230774-9e1ab77f-ed70-4280-ac81-98605d1dfc5b.png)

**Comment by andrewkroh** [comment]
It would be nice to include some additional context about remote requests in log messages like this. I'm thinking of `source.ip` and `user_agent.original`.

**Comment by scunningham** [comment]
@andrewkroh  That log data is available on each HTTP transaction if you turn debug logging on FWIW,

**Comment by andrewkroh** [comment]
Is it available on the errors, like the one in the picture, or only with debug logging?

**Comment by scunningham** [comment]
With debug logging, every transaction is logged with a bunch of metadata:
'
https://github.com/elastic/fleet-server/blob/master/internal/pkg/logger/http.go#L116

**Comment by jlind23** [comment]
Closing this one as outdated, we will reopen it later if required.
cc @ycombinator
