### ISSUE TITLE
Set User-Agent in HTTP requests

### ISSUE THREAD

**Issue by andrewkroh** [elastic/fleet-server#636]
**Describe the enhancement:**

For HTTP requests made by Fleet Server set a User-Agent header that identifies the software as Elastic Fleet Server and include version/build metadata.

For example this is a helper that Beats has https://github.com/elastic/beats/blob/95626b8f1690344312c0831ab2bdcbccffe4d089/libbeat/common/useragent/useragent.go#L27-L34.

**Describe a specific use case for the enhancement or feature:**

Having a user-agent header with this information would be helpful when looking at request logs or proxy logs for requests made to Elasticsearch or Kibana. It can make tracking down malfunctioning clients a little easier if you know what software and version that made the request.

**Comment by aleksmaus** [comment]
Merged the change for the client library to the main and 7.x branches.

Currently the fleet server is using version 7.13.1
```
github.com/elastic/go-elasticsearch/v7 v7.13.1
```

In order to implement this, need the client library to tag with the proper version v7.x.x version so we can update the go mod and pick up this change.
