### ISSUE TITLE
[Fleet]: Even after setting Unenrollment timeout field back to blank, installed agents get unenrolled after getting offline.

### ISSUE THREAD

**Issue by amolnater-qasource** [elastic/fleet-server#735]
**Kibana version:**  7.15.0 BC-5 Kibana Cloud environment

**Host OS and Browser version:** All, All

**Build details:**
```
Build: 43957
Commit: 0239ff6864dd9930cfe9bcd9a679272f2b7465c2
Artifact Link: https://staging.elastic.co/7.15.0-edd09abf/downloads/beats/elastic-agent/elastic-agent-7.15.0-windows-x86_64.zip
```

**Preconditions:**
1. 7.15.0 BC-5 Kibana Cloud environment should be available.
2. Agent must be installed with Default policy having System integration.

**Steps to reproduce:**
1. Login to Kibana environment.
2. Set unenrollment timeout from Default Policy setting to 60 seconds.
3. Turn off elastic-agent from services and observe agent goes inactive after 60 seconds.
4. Reset unenrollment timeout field of Default Policy to blank.
5. Re-enroll agent with default policy.
6. Turn off elastic-agent from services and observe agent still gets unenrolled from Fleet UI.

**Expected Result:**
After setting Unenrollment timeout field back to blank, installed agent should not go to inactive state after getting offline.

**Suggestion:**
Checkbox option should be there to use unenrollment timeout field or not.

**Screenshots:**
![11](https://user-images.githubusercontent.com/77374876/132496142-d79dbae0-d691-4908-8ad5-bb1f25531234.JPG)
![12](https://user-images.githubusercontent.com/77374876/132496775-3d1ebb40-1aba-415a-b108-a8225c41ab2a.JPG)

**Comment by jen-huang** [comment]
@elastic/agent Hi, this seems like a bug on the Fleet Server side where if the `unenroll_timeout` is unset in the policy sent to Fleet Server, it still unenrolls the agent by the last timeout value.

**Comment by EricDavisX** [comment]
I'd like to get this in 7.16 if possible, and backport to 7.15 is probably good plan.

**Comment by amolnater-qasource** [comment]
### `Bug Conversion`

-  01 new testcase is created under the 'Policy settings' section:
   - [C150164](https://elastic.testrail.io/index.php?/cases/view/150164)

Thanks!

**Comment by joshdover** [comment]
Hi all this recently affected a large user of Fleet in conjunction with #741. Could we get this prioritized for a 7.16 fix?

**Comment by jlind23** [comment]
Hi @joshdover we'll talk about it during our weekly and work on it as soon as possible.

**Comment by michel-laterman** [comment]
I've tried to recreate on `7.16.2` (on macOS and windows), however after stopping the `elastic-agent` (step 3 and 6) it is removed off the agents list in the Kibana UI. I didn't see it go to inactive in any case. Is this still an issue?

**Comment by amolnater-qasource** [comment]
Hi @michel-laterman 
We have revalidated this issue on latest 8.0 Snapshot and found it still reproducible.
- Even after setting Unenrollment timeout field back to blank, installed agents get unenrolled after getting offline.

**Steps to reproduce:**
1. Set unenrollment timeout to 120 seconds for default policy.
2. Install an agent with this policy.
3. Stop Elastic Agent from services.
4. Observe agent went offline.[Working Fine]
5. Now clear unenrollment timeout field for default policy.
6. Install an agent again and stop it from agent services.
7. Observe agent went offline [Issue]

**Build details:**
Build: 48868
Commit: a29e0164a4af4d3135910cac9e6caa4478af5f3b
Artifact Link: https://snapshots.elastic.co/8.0.0-b0d1c470/downloads/beats/elastic-agent/elastic-agent-8.0.0-SNAPSHOT-windows-x86_64.zip

Thanks

**Comment by blakerouse** [comment]
@amolnater-qasource Just for clarity after #7 is the steps above, it gets unenrolled.

**Comment by michel-laterman** [comment]
OK, I was able to reproduce.
It's also important to note that this behaviour (of an agent going `inactive`) does not occur on a fresh install where the unenrollment timeout value is never altered.
I've confirmed that clearing the timeout value in Kibana will remove the `unenroll_timeout` value in the saved policy (however I don't think this value displays properly with `elastic-agent inspect`.
I think there may be issues somewhere with parsing the timeout value in the policy (when it goes from a non-nil to a nil value).

**Comment by michel-laterman** [comment]
It doesn't appear to be a parsing issue. However I can see that the unenrollment monitor starts twice (a few seconds apart) when the value is changed (and I have confirmed that the cancel is called twice):
```
{"log.level":"info","ecs.version":"1.6.0","service.name":"fleet-server","ctx":"policy leader manager","policy_id":"2016d7cc-135e-5583-9758-3ba01f5a06e5","checkInterval":60000,"unenrollTimeout":120000,"@timestamp":"2021-12-28T22:18:22.137Z","message":"unenroll monitor start"}
{"log.level":"info","ecs.version":"1.6.0","service.name":"fleet-server","ctx":"policy leader manager","policy_id":"2016d7cc-135e-5583-9758-3ba01f5a06e5","checkInterval":60000,"unenrollTimeout":120000,"@timestamp":"2021-12-28T22:18:28.515Z","message":"unenroll monitor start"}
```

**Comment by amolnater-qasource** [comment]
Thanks @blakerouse for correction, yes it meant installed agent went inactive that is unenrolled from Kibana, after resetting unenrollment field to blank.
We have also updated the above comment.

Further, please let us know if any other testing is required on this from our end.

**Comment by michel-laterman** [comment]
We have a goroutine leak.

Two methods ([ensureLeadership](https://github.com/elastic/fleet-server/blob/master/internal/pkg/coordinator/monitor.go#L304) and [handlePolicies](https://github.com/elastic/fleet-server/blob/master/internal/pkg/coordinator/monitor.go#L192)) call `rescheduleUnenroller` which leads to two goroutines monitoring for unenrollment (when the unenroll timeout is set). However, when the timeout is cleared only one of the goroutines is cancelled.

To verify this I added  uuids to the reshedule function to track start and exit:
```
# setting timeout to 120
{"log.level":"info","ecs.version":"1.6.0","service.name":"fleet-server","ctx":"policy leader manager","policy_id":"2016d7cc-135e-5583-9758-3ba01f5a06e5","unenroll_timeout":120000,"@timestamp":"2021-12-29T21:28:02.469Z","message":"Setting unenrollment timeout"}
{"log.level":"info","ecs.version":"1.6.0","service.name":"fleet-server","ctx":"policy leader manager","policy_id":"2016d7cc-135e-5583-9758-3ba01f5a06e5","unenroller_uuid":"c50f9a7a-dd1f-46d5-a76b-ccfd850a92f4","checkInterval":60000,"unenrollTimeout":120000,"@timestamp":"2021-12-29T21:28:02.469Z","message":"unenroll monitor start"}
{"log.level":"info","ecs.version":"1.6.0","service.name":"fleet-server","ctx":"policy leader manager","policy_id":"2016d7cc-135e-5583-9758-3ba01f5a06e5","unenroll_timeout":120000,"@timestamp":"2021-12-29T21:28:07.934Z","message":"Setting unenrollment timeout"}
{"log.level":"info","ecs.version":"1.6.0","service.name":"fleet-server","ctx":"policy leader manager","policy_id":"2016d7cc-135e-5583-9758-3ba01f5a06e5","unenroller_uuid":"3cb1edf0-515c-4558-ba5e-28c67b5dc5fe","checkInterval":60000,"unenrollTimeout":120000,"@timestamp":"2021-12-29T21:28:07.934Z","message":"unenroll monitor start"}

# clearing timeout
{"log.level":"info","ecs.version":"1.6.0","service.name":"fleet-server","ctx":"policy leader manager","policy_id":"2016d7cc-135e-5583-9758-3ba01f5a06e5","@timestamp":"2021-12-29T21:29:14.615Z","message":"Cancelling unenrollment monitor"}
{"log.level":"info","ecs.version":"1.6.0","service.name":"fleet-server","ctx":"policy leader manager","policy_id":"2016d7cc-135e-5583-9758-3ba01f5a06e5","unenroll_timeout":0,"@timestamp":"2021-12-29T21:29:14.632Z","message":"Setting unenrollment timeout"}
{"log.level":"info","ecs.version":"1.6.0","service.name":"fleet-server","ctx":"policy leader manager","policy_id":"2016d7cc-135e-5583-9758-3ba01f5a06e5","unenroller_uuid":"3cb1edf0-515c-4558-ba5e-28c67b5dc5fe","@timestamp":"2021-12-29T21:29:14.632Z","message":"cancelling unenroller"}
{"log.level":"info","ecs.version":"1.6.0","service.name":"fleet-server","ctx":"policy leader manager","policy_id":"2016d7cc-135e-5583-9758-3ba01f5a06e5","unenroller_uuid":"3cb1edf0-515c-4558-ba5e-28c67b5dc5fe","@timestamp":"2021-12-29T21:29:14.632Z","message":"Unenroll monitor exit"}
{"log.level":"info","ecs.version":"1.6.0","service.name":"fleet-server","ctx":"policy leader manager","policy_id":"2016d7cc-135e-5583-9758-3ba01f5a06e5","@timestamp":"2021-12-29T21:29:34.359Z","message":"Cancelling unenrollment monitor"}
{"log.level":"info","ecs.version":"1.6.0","service.name":"fleet-server","ctx":"policy leader manager","policy_id":"2016d7cc-135e-5583-9758-3ba01f5a06e5","unenroll_timeout":0,"@timestamp":"2021-12-29T21:29:34.359Z","message":"Setting unenrollment timeout"
```

@blakerouse, should the call to reschule remain in `ensureLeadership`, or do we need to add a lock to the monitor?

**Comment by blakerouse** [comment]
@michel-laterman We need that function to be in both places because it could be that leadership changes due to interval timeout or in the case that the policy changes the unenroll timeout needs to be updated.

Seems that some type of locking will be needed to ensure that only 1 is started per policy.

**Comment by amolnater-qasource** [comment]
Hi @michel-laterman 
We have revalidated this issue on latest 8.0 Snapshot and found it **fixed** now.
- We have set unenrollment timeout to 240 seconds and then agent went to Inactive state after getting offline for 240 seconds.
- We reset the unenrollment timeout field to blank and then we stopped installed agent for a period of time.
- We observed it didn't go to inactive state and just remained offline.

**Screenshot:**
![7](https://user-images.githubusercontent.com/77374876/150921522-e203a716-fe08-4393-9de6-f45d5e74b964.JPG)

**Build details:**
BUILD: 49125
COMMIT: 1678a714924636da4f92cdfcf5b1e766d053cd5e
Artifact Link: https://snapshots.elastic.co/8.0.0-6ce456eb/downloads/beats/elastic-agent/elastic-agent-8.0.0-SNAPSHOT-windows-x86_64.zip

Thanks
