### ISSUE TITLE
Better error handling when enrolling an agent to a fleet server with version incompatibility

### ISSUE THREAD

**Issue by ppf2** [elastic/fleet-server#746]
When enrolling an Agent (7.15) to Fleet Server (7.14), we currently throw a brief `UnsupportedVersion` error.

```
2021-09-28T17:55:06.985-0700	INFO	cmd/enroll_cmd.go:432	Starting enrollment to URL: https://e393538d3afa4918a9546a7cf8770870.fleet.us-east-1.aws.found.io:443/
Error: fail to enroll: fail to execute request to fleet-server: status code: 400, fleet-server returned an error: UnsupportedVersion, message: version is not supported
For help, please see our troubleshooting guide at https://www.elastic.co/guide/en/fleet/7.15/fleet-troubleshooting.html
Error: enroll command failed with exit code: 1
For help, please see our troubleshooting guide at https://www.elastic.co/guide/en/fleet/7.15/fleet-troubleshooting.html
```

The above links to the troubleshooting page which doesn't discuss the version compatibility requirement.

It will be a better experience to spell out what versions of the Agent is supported by the Fleet Server the Agent is being enrolled to.  If we are going to link to a documentation page, let's add the compatibility information on this page (https://www.elastic.co/support/matrix#matrix_compatibility) and link from the error message :)

**Comment by guilhermevini** [comment]
+1

**Comment by dmehra23** [comment]
+1

**Comment by jlind23** [comment]
Closing this one as outdated/not prioritised, we will reopen it later if required.
cc @ycombinator

**Comment by mazda4409** [comment]
Just ran into this same issue, documentation on this is also lacking Elastic. Much room for improvement on this and other issues. Also, error handling to specify what versions ARE supported to prevent time wasted brute-forcing compatible versions. This is specifically applicable to the Elastic deployed with Security Onion 2 on the latest release [2.4.111-20241217](https://github.com/Security-Onion-Solutions/securityonion/releases/tag/2.4.111-20241217). 

Overall, more documentation is needed for this quasi-open-source security software. I have worked in PRD Elastic security deployment environments and let me say, it was NOT fun. It is not intuitive, especially from a deployment or engineering perspective and was a massive pain to deal with, even having a hired, dedicated "boutique" Elastic firm of "Elastic experts."
