### ISSUE TITLE
Kibana UX marks agents as "offline" at large scale, despite being connected to fleet.

### ISSUE THREAD

**Issue by scunningham** [elastic/fleet-server#749]
To repro:

- Use [horde](https://github.com/elastic/horde) to enroll 250k emulated agents.
-  Notice that regardless of cluster size, some subset of agents are always marked "offline".  Horde indicates they are online.

Kibana marks an agent as "offline" if it has not updated the agent's "last_checkin" in the .fleet-agent index in the last two minutes.  Kibana is behaving as expected, these records are not being updated be Fleet Server in time.

On investigation, noticed that one elastic search node was under heavy load:

![Screen Shot 2021-09-29 at 10 01 48 AM](https://user-images.githubusercontent.com/294689/135304306-77839d41-60bd-45ff-bb59-f654eac76201.png)

The ".fleet-agent" index has only one shard and one replica.  The primary shard is located on the node that is under heavy load and having difficult keeping up.  As an experiment, I forced the ".fleet-agent" index to reindex with four shards, and the load was distributed better; the UX now properly marked all agents as online:

![Screen Shot 2021-09-29 at 11 26 46 AM](https://user-images.githubusercontent.com/294689/135304635-606b1de8-1928-4caf-b1c7-effc78b69f35.png)

However, as you can see from above snapshot, a significant amount of resource overhead is used just to keep Fleet "dialtone".  The system is not doing anything interesting except waiting for new commands, and we are using about 1/3 of the clusters CPU and RAM.  This is excessive.

There are two things driving this:
1) The fleet server marks an agent's "last_checkin" record every 30s.  This allows Kibana to query for the 2m timeout mentioned above.  At 250k endpoints this is a sustained rate of 8333 document updates per second.
2) The fleet server does a long poll approximately every 5m.  At the beginning of each long poll, the server must auth the request, and run several queries to update state.  This is a relatively expensive set of operations.

To bring down overhead at scale, I would suggest the following:

1) Recode Kibana to be less aggressive in marking agents as offline.  Back off from 2m to 12m.  Remove the code from Fleet Server that updates the check-in field every 30s and have it effectively mark it every 5m.
2) Ask the cloud folks for a longer long-poll.  A twenty or thirty minute long poll would go a long way in taking load off of every component in the system when there is nothing going on.

**Comment by joshdover** [comment]
@ph I think this would be solved by our new design for agent health status which does not update the `last_checkin` field on a regular basis. Do you agree?

**Comment by ph** [comment]
@joshdover Yes I think so too.

**Comment by joshdover** [comment]
We decided to defer on this checkin frequency change to a later release. Currently, the Fleet UI considers an agent offline if it's [missed 4 check-ins (each 30s)](https://github.com/elastic/kibana/blob/c1025d81278f75b0d836235caf45f26329a543cd/x-pack/plugins/fleet/common/services/agent_status.ts/#L37), effectively hasn't checked in for 2 minutes. Maybe for now we should just increase this to something more reasonable like 10 checkins (5 minutes)? cc @juliaElastic who is working on some scaling related improvements

**Comment by juliaElastic** [comment]
@joshdover I created an issue in kibana repo for this: https://github.com/elastic/kibana/issues/134182

**Comment by joshdover** [comment]
Thanks, Julia. Let's close this in favor of the Kibana issue.
