### ISSUE TITLE
[8.0] Support "Security on by Default"

### ISSUE THREAD

**Issue by joshdover** [elastic/fleet-server#760]
Starting in 8.0, Elasticsearch will be shipping with security enabled by default for on-prem deployments. This involves Elasticsearch generating a CA and using it to create self-signed certificates for TLS.

We need to investigate how this will impact the initial Fleet Server onboarding experience for new users. I suspect that Fleet Server will need access to the generated CA's fingerprint in order to trust Elasticsearch. If so, the command given to users in the Fleet UI during Fleet Server setup will not work out of the box.

Kibana is following a pattern where Elasticsearch generates an 'enrollment token' that has the CA fingerprint embedded in it. It's possible we could follow a similar approach.

**Comment by azasypkin** [comment]
> @azasypkin If we wanted to send the Elasticsearch CA fingerprint to Fleet Server, would it be safe to derive this from the ElasticsearchConfig.ssl.certificateAuthorities property? https://github.com/elastic/kibana/blob/master/src/core/server/elasticsearch/elasticsearch_config.ts/#L378

Yeah, the SHA-256 fingerprint you'll get from the CA certificate we put to `elasticsearchConfig.ssl.certificateAuthorities` during enrollment process is exactly the same as the fingerprint we receive in the enrollment token itself and rely on during enrollment.

Luckily, we've just upgraded to NodeJS 16 and you can now use [`X509Certificate`](https://nodejs.org/api/crypto.html#class-x509certificate) to quickly parse CA certificate and get the required fingerprint.

**Comment by joshdover** [comment]
Now that I understand enrollment all happens in Agent 😬 , I believe we can close this in favor of elastic/beats#25705 as they should be solved in the same way.
