### ISSUE TITLE
Fleet Server needs CI Integration with e2e-testing repo to run the Agent (and Kibana/Fleet-server side) tests

### ISSUE THREAD

**Issue by EricDavisX** [elastic/fleet-server#77]
We have a repo that we use to run Agent (and other Fleet related) tests: 
https://github.com/elastic/e2e-testing

When Agent shifted to use Fleet server adjusted the available tests, here:
https://github.com/elastic/e2e-testing/issues/438
Though we still need to flesh out and implement deeper actual Fleet Server tests:
https://github.com/elastic/e2e-testing/issues/1266

Still, with the coverage we have, we can make use of those tests in the actual Fleet-Server repo CI, which is what this ticket is in support of.  We need to itemize what details we need of:
- [x] the Fleet Server repo compilation of the artifacts
- [ ]  - does this include how to build a Docker image with an updated Fleet server from source?
- [x] and how to make use of the newly compiled artifacts to be built into Elastic Agent artifact(s)
- [ ] Then, in the fleet-server repo we need to add more to the ci jenkins file, managed in the other issue 

The ci hook will run a desired set of e2e-testing scenarios like what we have done for Agent and Kibana.  Reference this groovy file for info:
https://github.com/mdelapenya/beats/blob/921a3d52e60db04e0c92712203f097157f290265/.ci/packaging.groovy

This ticket is for documenting the knowledge and steps / logistics.

There is a separate ticket for implementing e2e-testing side changes, here:
https://github.com/elastic/e2e-testing/issues/1411

**Comment by EricDavisX** [comment]
@mdelapenya is this something you want to help work with us on?

**Comment by EricDavisX** [comment]
@elastic/observablt-robots I should have tagged the team.

**Comment by ph** [comment]
Done in https://github.com/elastic/e2e-testing/issues/438

**Comment by EricDavisX** [comment]
Actually, this is not resolved in 438, this needs a fairly deep conversation and design to allow PR CI support for the Fleet-Server repo.  As it is tonight, we only have support for nightly runs to include new Fleet Sever tests, and those could be 1-2 days behind the change so the feedback loop is way too long.  This ticket is opened explicitly for the ability to provide feedback during a PR to know that a developer's fleet-server changes are not introducing problems.

**Comment by EricDavisX** [comment]
We're pairing with the above issue in e2e-testing repo now.  The details on how to build the Fleet Server binary are actually in the repo readme.md, as as follows.  To build Fleet Server:

pre-conditions (2 options):
option 1: pull the head of the branch in the Beats repo from which the Fleet Server PR is aimed (they will be in sync)
... and do a mage build to build all the artifact types

option 2: pull the entire set of the latest snapshot Elastic-Agent artifact set from the branch which the Fleet Server PR is aimed.  

Fleet Server steps:
1) clone Fleet Server repo on the worker and pull the repo branch that is under change
2) from inside it, run 'make release' which will build the binaries
3) go to build/distributions and copy out the .tar.gz (or other artifact) and sha512 file to the data/elastic-agent-{hash}/downloads inside the elastic-agent directory you wish to use.  
4) Then you can re-archive the Agent and use it in tests.

**Comment by EricDavisX** [comment]
Some discussion was had via email, I am summarizing the questions and my initial answers below:
---------

It feels best to keep it extremely simple, where possible, reduce combinations of tests to just one form and make assumptions that allow repeatability.

To your notes @ruflin), I could add the following:
Q) What version of the Elastic Agent do we test it with? Which commit? 
 - I hope we know during CI for Fleet Server what branch is under test (and we could keep it simple and target just master to start).  I suggest we just use the latest snapshot available of Agent for the given test line.  There are imperfections with this, but clarity in its simplicity.

Q) Are the builds reproducible? 
 - if we print the commit used of Agent during a given run and always pull 'latest' by default, while allowing the snapshot commit to be passed as a command line param, we can ensure repeatability. This would also allow us to test with older known working snapshots to pass CI tests if Agent build is ever broken.  Win/Win

Q) I'm also worried it adds quite a bit to the build time.
 - It should only add a minimum of time if we build just one variant of Fleet Server binary, meaning we can skip worrying about .deb/.rpm usage and indeed win/linux/macOS worries... let's just focus on one.  Whatever ends up being easiest for the team to construct.  I'd suggest Docker (and Elastic Agent Container) but I'm unclear on the build side if we could indeed 'stuff in' the Fleet Server code as easily there or not.  Someone else may know this or we can research it.   
- and also, who cares if it takes a little longer.  Patience to run tests may be rewarded by not checking in new bugs - which will save us time, over the long run.  :)

Q) Does anyone have additional questions, concerns, or thoughts?

**Comment by mdelapenya** [comment]
I did a research about this task, and after talking to @michalpristas, I'd like to confirm with the team if the following assumptions are correct, or if there is a simpler manner to build the agent with the new fleet-server code.

### Pre-requisites to build the agent with Fleet Server
1. the fleet-server code must be compiled and packaged first using `make release`, which will generate the artifacts under `build/distributions`:
```shell
$ ls -l build/distributions/
total 97280
-rw-r--r--  1 mdelapenya  staff  6943725 22 Sep 11:05 fleet-server-8.0.0-darwin-arm64.tar.gz
-rw-r--r--  1 mdelapenya  staff      169 22 Sep 11:05 fleet-server-8.0.0-darwin-arm64.tar.gz.sha512
-rw-r--r--  1 mdelapenya  staff  7349754 22 Sep 11:05 fleet-server-8.0.0-darwin-x86_64.tar.gz
-rw-r--r--  1 mdelapenya  staff      170 22 Sep 11:05 fleet-server-8.0.0-darwin-x86_64.tar.gz.sha512
-rw-r--r--  1 mdelapenya  staff  7287225 22 Sep 11:05 fleet-server-8.0.0-linux-arm64.tar.gz
-rw-r--r--  1 mdelapenya  staff      168 22 Sep 11:05 fleet-server-8.0.0-linux-arm64.tar.gz.sha512
-rw-r--r--  1 mdelapenya  staff  6430321 22 Sep 11:05 fleet-server-8.0.0-linux-x86.tar.gz
-rw-r--r--  1 mdelapenya  staff      166 22 Sep 11:05 fleet-server-8.0.0-linux-x86.tar.gz.sha512
-rw-r--r--  1 mdelapenya  staff  8016882 22 Sep 11:05 fleet-server-8.0.0-linux-x86_64.tar.gz
-rw-r--r--  1 mdelapenya  staff      169 22 Sep 11:05 fleet-server-8.0.0-linux-x86_64.tar.gz.sha512
-rw-r--r--  1 mdelapenya  staff  6668170 22 Sep 11:05 fleet-server-8.0.0-windows-x86.zip
-rw-r--r--  1 mdelapenya  staff      165 22 Sep 11:05 fleet-server-8.0.0-windows-x86.zip.sha512
-rw-r--r--  1 mdelapenya  staff  7067757 22 Sep 11:05 fleet-server-8.0.0-windows-x86_64.zip
-rw-r--r--  1 mdelapenya  staff      168 22 Sep 11:05 fleet-server-8.0.0-windows-x86_64.zip.sha512
```

2. metricbeat, filebeat and heartbeat have to be compiled in their x-pack flavour, using `DEV=true SNAPSHOT=true PLATFORMS="+all linux/amd64" mage package`
3. Copy fleet-server an MB/FB/HB binaries to a dedicated folder (i.e. `/tmp/drop-path`)
3. Package the elastic-agent with `DEV=true SNAPSHOT=true AGENT_DROP_PATH="/tmp/drop-path" PLATFORMS="+all linux/amd64" mage package`

```shell
$ ls -l build/distributions/
total 2859928
-rw-r--r--@ 1 mdelapenya  staff  123085702 22 Sep 12:34 elastic-agent-8.0.0-SNAPSHOT-amd64.deb
-rw-r--r--  1 mdelapenya  staff        168 22 Sep 12:34 elastic-agent-8.0.0-SNAPSHOT-amd64.deb.sha512
-rw-r--r--  1 mdelapenya  staff  247517305 22 Sep 12:34 elastic-agent-8.0.0-SNAPSHOT-linux-amd64.docker.tar.gz
-rw-r--r--  1 mdelapenya  staff        184 22 Sep 12:34 elastic-agent-8.0.0-SNAPSHOT-linux-amd64.docker.tar.gz.sha512
-rw-r--r--  1 mdelapenya  staff  123160314 22 Sep 12:33 elastic-agent-8.0.0-SNAPSHOT-linux-x86_64.tar.gz
-rw-r--r--  1 mdelapenya  staff        178 22 Sep 12:33 elastic-agent-8.0.0-SNAPSHOT-linux-x86_64.tar.gz.sha512
-rw-r--r--  1 mdelapenya  staff  122901963 22 Sep 12:34 elastic-agent-8.0.0-SNAPSHOT-x86_64.rpm
-rw-r--r--  1 mdelapenya  staff        169 22 Sep 12:34 elastic-agent-8.0.0-SNAPSHOT-x86_64.rpm.sha512
-rw-r--r--  1 mdelapenya  staff  622250882 22 Sep 12:36 elastic-agent-complete-8.0.0-SNAPSHOT-linux-amd64.docker.tar.gz
-rw-r--r--  1 mdelapenya  staff        193 22 Sep 12:36 elastic-agent-complete-8.0.0-SNAPSHOT-linux-amd64.docker.tar.gz.sha512
-rw-r--r--  1 mdelapenya  staff  166190314 22 Sep 12:34 elastic-agent-ubi8-8.0.0-SNAPSHOT-linux-amd64.docker.tar.gz
-rw-r--r--  1 mdelapenya  staff        189 22 Sep 12:34 elastic-agent-ubi8-8.0.0-SNAPSHOT-linux-amd64.docker.tar.gz.sha512
```

### CI Integration
We could create a dedicated pipeline listening for GH events on the fleet-server repo (we already do that for Kibana PRs), so that any `/run-e2e-tests` GH comment would trigger the execution of a pipeline which will:
1. download fleet-server, building it, stashing the `build/distributions` dir.
2. download beats, building metricbeat, heartbeat and filebeat, stashing the `build/distributions` dir for each beat.
3. unstash all of the above into a "drop-path" directory
4. build the elastic-agent using AGENT_DROP_PATH with previous directory
5. run the e2e-testing framework against the local copy of the binaries (BEATS_LOCAL_PATH)

**Comment by mdelapenya** [comment]
Thanks to @michalpristas again, a simpler sequence of steps would be:

1. Package the elastic-agent with `DEV=true SNAPSHOT=true PLATFORMS="+all linux/amd64" mage package`, which will build all dependant Beats (MB/FB/HB)
2. Package fleet-server code using make release, which will generate the artifacts under `build/distributions`
3. Copy fleet-server an MB/FB/HB binaries to a dedicated folder (i.e. /tmp/drop-path)
4. Package the elastic-agent again with `DEV=true SNAPSHOT=true AGENT_DROP_PATH="/tmp/drop-path" PLATFORMS="+all linux/amd64" mage package`

**Comment by EricDavisX** [comment]
@mdelapenya hi - I don't see that the steps are that different really?  Either way I'm excited we feel good about the steps! I'd love to hear how its going and to follow along with any updates / dev on this.  cheers.
