### ISSUE TITLE
Handle INTERNAL_POLICY_REASSIGN action

### ISSUE THREAD

**Issue by nchaulet** [elastic/fleet-server#84]
## Description 

In Kibana We are currently creating an action `INTERNAL_POLICY_REASSIGN` to know when we need to fetch again the agent and distribute a new policy, this should probably handled in Fleet Server too.

**Comment by scunningham** [comment]
@nchaulet As I read this implementation in Kibana, it would appear that the reason is to short circuit a long poll?  It seems the system would work as currently written when the long poll is over and the agent checks-in again?

**Comment by nchaulet** [comment]
Yes it works as it is right now, but a policy reassign could take up to 5 minute instead of being an instant action.

**Comment by scunningham** [comment]
I would suggest a different mechanism to signal the fleet server than an action.  This is an ephemeral signal that does not require perfect delivery and should roll off fast.  Actions are designed for fault tolerant delivery at bulk scale.

We would have to use elastic search as a go between.  Perhaps a dedicated signal data stream with a fast ILM rollover.  There may be other mechanisms we can leverage as well.

**Comment by scunningham** [comment]
Race condition here no matter what we do.  If the fleet server is watching policy A for changes, and is reassigned policy B, policy A could change to rev 2 and get applied before we notice policy B as been assigned.  Could mitigate somewhat with an agent record check before updating policy, but there's still a race.  This is true whether we use alerts or another mechanism to signal.

We will, however, achieve eventual consistency on next poll.

**Comment by nchaulet** [comment]
Will be solved by https://github.com/elastic/kibana/issues/93945

**Comment by ph** [comment]
@nchaulet I see this issue closed and the linked PR was not merged, is this still a problem?

**Comment by nchaulet** [comment]
I think I missed a reference to the PRs somewhere but here it is https://github.com/elastic/kibana/pull/94116  and https://github.com/elastic/beats/pull/24616
