### ISSUE TITLE
Add APM instrumentation to Fleet Server

### ISSUE THREAD

**Issue by simitt** [elastic/fleet-server#850]
**Describe the enhancement:**
Add apm instrumentation to the Fleet Server. At least following configuration options should be supported:
* environment
* hosts
* secret-token | api-key

**Describe a specific use case for the enhancement or feature:**
Turning on APM tracing will help gain more insights into the Fleet Server performance and errors, especially in combination with https://github.com/elastic/beats/issues/28895.

cc @elastic/apm-server @jlind23

**Comment by marclop** [comment]
I don't seem to have permissions to assign this issue to myself, if someone could give me permissions to do that or at least assign me to this issue so others don't work on it.

**Comment by jlind23** [comment]
You are assigned now;
