### ISSUE TITLE
[8.0 Snapshot]: `APM & Fleet configuration failed` while creating 8.0 Snapshot environment.

### ISSUE THREAD

**Issue by amolnater-qasource** [elastic/fleet-server#924]
**Description:**
`APM & Fleet configuration failed` while creating 8.0 Snapshot environment from:
- https://staging.found.no/deployments/create
- https://console.qa.cld.elstc.co/deployments/create

**Platform:**
Google Cloud Platform

**Observations:**
- Build is Healthy with Warnings
- None of the policies have the integrations.
- No hosted fleet server agent is available.

**Screenshot:**
![1](https://user-images.githubusercontent.com/77374876/143809874-798f947a-3086-4436-b231-e64400406d7f.JPG)

**Note:**
This issue is not observed for 7.16.0 Snapshot.

**Comment by amolnater-qasource** [comment]
Further we are also not able to deploy our own Fleet Server, as no enrollment command is available to install fleet-server.

**Screenshot:**
![2](https://user-images.githubusercontent.com/77374876/143814552-06e3756c-4a52-4794-a86c-e07b11723abb.JPG)

Hence we are **blocked for agent related tests**.

**Comment by amolnater-qasource** [comment]
@manishgupta-qasource Please review.

**Comment by manishgupta-qasource** [comment]
Reviewed & mentioned to @joshdover

CC: @EricDavisX

**Comment by EricDavisX** [comment]
The APM team had noted there was cloud side work to be done to sync up to 8.x changes done wrt to the APM changes - having this logged is nice, but we may not expect work to be tracked here. we can raise it as an urgent issue as we near the 8.0 testing time frame.

**Comment by amolnater-qasource** [comment]
Hi @EricDavisX 
Today we are able to deploy Healthy 8.0 Snapshot deployment from https://console.qa.cld.elstc.co/deployments

**Build details:**
Build: 48594
Commit: ad3660f3acbfe6eb809d869b908221edf2846313

Hence we are **closing** this issue.
Thanks
