### ISSUE TITLE
[8.1 Snapshot]: APM & Fleet configuration failed while creating 8.1 Snapshot environment.

### ISSUE THREAD

**Issue by dikshachauhan-qasource** [elastic/fleet-server#929]
**Description:**
APM & Fleet configuration failed while creating 8.1 Snapshot environment from:

Created from:
https://staging.found.no/deployments/create
https://console.qa.cld.elstc.co/deployments/create
Platform: Google Cloud Platform

Observations:

- Build is Healthy with Warnings
- Default Policies have the default integrations.
- No hosted fleet server agent is available.

**Screenshot:**
![image](https://user-images.githubusercontent.com/72375798/143823201-16241635-f06b-4cb9-a7c9-a1f16ce0fef2.png)

![image](https://user-images.githubusercontent.com/72375798/143823219-9fc22009-d03f-4dc6-996d-fc636caf9325.png)

**Comment by manishgupta-qasource** [comment]
Reviewed & mention to @joshdover

CC: @EricDavisX

**Comment by EricDavisX** [comment]
The APM team had noted there was cloud side work to be done to sync up to 8.x changes done wrt to the APM changes - having this logged is nice, but we may not expect work to be tracked here.  we can raise it as an urgent issue as we near the 8.0 testing time frame.

**Comment by EricDavisX** [comment]
Also... I see we logged 2 of these, one for each version - just to be safe.  That's cool.  :)  In this case it doesn't help as the work is known, and isn't even on this team (or this repo).  So, I'm closing this one in favor of 924 - https://github.com/elastic/fleet-server/issues/924

**Comment by dikshachauhan-qasource** [comment]
Hi @EricDavisX 

We have performed a sanity run on 8.1 snapshot cloud build and covered below scenarios:

- Agents install on all OSs
- Agent reboot and re-enroll scenarios
- Endpoint integrations
- Alerts detection and prevention tests
- Managed host and managed policy
- Policy reassigning and agent logging level
- Agent hardening
- Core integrations
- Discover and dashboards tabs
- Various filter on Fleet subtabs


**Build details:**
BUILD: 48524
COMMIT: c6f491c015217d039d3ad72815d38d4d936b0b3b
ARTIFACT: https://artifacts-api.elastic.co/v1/search/8.1.0-SNAPSHOT/

Thanks
QAS
