### ISSUE TITLE
[Self-managed 8.0]: Getting `400 status code error` on running fleet server install command on 8.0 Snapshot.

### ISSUE THREAD

**Issue by amolnater-qasource** [elastic/fleet-server#935]
**Kibana version:**  8.0.0 Kibana self-managed environment

**Host OS:** Windows 10x64

**Build details:**
```
BUILD 48385
COMMIT 767b23ad878cb7ca94331b6402789a9846388852
Artifact Link: https://snapshots.elastic.co/8.0.0-89da64e1/downloads/beats/elastic-agent/elastic-agent-8.0.0-SNAPSHOT-windows-x86_64.zip
```

**Pre-requirements:**
1. ELK setup should be completed.

**Steps to reproduce:**
1. Login to Kibana and navigate to Fleet>Agents tab.
2. Add host ip:`https://1.1.1.1:8220`.
3. Generate token and copy fleet server install command for windows.
4. Run agent install command and observe 400 status code error.

**Expected Result:**
Fleet-server should get installed on running agent install command on 8.0 Snapshot.

**Screenshots:**
![7](https://user-images.githubusercontent.com/77374876/144039547-8ac159c4-b93d-4ac3-8f32-2bb56c5d4a29.JPG)

**Comment by amolnater-qasource** [comment]
@manishgupta-qasource Please review.

**Comment by manishgupta-qasource** [comment]
Reviewed & mention to @blakerouse

CC: @EricDavisX

**Comment by EricDavisX** [comment]
raising this as an urgent issue.

**Comment by jlind23** [comment]
@amolnater-qasource was fleet server already running? don't you have logs in fleet server or in elastic agent logfiles?
Is your kibana instance properly running?
@manishgupta-qasource please mention @elastic/elastic-agent-control-plane instead of only @blakerouse.

**Comment by samratbhadra-qasource** [comment]
Hi @EricDavisX  as per the feedback on mail we have re-attempted agent installation on 8.0.0-Snapshot build on self-managed setup on macOS and found that the issue is **fixed** now.

**Screenshot:**

![Screenshot (399)](https://user-images.githubusercontent.com/84007952/144385455-6f5ebe53-6290-4c71-bb41-d01338ad7427.png)


![Screenshot (401)](https://user-images.githubusercontent.com/84007952/144385509-6475f30d-4750-45d8-8407-11b217425474.png)

**Build Details:**
VERSION: 8.0.0-SNAPSHOT
BUILD: 48481
COMMIT: 9366c7cc4be661476cf25a46dfb7248c4a2d3d55
ARTIFACT: https://snapshots.elastic.co/8.0.0-5dc82a0c/summary-8.0.0-SNAPSHOT.html

Thanks!

**Comment by amolnater-qasource** [comment]
Hi @jlind23 
No it was a fresh self-managed 8.0 kibana and no agent/fleet-server was earlier installed on it.

Further today we have re-attempted to install fleet-server.
We restarted the Elasticsearch and kibana and ran install command again.
Today we are **successfully** able to install fleet-server on Windows 10 too:

**Install command:**
![14](https://user-images.githubusercontent.com/77374876/144380797-c2a3e44f-464e-4410-94df-b670fd2bf88e.JPG)

**Agents tab:**
![15](https://user-images.githubusercontent.com/77374876/144380804-43833251-407d-4ebe-a843-a990e3261947.JPG)


As shared by @samratbhadra-qasource it is also working on mac self-managed 8.0 kibana.
Hence, we are **closing** this issue.
Thanks

**Comment by EricDavisX** [comment]
@amolnater-qasource did we use the same version of 8.0 Agent / ELK in both tests?  I'm worried that we have an intermittent bug that we are ignoring.  Would you mind doing 3-4 more tests on different templates of Windows 10 to help provide confidence (this will help as we aren't doing a dog-fooding server within the QA team recently)

**Comment by amolnater-qasource** [comment]
Hi @EricDavisX 
Above MAC and Windows tests were done on different builds.

**My build details for https://github.com/elastic/fleet-server/issues/935#issuecomment-984407576 :**
BUILD: 48385
COMMIT: 767b23ad878cb7ca94331b6402789a9846388852

Further we have revalidated on various Windows platforms:
- Windows 10 different VM.
- Windows 11 Vsphere
- Windows 11 QA Lab
- Windows 2012 r2
- Windows 2019

**Details:**
<HTML>
<BODY TEXT="#000000">
<TABLE FRAME=VOID CELLSPACING=0 COLS=3 RULES=NONE BORDER=0>
	<COLGROUP><COL WIDTH=86><COL WIDTH=86><COL WIDTH=86></COLGROUP>
	<TBODY>
		<TR>
			<TD STYLE="border-top: 1px solid #000000; border-bottom: 1px solid #000000; border-left: 1px solid #000000; border-right: 1px solid #000000" WIDTH=86 HEIGHT=50 ALIGN=CENTER VALIGN=MIDDLE><B>S.No.</B></TD>
			<TD STYLE="border-top: 1px solid #000000; border-bottom: 1px solid #000000; border-left: 1px solid #000000; border-right: 1px solid #000000" WIDTH=86 ALIGN=CENTER VALIGN=MIDDLE><B>OS</B></TD>
			<TD STYLE="border-top: 1px solid #000000; border-bottom: 1px solid #000000; border-left: 1px solid #000000; border-right: 1px solid #000000" WIDTH=86 ALIGN=CENTER VALIGN=MIDDLE><B>Able to Install Fleet Server</B></TD>
		</TR>
		<TR>
			<TD STYLE="border-top: 1px solid #000000; border-bottom: 1px solid #000000; border-left: 1px solid #000000; border-right: 1px solid #000000" HEIGHT=34 ALIGN=CENTER VALIGN=MIDDLE SDVAL="1" SDNUM="1033;">1</TD>
			<TD STYLE="border-top: 1px solid #000000; border-bottom: 1px solid #000000; border-left: 1px solid #000000; border-right: 1px solid #000000" ALIGN=CENTER VALIGN=MIDDLE>Windows 10 different VM.</TD>
			<TD STYLE="border-top: 1px solid #000000; border-bottom: 1px solid #000000; border-left: 1px solid #000000; border-right: 1px solid #000000" ALIGN=CENTER VALIGN=MIDDLE>Yes</TD>
		</TR>
		<TR>
			<TD STYLE="border-top: 1px solid #000000; border-bottom: 1px solid #000000; border-left: 1px solid #000000; border-right: 1px solid #000000" HEIGHT=34 ALIGN=CENTER VALIGN=MIDDLE SDVAL="2" SDNUM="1033;">2</TD>
			<TD STYLE="border-top: 1px solid #000000; border-bottom: 1px solid #000000; border-left: 1px solid #000000; border-right: 1px solid #000000" ALIGN=CENTER VALIGN=MIDDLE>Windows 11 Vsphere</TD>
			<TD STYLE="border-top: 1px solid #000000; border-bottom: 1px solid #000000; border-left: 1px solid #000000; border-right: 1px solid #000000" ALIGN=CENTER VALIGN=MIDDLE>Kibana Server Error</TD>
		</TR>
		<TR>
			<TD STYLE="border-top: 1px solid #000000; border-bottom: 1px solid #000000; border-left: 1px solid #000000; border-right: 1px solid #000000" HEIGHT=34 ALIGN=CENTER VALIGN=MIDDLE SDVAL="3" SDNUM="1033;">3</TD>
			<TD STYLE="border-top: 1px solid #000000; border-bottom: 1px solid #000000; border-left: 1px solid #000000; border-right: 1px solid #000000" ALIGN=CENTER VALIGN=MIDDLE>Windows 11 QA Lab</TD>
			<TD STYLE="border-top: 1px solid #000000; border-bottom: 1px solid #000000; border-left: 1px solid #000000; border-right: 1px solid #000000" ALIGN=CENTER VALIGN=MIDDLE>Yes</TD>
		</TR>
		<TR>
			<TD STYLE="border-top: 1px solid #000000; border-bottom: 1px solid #000000; border-left: 1px solid #000000; border-right: 1px solid #000000" HEIGHT=34 ALIGN=CENTER VALIGN=MIDDLE SDVAL="4" SDNUM="1033;">4</TD>
			<TD STYLE="border-top: 1px solid #000000; border-bottom: 1px solid #000000; border-left: 1px solid #000000; border-right: 1px solid #000000" ALIGN=CENTER VALIGN=MIDDLE>Windows 2012 r2</TD>
			<TD STYLE="border-top: 1px solid #000000; border-bottom: 1px solid #000000; border-left: 1px solid #000000; border-right: 1px solid #000000" ALIGN=CENTER VALIGN=MIDDLE>Yes</TD>
		</TR>
		<TR>
			<TD STYLE="border-top: 1px solid #000000; border-bottom: 1px solid #000000; border-left: 1px solid #000000; border-right: 1px solid #000000" HEIGHT=34 ALIGN=CENTER VALIGN=MIDDLE SDVAL="5" SDNUM="1033;">5</TD>
			<TD STYLE="border-top: 1px solid #000000; border-bottom: 1px solid #000000; border-left: 1px solid #000000; border-right: 1px solid #000000" ALIGN=CENTER VALIGN=MIDDLE> Windows 2019</TD>
			<TD STYLE="border-top: 1px solid #000000; border-bottom: 1px solid #000000; border-left: 1px solid #000000; border-right: 1px solid #000000" ALIGN=CENTER VALIGN=MIDDLE>Yes</TD>
		</TR>
	</TBODY>
</TABLE>
</BODY>

</HTML>

**Vsphere Windows 11 error:**
![20](https://user-images.githubusercontent.com/77374876/144589201-5a3fc8f2-250b-4ae1-81c2-d2fceb741758.JPG)

**Build details:**
BUILD: 48533
COMMIT: 5aa6ba67117aed73772be3d0c0db6cf5714a626
Artifact Link: https://snapshots.elastic.co/8.0.0-bf35acb3/downloads/beats/elastic-agent/elastic-agent-8.0.0-SNAPSHOT-windows-x86_64.zip

**Conclusion:**
We haven't observed this issue on any other VM template.

Please let us know if anything else is required.
cc: @jlind23

**Comment by EricDavisX** [comment]
@amolnater-qasource thanks - let's log the win 11 issue separately and, if you don't reproduce it consistently we can close it out too.  but it is helpful to have a record of it.  thanks so much for the re-testing
