### ISSUE TITLE
Windows7 Windows2008 R2 can't install elastic-agent 

### ISSUE THREAD

**Issue by Oddluo** [elastic/fleet-server#942]
For confirmed bugs, please report:
- Version: Elastic-Agent 7.15.2
- Operating System: Windows7/Windows Server2008R2
- Steps to Reproduce: 
1.Get into the kibana --Fleet 
2.Add Agent and follow the steps to install
3.in the cmd/powershell that shows Error--fleet-server-failed context cancled
![图片](https://user-images.githubusercontent.com/67694128/144184611-bb826317-a1c3-49b9-af0d-1df8675eb0ab.png)

**Comment by jlind23** [comment]
[Clean up] Closing this as outdated.
