### ISSUE TITLE
Configuration of elastic-agent from fleet

### ISSUE THREAD

**Issue by poulaone** [elastic/fleet-server#948]
Hello,
I'm using ELK 7.15.
I don't understand how to configure elastic-agent from fleet in Kibana.
I want to make some changes on filebeat and other agent.
It is documented here https://www.elastic.co/guide/en/fleet/current/dynamic-input-configuration.html
But i don't know where to put the directives.
Thanks

Bye

**Comment by nimarezainia** [comment]
Please have a look at the Quick Start guides here: https://www.elastic.co/guide/en/fleet/current/index.html

**Comment by jlind23** [comment]
Closing it as @nimarezainia provided guidance.
