### ISSUE TITLE
update elastic/beats in go.mod once v8.0.0 has been released

### ISSUE THREAD

**Issue by michel-laterman** [elastic/fleet-server#971]
PR https://github.com/elastic/fleet-server/pull/970 updated the go.mod file to an untagged commit on the 8.0 branch to allow fleet-server to use up to date code from libbeat (specifically new ca fingerprint handling).

Once `v8.0.0` has been released and tagged we should set our go.mod to refer to this version.

**Comment by michel-laterman** [comment]
Currently the `go.mod` of the beats repo is set to have the `v7` major version. go detects incompatible major versions when trying to update to `v8.x`. We will not be able to use a tagged version of the beats module unless the module is updated to point provide v8 paths.

An alternative solution is to change the beats import to use https://github.com/elastic/elastic-agent-libs

**Comment by ph** [comment]
Yes, the data plane have looked at moving to v8, but that decided the number of changes didn't worth the risk.  So we will run off a commit for a long time.

**Comment by ph** [comment]
See this https://github.com/elastic/beats/pull/31213#event-6407482014 I will close this issue.
