### ISSUE TITLE
[7.16.0>8.0]: Unable to initialize fleet on upgrading 7.16.0 Snapshot to 8.0 Snapshot.

### ISSUE THREAD

**Issue by amolnater-qasource** [elastic/fleet-server#976]
**Kibana version:**  7.16.0 Snapshot Upgrade to 8.0 Snapshot Kibana Cloud environment

**Host OS and Browser version:** All, All

**Preconditions:**
1. 7.16.0 Snapshot Kibana Cloud environment should be available.

**Steps to reproduce:**
1. Login to Kibana environment.
2. Trigger Upgrade from edit deployment page.
3. Observe all modules upgraded successfully except APM & Fleet.
4. Navigate to Kibana observe user is able to access various tabs like> Security etc.
5. Navigate to Fleet tab, observe unable to initialize fleet error.

**Expected Result:**
User should be able to access Fleet UI after upgrading from 7.16.0 Snapshot>8.0 Snapshot

**Screenshot:**
![3](https://user-images.githubusercontent.com/77374876/145167253-3ec99b49-a615-4264-87cf-75f60565b5fd.JPG)

![2](https://user-images.githubusercontent.com/77374876/145166984-6ea01ea8-c304-4e78-880f-12490240af1c.JPG)

**Comment by amolnater-qasource** [comment]
@manishgupta-qasource Please review.

**Comment by manishgupta-qasource** [comment]
Reviewed & mention to @elastic/elastic-agent-control-plane

CC: @EricDavisX

**Comment by jlind23** [comment]
@amolnater-qasource what are the logs that you have?
@michalpristas @blakerouse does it sound familiar to you?

**Comment by amolnater-qasource** [comment]
Hi @jlind23 
We added integrations like- Windows, Linux, Endpoint and Nginx and installed MAC, Windows and Linux agents on 7.16.0 Snapshot.

Could you please confirm which logs you want us to fetch apart from the error(screenshots pasted under reported issue).

Yesterday, we were getting this issue.
Entire kibana was accessible however only fleet tab was blocked.

Today when we attempted to reproduce this we faced different issue, in which entire kibana was blocked and deployment gets **Unhealthy**.
For this we have reported issue at https://github.com/elastic/cloud/issues/93865 

Thanks

**Comment by jlind23** [comment]
@amolnater-qasource one question - Was the fleet linux binary pushed to staging? @joshdover does it sound familiar to you?

**Comment by EricDavisX** [comment]
@jlind23 I will guess what you refer to above, are you asking about if the Linux Docker Container for Fleet&APM was recently pushed up / available to use in Cloud?  There is a multi-stage build process... starting with the stack and then it being setup in a 'stack pack' for the cloud release (and in parallel, the cloud builds their code to deploy to QA/Staging servers during testing - the QA/Staging cloud servers consume the same versions of the stack.  
The stack builds are here: https://internal-ci.elastic.co/view/Unified%20Release%20-%20snapshot/
 - we can look at it more Monday and try to correlate build hashes or general time-stamps to know what we need to.

**Comment by jlind23** [comment]
@amolnater-qasource could you tell us what particular hash you are on? Do you still face this issue?
All snapshots from Friday seems to be available.
Thanks @EricDavisX for understanding what i wanted to say... 👍🏼

**Comment by amolnater-qasource** [comment]
Hi @jlind23 
We don't have that build with this issue available now. 
However currently we are not able to deploy any latest 8.0 Snapshot builds to reproduce this as per reported issue https://github.com/elastic/cloud/issues/93865 

Hence we are blocked to test kibana upgrades.
Please let us know if anything else is required.
