### ISSUE TITLE
fleet-server username/password feature must be deprecated in 7.16 / 7.17

### ISSUE THREAD

**Issue by jlind23** [elastic/fleet-server#977]
**Describe the enhancement:**
Write access to Elasticsearch using username/password must be deprecated.

**Comment by ruflin** [comment]
This must not only be deprecated in fleet-server itself but also Elastic Agent which has environment variables and likely other code around for these config options.

**Comment by michel-laterman** [comment]
Deprecation messages have been added to fleet-server and the elastic-agent in 7.17 and backported to 7.16.
The docs pr for it is https://github.com/elastic/observability-docs/pull/1409

**Comment by jlind23** [comment]
@michel-laterman as soon as the doc PR is closed, this issue can be closed too. Agree?

**Comment by michel-laterman** [comment]
agreed

**Comment by jlind23** [comment]
Done thanks to @michel-laterman
