### ISSUE TITLE
Too many checkins on scale up / down

### ISSUE THREAD

**Issue by ruflin** [elastic/fleet-server#983]
Today in Elastic Cloud when the users scales up / down the fleet-server container, a new container is spun up with the new size and then the old one is shut down. As the fleet-server keeps the connection open to all Elastic Agent connected, this means all Elastic Agent will check into the new fleet-server at the same time which also sends all the info at the same time. This could overload the system. 

This issue is to discuss if this is actually and issue on larger scale and if yes, how we should work around. Some ideas so far:

* jitter: Elastic Agents should use some jitter on how quickly to check in again to make sure not all Elastic Agent always check in at exact the same time especially after the connection is dropped
* Graceful hand over: When fleet-server shuts down, there should be a period where the fleet-server starts to disconnect Elastic Agents, keeps some alive but does not accept new ones anymore. Like this over a period of time Elastic Agents could be handed over.

**Comment by ruflin** [comment]
@blakerouse I remember you had some more ideas, could you add them?

**Comment by blakerouse** [comment]
Another idea would be to only allow a Fleet Server to accept an X number of Elastic Agents per length of time (say like no more than 50 in 100ms). That would help the Fleet Server from trying to process all new connections in a quick amount of time, it could either queue the other connections or drop the extras having them retry.

**Comment by blakerouse** [comment]
I think adding jitter on the Elastic Agent side should be the first step.

**Comment by michel-laterman** [comment]
I think we've implemented all of this by now, jitter in the ES agent, rate limiting as part of fleet-server, and graceful connection termination (for checkins) on fleet-server
